### ISSUE TITLE
Implement/prototype a new framework that implements the design guidelines

### ISSUE THREAD

**Issue by ruphy** [italia/bootstrap-italia#1]
We currently have one reference implementation of the user interface design guidelines. Create a prototype to provide a toolkit for Bootstrap (4) developers.

Link:
- [The current reference implementation (source)](https://github.com/italia/design-web-toolkit)
- https://italia.github.io/design-web-toolkit/
- https://design-italia.readthedocs.io/it/stable/doc/user-interface.html

**Comment by francescozaia** [comment]
We started working actively on the project, closing this.

**Comment by ruphy** [comment]
@francescozaia make sure you add the "help wanted" label for all tasks up for grabs. I will regenerate the website periodically ;-)
