### ISSUE TITLE
Il componente chips non coincide con UI kit Italia

### ISSUE THREAD

**Issue by zetareticoli** [italia/bootstrap-italia#1024]
## Versione di Bootstrap Italia

v2.7.7

## Comportamento atteso
L'aspetto visivo (font, spacing, size) e le varianti devono essere le stesse presenti nella scheda del componente presente in UI kit Italia.

In Bootstrap Italia esistono le varianti alte 24px (default) e 32px (lg). 
In UI Kit Italia esistono le varianti alte 24px (small), 40px (medium) e 48px (large). 

![Chips in Bootstrap Italia](https://github.com/italia/bootstrap-italia/assets/6736103/430fdca8-906b-427d-a1ec-29104a4df030)
![Chips in UI Kit Italia](https://github.com/italia/bootstrap-italia/assets/6736103/02cc0822-af2c-4f71-ae92-07faa5307384)

## Comportamento attuale
Le varianti non hanno gli stessi nomi, le scelte di `font-size` e `padding` sono differenti. Questo comporta una diversa altezza del componente e dei suoi elementi interni (label, icone).

## Possibili soluzioni
1. Rivedere i valori utilizzati per l'elemento, utilizzando dove possibile variabili locali del componente.
2. Rimuovere il valore di `min-width` per consetire alla chips di estendersi quanto il contenuto, senza dimensioni fisse minime. /cc @Fupete 
3.  Abilitare effetto `:hover` solo quando presente un link

**Comment by astagi** [comment]
@Fupete riporto la discussione qua dentro, almeno abbiamo un'unica issue. Modificata la precedente per le sole spaziature.

**Comment by astagi** [comment]
Riporto inoltre le considerazioni di @alessandrovecchi

Mia opinione, 40px e 48px mi sembrano molto grandi.
Inoltre per una scalatura più corretta sarebbe meglio 24px (small), 36px (medium) e 48px (large).

**Comment by Fupete** [comment]
Stale stai tranquillo. Qui per reminder.

**Comment by zetareticoli** [comment]
Sono d'accordo che le misure 40px o 48px risultano eccessive. Ritengo che le due opzioni presenti in BS Italia siano più che sufficienti, quindi ridurrei le opzioni previste in UI Kit Italia.
