### ISSUE TITLE
Controllare uso corretto di `<a>`ncore. Usare `<button>` dove necessario.  

### ISSUE THREAD

**Issue by Fupete** [italia/bootstrap-italia#1029]
## Comportamento atteso

Azioni sulla pagina (collapse, dropdown, ...) devono essere attivate dal nativo tag html `<button>`. 
Dovremmo usare il tag html `<a>` **solo** per navigazione (ancore, pagine, ....).
Dovremmo evitare laddove non necessario soluzioni ibride, per es. usando `role=button` su tag `<a>`. 

## Comportamento attuale

Dalle scoperte fatte in questa https://github.com/italia/designers.italia.it/issues/1108#issuecomment-1835757046 su Designers Italia, e da quanto già rilevato per il lavoro sul Megamenu in corso https://github.com/italia/bootstrap-italia/issues/995, ci sono sicuramente check e fix da fare su alcuni componenti (header, nav-scroll, dropdown, ...).

## Componenti/esempi da controllare ed eventualmente sistemare

- [x] [dovunque c'è un back button](https://github.com/search?q=repo%3Aitalia%2Fbootstrap-italia+it-back-button+language%3AMarkdown&type=code&l=Markdown) (se serve a chiudere un menu per es.)
- [x] [dovunque c'è un role="button"](https://github.com/search?q=repo%3Aitalia%2Fbootstrap-italia+role%3D%22button%22+language%3AMarkdown&type=code&l=Markdown)
- [x] [dovunque c'è un dropdown](https://github.com/search?q=repo%3Aitalia%2Fbootstrap-italia+dropdown+language%3AMarkdown&type=code)
- [x] [dovunque c'è un collapse](https://github.com/search?q=repo%3Aitalia%2Fbootstrap-italia+collapse+language%3AMarkdown&type=code)
- [x] [dovunque c'è una classe che comprende -buttons](https://github.com/search?q=repo%3Aitalia%2Fbootstrap-italia+-buttons+language%3AMarkdown&type=code)

(smarcate man mano dal progress della PR collegata https://github.com/italia/bootstrap-italia/pull/1037)

**Comment by cfabry** [comment]
Si @Fupete confermo quanto hai già scritto: è importante sempre distinguere chiaramente i due ruoli semantici di `<a>` e `<button>`.
L'elemento <a> ha come ruolo implicito "link" e, come da standard W3C [ARIA in HTML](https://www.w3.org/TR/html-aria/#docconformance), è consentito l'uso di role="button" per sovrascrivere tale ruolo.
Tuttavia <a role="button"> è un non-sense essendo disponibile il tag nativo <button>. Quindi, in tutti i casi in cui sia possibile, è meglio optare per la sostituzione del tag, senza usare l'attributo ARIA.
Rimane chiaramente una strada possibile se non si può fare diversamente.

**Comment by Fupete** [comment]
@astagi, reminder: abbiamo concordato con @cfabry che appena rilasciata la [PR](https://github.com/italia/bootstrap-italia/pull/1037) di fix, apriremo una nuova issue per tracciare un approfondimento da fare anno nuovo per documentare l'uoso dell'attributo `tabindex="0"` nei casi necessari laddove si sia in presenza di un attributo `role="button"`.
