### ISSUE TITLE
Errato reindirizzamento documentazione

### ISSUE THREAD

**Issue by cvrboni** [italia/bootstrap-italia#1032]
## Versione di Bootstrap Italia

v2.7.8

## Comportamento atteso

Rimanda correttamente alla pagina dei bottoni

## Comportamento attuale

Nella documentazione al link https://italia.github.io/bootstrap-italia/ , quando vado a cercare bottoni 
![Screenshot 2023-12-05 104332](https://github.com/italia/bootstrap-italia/assets/136789082/dafccebc-4b32-4d8d-b1b5-07ceb6187d7a)
Rimanda ad una pagina errore :
![Screenshot 2023-12-05 104921](https://github.com/italia/bootstrap-italia/assets/136789082/6029d766-e5cd-4e84-a7ef-95e48c28356b)
penso che il link corretto che dovrebbe rimandare sia: https://italia.github.io/bootstrap-italia/docs/componenti/buttons/ 

## Possibili soluzioni

Correggere il link

## Contesto

Non è niente di grave, mi è capitato un paio di volte, penso possa essere utile fixarlo, visto che inizialmente pensavo che fosse stata eliminata la pagina in sè

**Comment by astagi** [comment]
Grazie @cvrboni ci diamo subito un'occhiata.

**Comment by astagi** [comment]
@cvrboni siamo in contatto con Algolia speriamo di risolvere il problema entro anno nuovo. Grazie per la segnalazione e la pazienza!

**Comment by Fupete** [comment]
still active mr @stale

**Comment by AlessandroVecchi** [comment]
> still active mr @Stale

ma non si può disattivare lo stale? non è di nessuna utilità.

**Comment by Fupete** [comment]
@AlessandroVecchi in realtà in un ecosistema di repo che vengono da lontano nel tempo con molte versioni stratificate, e una community potenziale di migliaia di utilizzatori e contributori, si è rilevato decisamente utile in questi anni a lasciare in backlog solo segnalazioni rilevanti. Oltre obbligare noi maintainer a portarci spesso l'attenzione. 

Direi @astagi che si potrebbe valutare se allungare il tempo di reazione passati questi due anni di ripresa delle risorse.

**Comment by AlessandroVecchi** [comment]
@Fupete capisco ma l'attività e la partecipazione si è notevolmente ridotta ed il rischio è che alcuni bug finiscano dimenticati o non tracciati.

es.
![Screenshot 2024-02-13 120736](https://github.com/italia/bootstrap-italia/assets/20642463/6dd7046e-6cd7-4ef7-baf0-a0553257e431)

**Comment by Fupete** [comment]
@AlessandroVecchi apri una issue ad hoc sul tema Stale per favore. Sposta lì la discussione, sennò questa relativa ad Algolia la perdiamo.
