### ISSUE TITLE
Uso della classe text-decoration-none

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#1045]
## Versione di Bootstrap Italia

2.7.9

## Comportamento atteso

Applicando la classe `text-decoration-none` nelle precedenti versioni di BI veniva tolta la sottolineatura sui link ma era sempre presente sull'hover.

## Comportamento attuale

Adesso la sottolineatura è disattivata anche sull'hover del link.
All'interno del CSS di BI vedo definizioni contrastasti e quella con !important ovviamente prevale

```
a.text-decoration-none:hover {
    text-decoration: underline;
}
.text-decoration-none {
    text-decoration: none !important;
}
```

## Possibili soluzioni

Io ripristinerei lo stato precedente togliendo `!important` ma non so il motivo della scelta che ha portato alla modifica

**Comment by Fupete** [comment]
Grazie @AlessandroVecchi per la segnalazione. 

In realtà lo stile con forzato `!important` viene dalle ultime versioni di Bootstrap, dove il sottolineato è stato tolto anche dall'hover se applichi `.text-decoration-none`. Si veda https://getbootstrap.com/docs/5.3/utilities/text/#text-decoration). 

Delle due una: 
1. adeguarsi a Bootstrap e togliere la ns classe per l'hover sottolineato;
2. forzare anche il ns hover (nel file `_type.scss`) con `!important`, per recuperare il precedente comportamento. Premesso che ovviamente non possiamo togliere `!important` da Bootstrap 🤷 .

Lascerei a te @zetareticoli la scelta coordinandola anche con quanto su UI Kit Italia.

**Comment by zetareticoli** [comment]
Sarei per allinearci alla libreria genitore. 

Nello UI kit definiamo stili di link con e senza `underline` ma non in modo specifico per gli stati interattivi. 

Credo che il comportamento di "default" (ovvero di un `<a>` normale, senza classi specifiche) debba essere quello di prevedere sempre `underline` su :hover. 

La funzione di una `utility class` è proprio quella di sovrascrivere questo comportamento.
