### ISSUE TITLE
[a11y] Contrasto colore campi disabled

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#1059]
## Versione di Bootstrap Italia

2.7x

## Comportamento atteso

Come ogni rapporto di contrasto primo piano/sfondo anche quello nei campi disabled o readonly dovrebbe essere > 4.5 

## Comportamento attuale

https://italia.github.io/bootstrap-italia/docs/form/input/#disabilitato
Al momento il rapporto è 3.61

## Possibili soluzioni

SI potrebbe scurire il testo (es. con un elegante #506070 rientriamo nei parametri) o schiarire lo sfondo... o entrambi.
La soluzione più logica potrebbe essere ereditare i parametri di Bootstrap 5.2 che sono già corretti.

**Comment by Fupete** [comment]
Ciao @AlessandroVecchi gli elementi interattivi "disabled" non hanno obblighi di contrasto dalle WCAG. Il tema è già stato affrontato qui https://github.com/italia/bootstrap-italia/issues/761#issuecomment-1302024836

**Comment by AlessandroVecchi** [comment]
Ok grazie!
