### ISSUE TITLE
Gruppi di input checkbox, radio e toggles

### ISSUE THREAD

**Issue by cfabry** [italia/bootstrap-italia#1069]
## Versione di Bootstrap Italia

2.8.2

## Descrizione del problema

Nella sezione **[Gruppi](https://italia.github.io/bootstrap-italia/docs/form/radio-button/#gruppi)**, si suggerisce una modifica del layout di default per gli elementi grafici di spunta per spostarli a destra. Tuttavia il nome "Gruppi", potrebbe essere fuorviante e richiamare all'uso della classe CSS per "**raggruppare**" i campi di input.
Invece il "raggruppamento" di campi di input, quando semantico, deve poter essere fatto con l'elemento nativo `<fieldset>`.

## Possibili soluzioni

Si potrebbe rinominare la sezione con un nome più consono e/o inserire un alert di accessibilità che possa invitare gli sviluppatori all'uso corretto di `<fieldset>`, spiegando che la soluzione indicata è puramente visiva, senza valore semantico.

## Contesto
Aggiornato da @Fupete 2/9/2024: 

Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

**Comment by Fupete** [comment]
Reference utile uscita questi giorni: https://www.tpgi.com/fieldsets-legends-and-screen-readers-again/

**Comment by Fupete** [comment]
@cfabry se rimandiamo al pattern aria di riferimento? Ad esempio per i Radio button: https://www.w3.org/WAI/ARIA/apg/patterns/radio/ magari anche implementando già role, aria-label etc. corretti nel markup?

**Comment by Fupete** [comment]
⚠️ Da notare che vale anche per `Checkbox`, non solo per `Radio`.

**Comment by Fupete** [comment]
Segnalo inoltre qui su Carbon la corretta implementazione dei `<fieldset>` con `<legend>` del gruppo. Può essere utile all'implementazione. 

Aggiungerei poi alla presente issue, visto che ci siamo, che probabilmente in queste varianti "Gruppi" sarebbe da ricontrollare anche la semantica dei testi "<small>" integrati.
