### ISSUE TITLE
Timepicker non visualizzato correttamente con Firefox

### ISSUE THREAD

**Issue by simomosi** [italia/bootstrap-italia#1073]
## Versione di Bootstrap Italia

2.8.2

## Comportamento atteso

Così come con Chrome,  anche con Firefox l'input di tipo "time" deve mostrare l'icona dell'orologio che permette di selezionare l'ora.

## Comportamento attuale

L'icona dell'orologio non viene mostrata.  
Il problema è visualizzabile anche navigando la doc: https://italia.github.io/bootstrap-italia/docs/form/input-ora/

## Contesto

Testato con:
- l'ultima versione di Firefox 122.0.1 (il problema è presente)
- l'ultima versione di Firefox Developer 123.0b9 (64 bit) (il problema è presente)
- l'ultima versione di Chrome 121.0.6167.185 (Build ufficiale a 64 bit) (il problema NON è presente)

**Comment by Fupete** [comment]
Confermo il bug segnalato da @simomosi, e aggiungo che riguarda anche Safari. 

Ho testato via Browserstack anche con: 
- **Safari** per Mac, latest (🔴 il problema è presente)
- **Firefox** per Mac e Windows, latest (🔴 il problema è presente)
- **Chrome** per Mac e WIndows, latest (🟢 il problema NON è presente)
- **Edge** per WIndows e Mac, latest (🟢 il problema NON è presente)

Da verificare anche i comportamenti su mobile.

FYI @astagi @zetareticoli

**Comment by zetareticoli** [comment]
Se siete d'accordo, chiudo come _not planned_
