### ISSUE TITLE
Link non sottolineati nelle liste

### ISSUE THREAD

**Issue by cfabry** [italia/bootstrap-italia#1077]
## Versione di Bootstrap Italia 
2.8.2

## Comportamento atteso
I link nelle [liste](https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/liste/) devono essere sottolineati.

Aggiornato da Fupete 17/9/2024:
Aggiungo alla presente anche il problema che il "Link attivo" ha lo stesso colore del testo attualmente 🤔 

## Possibili soluzioni
Valutare se gestire direttamente con CSS text-decoration

### Perché
Aggiornato da Fupete 17/9/2024:
Visivamente accessibile. Comprensibile. 

### Contesto
Aggiornato da Fupete 17/9/2024:
Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

### Altro
Aggiornato da Fupete 17/9/2024:

Problema presente anche in UI Kit Italia, React kit e Angular kit. 
Qui la issue UI Kit Italia: https://github.com/italia/design-ui-kit/issues/119

**Comment by siddharthbaleja7** [comment]
Puoi assegnarmi questo problema per favore?

**Comment by Fupete** [comment]
Vedi anche https://github.com/italia/design-ui-kit/issues/119 per risolvere in UI Kit Italia.
