### ISSUE TITLE
Didascalia sopra all'immagine

### ISSUE THREAD

**Issue by cfabry** [italia/bootstrap-italia#1079]
## Versione di Bootstrap Italia
2.8.2

## Comportamento attuale
Nelle [liste di immagini](https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/liste-di-immagini/#standard-con-didascalie) è stata introdotta una casistica [non presente nelle immagini](https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/immagini/), dove **la didascalia viene posta sopra l'immagine**. 

## Possibili soluzioni
Sarebbe auspicabile che tale casistica fosse riportata anche nelle immagini, e non solo nelle liste, che sono soltanto un'applicazione dell'esempio base in immagini.
In immagini è necessario inserire un **alert di accessibilità** che spieghi che: "la classe CSS "it-grid-item-overlay" genera un effetto di trasparenza perché altrimenti il testo sopra le immagini non è consentito in quanto non è possibile garantire, in ogni contesto, il giusto contrasto di colore tra testo e sfondo. Pertanto si consiglia, in ogni caso, di usare il testo sopra le immagini soltanto quando non è possibile fare diversamente e, in ogni caso, limitarsi a implementare la soluzione suggerita senza eliminare o modificare l'effetto trasparenza.

## Contesto
Questo si rende necessario perché si rilevano molte implementazioni di testo sopra le immagini quasi sempre in modo non accessibile. Mancando l'esempio nella sezione Immagini, chi implementa può essere indotto a soluzioni "fai da te".

**Comment by zetareticoli** [comment]
Issue collegata a #1078 e risolta in #1150
