### ISSUE TITLE
regole di visbilità dell'Hamburger Menu su desktop 

### ISSUE THREAD

**Issue by groundrace** [italia/bootstrap-italia#1080]
Quello di rendere obbligatorio il menù aperto su dektop dovrebbe essere un suggerimento più che un obbligo, anche per una questione di aderenza alla boostrap dalla quale si parte dove ognuno decide come gestire questa funzionalità sui vari breakpoint

nel design system quindi è obbligatorio avere il menu visibile per width > 992px ?
Non è una regola un po' troppo limitante?
il modo in cui è implementato sulla `_navigation.scss`

```
...
//Tablet horizontal / small desktop
@media (min-width: #{map-get($grid-breakpoints, lg)}) {
  .row.row-column-border > [class^='col-'] .navbar {
    padding: 0;
  }

  .navbar {
    background: $navigation-bg-color-desktop;
    padding: 0;

    // navbar mobile
    .navbar-collapsable {
      position: relative;
      top: auto;
      right: auto;
      left: auto;
      bottom: auto;
      z-index: auto;
      background: none;
      display: block !important; //-sovrascrive l'inline style di jquery
      transition: none;
...
``` 
che prevede una `[!important](display: block !important;)` ci pare troppo bloccante per un potenziale riuso che intenda comunque non visualizzare il menu. 

Vedi anche #859

**Comment by Fupete** [comment]
Ciao @groundrace. 

La scelta di mostrare la barra di navigazione aperta su dispositivi con viewport sufficientemente larghe credo sia ancora oggi supportata dalle fonti primarie dell'epoca in cui fu presa (durante la progettazione della seconda generazione delle risorse del design system tra il 2017 e il 2021). In particolare ti segnalo: 
- lo storico articolo NNGroup qui lato usabilità: https://www.nngroup.com/articles/hamburger-menus/
- l'approfondimento di Adrian lato usabilità e accessibilità aggiornato poi negli anni qui: https://adrianroselli.com/2016/01/avoid-the-hamburger-menu-for-desktop-layouts.html. 

Ovviamente ormai l'uso mobile ha largamente superato il desktop rispetto al 2016, e l'utente è sempre più abituato a dispositivi mobile, ma c'è da dire che qui stiamo parlando di usare il "burger" su desktop, che è bel altro contesto e secondo me la scelta rimane solida.

Detto questo, come già citato da @astagi al termine della discussione nella issue che citi #859, è sempre possibile per casi specifici forzare la presenza del burger menu anche su dispositivi con viewport più ampie, nonostante il default. Ti suggerirei di testarne i risultati e l'efficacia con utenti nel contesto specifico e magari condividere qui i risultati; personalmente mi limiterei comunque a usare l'eventuale soluzione forzata solo per dispositivi touch con grandi schermi per un approccio conservativo.  

Se esistono fonti con ricerche più aggiornate di usabilità e accessibilità sul "burger" che aggiornano quanto sopra ovviamente più che benvenute!

Un saluto.
