### ISSUE TITLE
Problemi con il funzionamento del menu di navigazione su dispositivi mobili

### ISSUE THREAD

**Issue by peyman1987** [italia/bootstrap-italia#1087]
Abbiamo integrato il componente Header nav in un progetto Angular versione 16.2.12. Tuttavia, abbiamo riscontrato un problema nella modalità per dispositivi mobili. Quando si clicca sul pulsante del menu, il menu-wrapper appare brevemente e poi scompare immediatamente. Inoltre, se si clicca nuovamente sul pulsante del menu, il menu si chiude molto veloce.

Per escludere possibili conflitti CSS nel nostro progetto, abbiamo creato un nuovo progetto Angular con la versione "^17.2.0" e abbiamo copiato direttamente il codice dal sito https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/. Tuttavia, il problema persiste anche in questo nuovo progetto.

**Comment by zetareticoli** [comment]
Ciao @peyman1987 , hai una demo da mostrare per capire bene il problema da te descritto?

Ci sono errori in console?

**Comment by astagi** [comment]
Chiudo per inattività
