### ISSUE TITLE
navigazione tab dropdown

### ISSUE THREAD

**Issue by davidefrancesconi** [italia/bootstrap-italia#1091]
## Versione di Bootstrap Italia
[https://designers.italia.it/design-system/componenti/dropdown/]

## Comportamento atteso

In caso di navigazione da tastiera con tab il comportamento atteso dovrebbe essere spostare il focus al prossimo elemento focusabile  (fonte [https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/listbox/listbox-collapsible.html]) 

## Comportamento attuale

Navigazione tramite tab mi sposta il focus su un item della lista

## Possibili soluzioni

Gestire la navigazione dei list items solo attraverso le frecce e con il tab spostarsi al prossimo elemento focusabile nel dom

**Comment by cfabry** [comment]
Si @Fupete confermo, il comportamento del componente è corretto. 
@davidefrancesconi se non mi sbaglio il link che metti è della vecchia aria-practices che è ormai deprecata, ora c'è tutto il progetto [APG](https://www.w3.org/WAI/ARIA/apg/).
In ogni caso, il comportamento che segnali è tipico dei ruoli "menu", che però non si devono confondere con i ruoli i ruoli di "navigation" e in ogni caso non adatto al componente generico dropdown che, nella quasi totalità dei casi, non sarà utilizzato in un role menu.
