### ISSUE TITLE
Aggiunta icone

### ISSUE THREAD

**Issue by McAle16** [italia/bootstrap-italia#1093]
## Versione di Bootstrap Italia

2.8.3

## Comportamento atteso

Aggiunta icone:
* file immagine (come per il video e l'audio farebbe comodo avere l'icona per l'immagine)
* file xlsx
* file docx
* firma
* file firmato

Come esempio per firma e file firmato mostro fontawesome https://fontawesome.com/icons/file-signature?f=classic&s=solid
Per l'icona della firma sarbbe bello avere la penna con la firma senza il file di sfondo.

**Comment by McAle16** [comment]
Aggiungo come richiesta anche l'icona dell'aereo di carta, utile per indicare il processo d'invio.

**Comment by aniketkumar7** [comment]
Puoi spiegarmi dove posso aggiungere le icone?

**Comment by McAle16** [comment]
Intendi questa sezione https://italia.github.io/bootstrap-italia/docs/utilities/icone/ ?
Avevo aperto una issue per l'aggiunta di un'altra icona e è stata risolta, quindi se ti serve per prendere spunto te la allego https://github.com/italia/bootstrap-italia/issues/1082

**Comment by astagi** [comment]
@McAle16 @aniketkumar7 chiusa in favore di questa https://github.com/italia/bootstrap-italia/issues/1297
