### ISSUE TITLE
SyntaxError - ")" is expected

### ISSUE THREAD

**Issue by guildenstern70** [italia/bootstrap-italia#1098]
## Versione di Bootstrap Italia

2.8.x

## Comportamento atteso

Nessun errore in console o quando si importa il CSS via @import.

## Comportamento attuale

Quando aggiunto a una pagina, il CSS dà un errore di sintassi in console. 

`Uncaught SyntaxError: Unexpected token ':'`

<img width="432" alt="Screenshot 2024-04-12 at 09 09 05" src="https://github.com/italia/bootstrap-italia/assets/1478060/baf8a2fc-4ebc-4dfc-8c3c-cfeba3f7a192">

Se aggiunto via @import e analizzato con un parser, ad esempio in file SASS, dà un errore

`")" is expected` 

<img width="1237" alt="Screenshot 2024-04-12 at 09 11 34" src="https://github.com/italia/bootstrap-italia/assets/1478060/ac3a3e45-aba5-4db1-90e4-0f5d6a415f99">

**Comment by zetareticoli** [comment]
Ciao, ho eseguito alcuni test di validazione CSS e SCSS, la sintassi è corretta.

Piuttosto, l'utilizzo della funzione `alpha` dovrebbe essere ormai deprecata, in quanto utilizzata in passato per supportare vecchie versioni di IE.

Sarebbe quindi utile rimuoverla in favore di una sintassi semplificata.
