### ISSUE TITLE
Modali e sticky

### ISSUE THREAD

**Issue by ambr89** [italia/bootstrap-italia#1104]
## Versione di Bootstrap Italia

 Bootstrap Italia 2.8.4

## Comportamento atteso

Mi aspetto che un pop up Modale abbia lo sfondo che vada graficamente sopra uno stiky.

## Comportamento attuale

All'interno del codice ho un menù che si collassa e rimane fisso in alto con uno sticky e una modale che a popUp si apre.
Al momento lo sfondo della modale rimane sotto allo sticky.

Il menu è stato fatto seguendo le linee guida:
https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/#header-sticky

<img width="1132" alt="image" src="https://github.com/italia/bootstrap-italia/assets/34572512/c518a759-99c5-4349-bef3-fe001f5fceaf">

Ho provato anche a cambiare lo z-index della modale ma lo sfondo "nero trasparente" non si riesce in nessun modo ad alzarlo sopra allo stikcy.

**Comment by zetareticoli** [comment]
@ambr89 puoi condividere il codice CSS utilizzato per modal e sticky?

**Comment by ambr89** [comment]
Si,
abbiamo preso la documentazione usata qui:
https://italia.github.io/bootstrap-italia/docs/componenti/sticky/
e in particolare il codice usato qui:
https://italia.github.io/bootstrap-italia/docs/esempi/sticky-target/

che all'interno di `_sticky.scss row 6` ha:
```
.bs-is-fixed {
    position: fixed !important;
    z-index: 10000 !important;
}
```

se prendete la documentazione della modale e lanciate la "demo semplice"
https://italia.github.io/bootstrap-italia/docs/componenti/modale/

vedrete che la modal usa la classe 
`_modal.scss row 10` che ha:

```
.modal {
    --bs-modal-zindex: 1055;
...
}
```

Segue che a meno di forzare in un css custom lo z index dello sticky riportandolo ad un valore più basso, non si avranno mai delle modali sopra al menu di navigazione.

**Comment by Fupete** [comment]
Penso sia un tema collegato a questa segnalazione da un po' in attesa di lavorazione https://github.com/italia/bootstrap-italia/issues/1009 (cc @bfabio @astagi)

**Comment by zetareticoli** [comment]
Resolved in #1118
