### ISSUE TITLE
Aggiunta icone

### ISSUE THREAD

**Issue by ambr89** [italia/bootstrap-italia#1105]
## Versione di Bootstrap Italia

2.8.4

## Comportamento atteso

Aggiunta icone:

- carrello ( cart ) 
- logo pagoPA ( utile per i pulsanti che portano ad un pagamento pagoPa )
- badge "integrato con pagoPA"
- macchinina ( car ) 

Info for pagoPa logos:
https://docs.pagopa.it/linee-guida-brand-pagopa/risorse-utili/scarica-gli-asset-grafici

**Comment by AlfioCostanzo** [comment]
Aggiungo alla richiesta, se possibile

- Spotify

Grazie

**Comment by astagi** [comment]
Chiusa in favore di questa https://github.com/italia/bootstrap-italia/issues/1297 @AlfioCostanzo @ambr89
