### ISSUE TITLE
Ordine dei contenuti per le card

### ISSUE THREAD

**Issue by cfabry** [italia/bootstrap-italia#1116]
## Versione di Bootstrap Italia 
2.8.7

## Comportamento attuale
Nelle [card](https://italia.github.io/bootstrap-italia/docs/componenti/card/#card-articolo-semplice) quando contengono anche la categoria, la sequenza delle informazioni non è corretta. Il titolo dovrebbe essere il primo elemento e tutti eventuali metadati (categoria, data, tags, ecc) dovrebbe essere collocati dopo.
Questo perché nelle sequenze complesse di card, la sequenza si potrebbe perdere durante la lettura e l'utente potrebbe non distinguere più a cosa appartiene l'elemento che definiamo "categoria", che in realtà è un testo senza alcun valore semantico. Anche perché la suddivisione dei contenuti in "card" è solo visivo, semanticamente quello che conta è la sequenza delle informazioni; in questo contesto il titolo è l'unico elemento semantico che fa da spartiacque tra un blocco di contenuti e l'altro.

## Possibili soluzioni
Spostare i metadati dopo il titolo. 
Evidentemente questo richiede un re-design della card.
In alternativa, come soluzione temporanea minimale, sarebbe necessario inserire un alert lato accessibilità.

**Comment by Fupete** [comment]
Ciao @cfabry, ti segnalo che c'è già una issue dedicata a questa attività da un po' di tempo in backlog https://github.com/italia/bootstrap-italia/issues/1071 ci trovi anche la issue sulla repo design ui kit. Concordo che nel frattempo un alert potrebbe aiutare, ti va di proporre un contenuto? Usiamo l'altra issue per discuterne per favore per non disperdere le energie. Va bene in italiano anche.
