### ISSUE TITLE
Installazione del tema

### ISSUE THREAD

**Issue by flaviomariarussofmrgroup** [italia/bootstrap-italia#1124]
Salve a tutti, sto cercando di installare il tema per la prima volta su drupal seguendo la guida presente su https://git.drupalcode.org/project/bootstrap_italia/-/tree/2.x - ho tre problemi:

1) non riesco a far funzionare drush, in quanto mi dice che non lo riconosce come comando anche dopo averlo installato all'interno del server;

2) quando cambio la variabile hidden su false drupal mi dice che c'è un errore inatteso sul sito, pertanto sono costretto a riprisitnare la variabile su hidden;

3) non riesco a far funzionare npm, perché prima mi dice di installarlo, allora eseguo sudo apt install npm, poi una volta installato, se inserisco il comando npm run watch:dev mi inizia a dare una serie di errori che anche mettendomi di buona volontà non riesco a risolvere.

Sto lavorando in Ubuntu 20.04 con php 7.2 e drupal 9.3.3.

Spero che qualcuno mi possa aiutare.

Ringrazio tutti in anticipo.

Flavio

**Comment by arturu** [comment]
Questa issue si può chiudere
