### ISSUE TITLE
Upload Drag & Drop il metodo `reset()` non funziona

### ISSUE THREAD

**Issue by lungarella-raffaele** [italia/bootstrap-italia#1127]
## Versione di Bootstrap Italia

2.8.5

## Comportamento atteso

La mia applicazione necessita un controllo sulla dimensione del file prima del caricamento, se eccede una certa dimensione il file non deve essere caricato.
Il comportamento con caricamento da dispositivo (senza drag and drop) funziona senza problemi.
Il problema è il drag and drop. Nel momento in cui carico un file troppo grande, il caricamento viene correttamente impedito, ma il componente viene comunque inizializzato. 

## Comportamento attuale

Quello che succede:

<img width="560" alt="Screenshot 2024-06-11 at 18 35 42" src="https://github.com/italia/bootstrap-italia/assets/92225745/896fab52-d324-499c-ac5a-cbd719c71f63">

Quello che vorrei:

<img width="560" alt="Screenshot 2024-06-11 at 18 36 55" src="https://github.com/italia/bootstrap-italia/assets/92225745/e6731db0-9363-435f-b516-bf1eeb8bbae6">

Ho provato ad utilizzare il metodo reset() per eliminare la classe 'loading' che viene aggiunta con scarsi risultati.

## Code snippet
```js	
const handleFileDrop = (event: any) => {
	event.preventDefault();
	if (event.dataTransfer && event.dataTransfer.files) {
		if (event.dataTransfer.files[0].size > Config.MAX_FILE_SIZE_IN_BYTES) {
			fileDragDrop.reset();
			return;
		}
		if (fileInput) {
			fileInput.files = event.dataTransfer.files;
		}
		runDonutAnimation();
	}
};

const handleFileChange = (event: any) => {
	event.preventDefault();
	runDonutAnimation();
};
```
Nella funzione handleFileDrop il metodo `fileDragDrop.reset()` non ha alcun effetto.
## Contesto

Applicazione SvelteKit 4.2.7

**Comment by Virtute90** [comment]
In che modo definisci fileDragDrop?

**Comment by lungarella-raffaele** [comment]
```js	
let fileDragDrop: any;
onMount(async () => {
	window.bootstrap = await import('bootstrap-italia/dist/bootstrap-italia.esm');
	fileDragDrop = bootstrap.UploadDragDrop.getOrCreateInstance(
		document.getElementById('upload-file-form')
	);
});
```
I metodi `progress()` e `success()` funzionano senza problemi

**Comment by Virtute90** [comment]
> ```js
> let fileDragDrop: any;
> onMount(async () => {
> 	window.bootstrap = await import('bootstrap-italia/dist/bootstrap-italia.esm');
> 	fileDragDrop = bootstrap.UploadDragDrop.getOrCreateInstance(
> 		document.getElementById('upload-file-form')
> 	);
> });
> ```
> 
> I metodi `progress()` e `success()` funzionano senza problemi

Non ho capito perchè prima imposti bootstrap su window e dopo lo chiami senza

Dovrebbe essere così:

```jsx
let fileDragDrop: any;
onMount(async () => {
	window.bootstrap = await import('bootstrap-italia/dist/bootstrap-italia.esm');
	fileDragDrop = window.bootstrap.UploadDragDrop.getOrCreateInstance(
		document.getElementById('upload-file-form')
	);
});
```

**Comment by lungarella-raffaele** [comment]
Hai ragione, cambiando il codice purtroppo il comportamento rimane uguale

**Comment by Virtute90** [comment]
Guardando il codice:

https://github.com/italia/bootstrap-italia/blob/8db48b2889c9817e0ba74b277153f72bd5a089a5/src/js/plugins/upload-dragdrop.js#L63-L67

la funzione non fa altro che rimuovere due classi css e resettare il valore percentuale a 0.

Prova a verificare che almeno le classi vengano rimosse.

**Comment by lungarella-raffaele** [comment]
Sì mi ero informato sull'implementazione. Il problema è che queste classi non vengono rimosse, anche senza il metodo reset(), quindi usando una mia implementazione, la classe 'loading' persiste
