### ISSUE TITLE
Floating labels non funzionanti (Svelte 5)

### ISSUE THREAD

**Issue by lungarella-raffaele** [italia/bootstrap-italia#1134]
## Versione di Bootstrap Italia 
2.8.8

## Comportamento atteso

Vorrei utilizzare la floating label come da documentazione nella mia applicazione Svelte 5.

## Comportamento attuale
il comportamento però non è consistente.
Al refresh tutto funziona correttamente, nel momento in cui l'utente naviga nell'applicazione e in seguito ritorna nella pagina del componente questi smette di funzionare. (Data la natura saltuaria del bug credo che il componente smetta di funzionare anche in altre occasioni che non sono riuscito a riprodurre facilmente).

<img width="799" alt="Screenshot 2024-06-18 at 11 56 45" src="https://github.com/italia/bootstrap-italia/assets/92225745/08bb5310-d1a8-41fc-b85c-2820e728d332">

## Contesto

Ho creato una repository con la riproduzione del bug: https://github.com/lungarella-raffaele/bootstrap-italia-svelte installando bootstrap-italia con `npm i bootstrap-italia --save`

**Comment by arturu** [comment]
Se l'input ha un placeholder o del un valore di preset la label ha la classe 'active' già renderizzata al caricamento della pagina?

**Comment by lungarella-raffaele** [comment]
Ci sono due comportamenti diversi. 
## 1. Ricarico la pagina
La label funziona correttamente, quando clicco sull'input la classe 'active' viene aggiunta alla label è il comportamento funziona senza problemi.
## 2. Arrivo in una pagina tramite navigazione
La label non aggiunge più la label 'active' all'elemento quando il focus è sull'input e il risultato è l'immagine inserita nella issue. 

La repository inserita è fatta ad-hoc per vedere questo comportamento nella maniera più semplice possibile.

**Comment by arturu** [comment]
Nello screen che hai pubblicato, vedo un placeholder. In questo caso il codice html del tag `label` viene renderizzato con la classe `active`? Viene inviato dal server al browser già renderizzato in questa maniera `<label class="active" ...`?

**Comment by lungarella-raffaele** [comment]
Cosa intendi per "già renderizzato"? Credo di aver risposto nella mia risposta precedente perdona il gioco di parole. La classe "active" viene correttamente aggiunta solo nel momento in cui faccio il refresh della pagina in cui è presente il componente. Negli altri casi la classe non viene aggiunta. Nella fase iniziale (senza il focus dell'utente) la classe active non è presente nella label (ed è il comportamento che voglio), solo nel focus dell'input la classe "active" dovrebbe essere aggiunta alla label (cosa che funziona solo nel caso del refresh). Non so se ho capito male la domanda, comunque credo sia più facile per te risponderti da solo clonando la repository, ripeto, è fatta su misura per vedere questo comportamento.

**Comment by arturu** [comment]
Ah, scusa, pensavo ci fosse un placeholder (qualche annetto fa mi sono ammattito proprio su questo), ma vedendo la console nel video che hai postato non c'è nessun placeholder.

È un comportamento strano però.

L'unica cosa che salta all'occhio è che l'input non è annidato dentro un tag `form` e form.js fa questo https://github.com/italia/bootstrap-italia/blob/c7393ea9adaa946787b4e2ef97f87e6f07a8d77e/src/js/plugins/form.js#L119-L124 , vedi se hai errori in console.

**Comment by lungarella-raffaele** [comment]
Ho corretto inserendo il tutto all'interno di un form. Purtroppo non ha risolto il problema, credo sia un problema intrinseco di svelte. Grazie mille dell'aiuto. Non so se vuoi lasciare la issue aperta. Sicuramente cercherò di studiare una soluzione e di aggiornare la issue in futuro. Lascerò la repository aperta per chiunque voglia provare a capire qual'è il problema.

**Comment by arturu** [comment]
Di niente, ci si aiuta come si può :)
Emm, non gestisco io le issue, sicuramente qualcun altro che legge saprà darti una mano :)
