### ISSUE TITLE
Italia-icon-font.min.css not found

### ISSUE THREAD

**Issue by fabiofumarola** [italia/bootstrap-italia#115]
Reading the documentation I found a reference a file named [italia-icon-font.min.css](https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/#icon-font) which is not available in the package downloaded

**Comment by francescozaia** [comment]
Thanks @fabiofumarola, you can safely use the packaged `/css/italia-icon-font.css` as we're just not minifying it. I'll keep this open in order to not forget to update the docs accordingly.

**Comment by francescozaia** [comment]
Fixed docs in v0.6.0.
