### ISSUE TITLE
Componente `Upload`: parte in lingua nella documentazione

### ISSUE THREAD

**Issue by Mattia541993** [italia/bootstrap-italia#1186]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Nella sezione [Upload Drag&drop](https://italia.github.io/bootstrap-italia/docs/form/upload/#upload-dragdrop) presente nella documentazione è presente un esempio nel quale ad un certo punto nel codice viene mostrato il testo "Process completed". Essendo tutto l'esempio in lingua italiana, per questo particolare contenuto è necessario definire l'attributo `lang="en"` sul tag `<p>` che contiene il testo:
```html
<p class="mt-5" lang="en"><strong>Process completed</strong></p>
```
In alternativa si potrebbe tradurre anche questo messaggio in italiano.

### Perché

Utile alla documentazione

**Comment by Fupete** [comment]
Ciao @Mattia541993, osservazione corretta. 

Va cambiato il testo e messo in italiano "**Processo completato**".

**Comment by astagi** [comment]
@Mattia541993 grazie mille! ho appena inserito il fix nel main, alla prossima release sarà online. Stiamo riscrivendo parti della codebase e della documentazione.
