### ISSUE TITLE
Componente `TimePicker`: contrasto durante l'inserimento di ore e minuti

### ISSUE THREAD

**Issue by Mattia541993** [italia/bootstrap-italia#1193]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

## Con il browser Chrome
In fase di inserimento di ore e minuti utilizzando la tastiera per inserire i valori numerici per ore e minuti (quindi **non** attraverso il menu a tendina dal quale è possibile selezionare con le frecce il valore di ore e minuti), quando il focus è su ore o minuti, il contrasto di colore tra lo sfondo del campo e il testo inserito non raggiunge la soglia di contrasto minimo.
Questo problema sembra essere dovuto al modo in cui il browser Chrome supporta l'elemento nativo HTML `<input type="time">`
![Screenshot 2024-08-29 alle 12 23 27](https://github.com/user-attachments/assets/44c65ddf-04fc-49b4-bfe8-4effa93e6c29)

![Screenshot 2024-08-29 alle 12 28 10](https://github.com/user-attachments/assets/568004fb-e1a6-4f32-ae07-f9696a2821e4)

Per tutti gli altri browser indicati nella sezione "Contesto" il contrasto è sufficiente

### Perché

Per l'accessibilità delle persone con ipovisione e in riferimento alla norma [WCAG 1.4.3](https://www.w3.org/Translations/WCAG22-it/#contrast-minimum) relativa al contrasto tra testo e sfondo

## Browser utilizzati
- Chrome
- Firefox
- Safari
- Safari per iOS
- Edge per Windows

**Comment by Mattia541993** [comment]
Ciao, che strano.. Ho provato anche oggi e ora funziona anche con Chrome sia su Mac che su Windows, seppur con sfondi diversi a seconda che sia su mac o su Windows. L'unico problema di contrasto ce l'ho ad oggi solo sul browser Arc. Mi sembra di capire che c'è molta variabilità in questo senso che dipende soprattutto dal browser utilizzato e dal sistema operativo, ma per la maggior parte dei browser il componente vada bene

**Comment by Fupete** [comment]
Sì, dovrebbe essere il comportamento del componente input time standard HTML. 
Andrebbe aperta una segnalazione bug su Arc 🤷 

Senti, chiuderei la la presente non essendo un bug del framework Bootstrap Italia. Che ne dici?
