### ISSUE TITLE
Componente `TimePicker`: link errato sulla tabella GitHub

### ISSUE THREAD

**Issue by Mattia541993** [italia/bootstrap-italia#1194]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Nella tabella [.italia census Design System Italia](https://github.com/orgs/italia/projects/32/views/1) il link al componente nella versione Angular rimanda al componente `FormInput` ([https://italia.github.io/design-angular-kit/design-angular-kit#/componenti/form-input](https://italia.github.io/design-angular-kit/design-angular-kit#/componenti/form-input))

### Perché

Per correttezza della documentazione

**Comment by Fupete** [comment]
Ciao @Mattia541993, in realtà è corretto. 

Per il momento infatti, nel kit Angular, il componente timepicker è nella documentazione "solo" una variante del componente `FormInput`, non ha una scheda dedicata. Trovi la proprietà per visualizzarlo sulla destra del pannello.  
![Proprietà timepicker](https://github.com/user-attachments/assets/f35d2857-5dc7-456c-975c-7c0e5a6f7820)
ps. anche in React kit è sotto il componente `Input`. 

Un giorno spero non troppo lontanto affronteremo anche queste ultime discrepanze nel naming componenti e schede. 

Se qualcosa non ti torna per favore potresti riaprirla direttamente nella repository del kit Angular? https://github.com/italia/design-angular-kit/issues

**Comment by Mattia541993** [comment]
Ciao! Grazie della risposta! Scusami, svista mia!! 😅
