### ISSUE TITLE
Componente `Timeline`: navigabilità

### ISSUE THREAD

**Issue by Mattia541993** [italia/bootstrap-italia#1195]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Per facilitare la navigazione tra i mesi nell'[esempio in documentazione](https://italia.github.io/bootstrap-italia/docs/componenti/timeline/) si potrebbe marcare come intestazione il testo che indica il mese. Si potrebbe quindi sostituire lo `<span>` che contiene il nome del mese con un `h4` perchè è presente un `h5` ad indicare il titolo di una card (un elemento della timeline)

### Perché

Sebbene sia soddisfatto il criterio [WCAG 2.4.6](https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels.html) "Intestazioni ed etichette", non è soddisfatto il criterio [WCAG 1.3.1](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships) "Informazioni e correlazioni"

### Contesto
Aggiornato da @Fupete in data 3/9/2024:

Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

### Altro
Aggiornato da @Fupete in data 3/9/2024:

Sarà da aggiornare anche in React kit alla risoluzione.

**Comment by Fupete** [comment]
Ciao @Mattia541993, sono d'accordo con te questa modifica. 

Nella correzione ne farei anche un'altra, spostando CATEGORIA e DATA sotto il titolo della singola card. Per migliorare ancora di più la gerarchia dei contenuti raccolti dagli heading. È una modifica che dovremo fare anche alle CARD in generale appena possibile. 

Visto che ci siamo, per questi meta tag categoria e data, sarebbe da valutare anche uno `<span>` con classe `visually-hidden` da mettere subito prima ad ognuno con scritto: "Categoria dell'evento: " e "Data evento: ", in modo da renderne chiaro il significato durante la lettura da lettore di schermo e fornire un esempio completo a chi ne può usare il markup. 

Cosa ne pensi?

**Comment by Mattia541993** [comment]
Ciao, per quanto riguarda le intestazioni su categoria e data sono d'accordo così come lo `<span class="visually-hidden">` da aggiungere in documentazione per specificare meglio cosa sono la categoria dell'evento e la data.
Per quanto riguarda la semantica dei colori ci ho riflettuto un po' e secondo me la semantica dei colori nella timeline è più un espediente visivo per aver un colpo d'occhio su un punto di confine tra passato e futuro, ma ha senso che un solo elemento sia contrassegnato come presente. Non vedo nella timeline un caso in cui più mesi possano essere considerati come "presente". Inoltre non trasmette informazioni in più, ma rafforza quelle che già ci sono (se oggi siamo a settembre e la granularità della timeline è al mese, so che mi sto riferendo ad "adesso"). Per questo sarei per non considerare di veicolare quest'informazione a livello di accessibilità. 

Per quanto riguarda invece l'icona `<svg>` sono d'accordo di assegnarle un `role="img"`e un tag `<title>` all'interno.

**Comment by Fupete** [comment]
@Mattia541993 ho aperto una PR di risoluzione. È ancora in draft. Dai un'occhiata e fammi sapere cosa ne pensi e se ti torna tutto. 

Unico dubbio che ho ancora: 
- probabilmente l'ordine di icona mese e titolo mese dovrebbe essere invertito nel markup. Prima l'heading poi l'icona. In modo che venga sempre letta successivamente al titolo, ad es. "<heading> Giugno <immagine> Successo". Il tema è che per invertire questo markup e poter invertire correttamente gli elementi anche visivamente la modifica al scss diventerebbe parecchio disruptive, tanto da dover valutare se farla con nuove classi "to be" per retrocompatibilità (cc @astagi che ne pensi?)

@astagi la documentazione della breaking (è una breaking? ad valutare) in caso poi ci pensi tu.

**Comment by Fupete** [comment]
Qui la preview corrente della PR: https://bootstrap-italia-o80xpc6nt-dip-trasformazione-digitale.vercel.app/docs/componenti/timeline/

Da notare che ho sostituito anche le icone dei mesi con icone più puntuali, in modo da poterne dimostrare l'utilità e la necessità di ruolo e titolo.

**Comment by Fupete** [comment]
Mi correggo: ho aggiornato l'approccio. Ora il tag `h` racchiude sia icona che testo del mese. Così sembra funzionare correttamente. Da domani vi metto reviewer.

**Comment by cfabry** [comment]
Io andrei vero una semplificazione @Fupete :

- Trasformare la data in Hx. Come al solito possiamo indicare un generico H, ma il livello è determinato dal titolo primario assegnato alla timeline; se pensiamo che H3 possa essere il caso d'uso primario ok, però mettiamo sempre nella documentazione che è solo un caso d'uso.
- Ok per spostare categoria e data sotto il titolo (è una richiesta già aperta per tutte le card).
- A mio avviso l'icona è sempre decorativa, non rappresenta altro che il cambio di mese, che avrebbe già il suo valore semantico H.
- Non aggiungerei altre informazioni sul presente/futuro, implicitamente contenuto nel mese. 
- Stessa cosa per `<span class="visually-hidden">Segnaposto`, sinceramente non ne vedo l'esigenza.

**Comment by Fupete** [comment]
@cfabry l'icona però potrebbe avere significato per la mia esperienza (segnaposto, successo, milestone, etc.) Per questo ho messo nell'esempio come eventualmente veicolarlo (segnaposto) sia con title o con span nascosto. Dici che è overkill?

**Comment by cfabry** [comment]
A mio avviso è ridondante se esprime soltanto il passaggio da un mese all'altro, quello è garantito dal mese messo come H.
Se invece vuoi dire che può significare "milestone" o altro, allora ha un senso. Lo specificherei nella documentazione.

**Comment by Fupete** [comment]
Ho aggiornato la documentazione. Per me ci siamo. Lascio alla review di @astagi e @Mattia541993 .

**Comment by Mattia541993** [comment]
Cao! Sono d'accordo con tutta la conversazione finora. Allo stato attuale della documentazione nella PR però la riga che spiega `.pin-icon` è un po' troppo generica secondo me, nel senso che quello che secondo me dovrebbe arrivare è che dentro `.pin-icon` ora c'è un svg, ma potrebbe esserci anche qualcos'altro (un'`img`) e che se è significativo deve avere del testo alternativo, altrimenti dev'essere contrassegnato come decorativo. Aggiungerei questa precisazione alla frase "L’elemento `.pin-icon` ha attributi `role="img"` e tag `title` che lo descrive" qui https://bootstrap-italia-bfo4g9880-dip-trasformazione-digitale.vercel.app/docs/componenti/timeline/

**Comment by Fupete** [comment]
Concordo. Guarda l'ultima versione che avevo preparato rivedendo proprio la documentazione: https://bootstrap-italia-5w8edbsrp-dip-trasformazione-digitale.vercel.app/docs/componenti/timeline/

**Comment by Mattia541993** [comment]
Vista, perfetto scusami! Avevo guardato il link sbagliato! Per me così va bene! Grazie @Fupete
