### ISSUE TITLE
Componente `Thumbnav`: link errato sulla tabella GitHub

### ISSUE THREAD

**Issue by Mattia541993** [italia/bootstrap-italia#1196]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Nella tabella [.italia census Design System Italia](https://github.com/orgs/italia/projects/32/views/1) il link al componente nella versione React rimanda ad una pagina non disponibile (https://italia.github.io/design-react-kit/?path=/docs/documentazione-componenti-thumbnav--documentazione)

### Perché

Per correttezza della documentazione

**Comment by Fupete** [comment]
Grazie @Mattia541993! 

✅ Appena corretto.
