### ISSUE TITLE
Componente `Tab`: Indicazione dello stato selezionato in React

### ISSUE THREAD

**Issue by Mattia541993** [italia/bootstrap-italia#1197]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

I lettori di schermo non leggono lo stato selezionato nei tab a bottoni che ereditano la proprietà `pills`. 

### Perché

In riferimento alle [WCAG 4.1.2](https://www.w3.org/Translations/WCAG22-it/#name-role-value) "Nome, Ruolo, Valore"

**Comment by Mattia541993** [comment]
Ciao, certo! Ho aperto tutte le issue per ora sempre su Bootstrap Italia. Anche per le altre che sarebbero dovute essere pubblicate sul repository corretto di React/Angular sposto la issue sul repository corretto. Grazie mille della segnalazione 😃

**Comment by Fupete** [comment]
Grazie, chiudo la presente ✋
