### ISSUE TITLE
Componente `Sections`: `aria-describedby` vs `aria-labelledby`

### ISSUE THREAD

**Issue by Mattia541993** [italia/bootstrap-italia#1199]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Nella documentazione delle ["Section"](https://italia.github.io/bootstrap-italia/docs/componenti/sections/) viene utilizzato l'attributo `aria-describedby` per creare una correlazione tra la `<section>` e l'intestazione `<h2>`. Da linee guida ARIA ([Headings](https://www.w3.org/WAI/tutorials/page-structure/headings/) e [Labeling Regions](https://www.w3.org/WAI/tutorials/page-structure/labels/#using-aria-labelledby)) sarebbe più corretto utilizzare l'attributo `aria-labelledby`.

### Perché

Per la semantica della struttura della pagina

### Contesto
Aggiornato da @Fupete 2/9/2024: 

Verifiche di accessibilità sui componenti.

⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

### Altro
Aggiornato da @Fupete 3/9/2024: 

Da "sistemare" anche nel React kit al completamento.

**Comment by Fupete** [comment]
Ciao @Mattia541993, grazie per questa e le altre segnalazioni di oggi. 

Appena possibile faccio un giro a prioritizzarle e, nel tempo, le verrai pian piano assergnare per eventuali soluzioni o commenti. 

Posso chiederti se dove la soluzione è evidente, come in questo caso, saresti anche in grado di aprire PR di soluzione? Per curiosità, e perché sarebbe molto utile a velocizzare. 

Un caro saluto, Daniele T. 

cc @astagi

**Comment by Fupete** [comment]
Per informazione: nella [board di censimento status ](https://github.com/orgs/italia/projects/32/views/1) ho aggiornato lo status del campo "Amichevole con i lettori di schermo" in "IN REVIEW", e aggiunto questa issue al tracciamento.

**Comment by Fupete** [comment]
Per informazione: nella [board di censimento status ](https://github.com/orgs/italia/projects/32/views/1) ho aggiornato lo status del campo "Amichevole con i lettori di schermo" in "IN REVIEW", e aggiunto questa issue al tracciamento.

**Comment by Mattia541993** [comment]
Ciao! Grazie a te per la puntualità della risposta. Certamente posso aprire delle PR. Ci sono delle linee guida tecniche su come farle, tipo convenzioni di naming o branch dal quale aprirle?

Grazie mille!

**Comment by Fupete** [comment]
Bene! Lascio ad @astagi le convenzioni 😄

**Comment by Mattia541993** [comment]
Ciao, grazie a te per la risposta. Mi scuso per aver fatto la domanda sulle convenzioni quando in realtà è tutto ben documentato.

**Comment by Fupete** [comment]
@astagi la soluzione qui implementata va riportata anche in React kit. Apri tu una issue?
