### ISSUE TITLE
Aggiunta icona PagoPA

### ISSUE THREAD

**Issue by lscorcia** [italia/bootstrap-italia#1205]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Salve, sarebbe utile aggiungere il logo PagoPA all'iconset di default, così da rendere più semplice realizzare i bottoni di attivazione di pagamento dei contributi.

### Perché

Ci sono loghi per ogni tipo di piattaforma social, ma PagoPA manca. Avere un riferimento built-in aiuterebbe anche a assicurare il rispetto delle linee guida sul branding previste da PagoPA (https://www.pagopa.gov.it/assets/download/pagoPA-brand-guidelines.pdf).

**Comment by Fupete** [comment]
Ciao @lscorcia, grazie per la segnalazione. 

Non sarebbe propriamente un'icona... ci ragioneremo nella prossima fase di ricerca, in particolar modo magari rispetto all'utilità di simboli grafici utili all'implementazione di diversi servizi (SPID, PagoPA, CIE, ...). 

Daniele T.

**Comment by astagi** [comment]
@Fupete @lscorcia chiusa in favore di questa https://github.com/italia/bootstrap-italia/issues/1297

**Comment by astagi** [comment]
@Fupete @lscorcia forse per PagoPA sarebbe meglio utilizzare gli asset grafici ufficiali che indicano nel sito e che magari sono soggetti a cambiamenti: https://developer.pagopa.it/pago-pa/guides/linee-guida-brand-pagopa/risorse-utili/scarica-gli-asset-grafici#il-logo-pagopa

Direi di non includere all'interno di Bootstrap Italia né il logo né tantomeno badge ufficiali.
