### ISSUE TITLE
La classe is-invalid renderizza male sugli input type="date"

### ISSUE THREAD

**Issue by diegoandornoorangepix** [italia/bootstrap-italia#1207]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Inserendo la classe `is-invalid` in un input di tipo data con classe datepicker la crocetta viene ripetuta indefinitamente coprendo l'intero input

I test sono stati fatti su Mac (chrome e firefox) e su windows (firefox ed edge) aggiornati all'ultima versione
Sui progetti proprietari e, per testare, direttamente nella documentazione di bootstrap-italia (come da foto allegata)

<img width="1972" alt="Screenshot 2024-09-04 alle 15 48 22" src="https://github.com/user-attachments/assets/b356cc7d-b4ed-41d6-b48f-9d9515ce8f65">

Per replicare l'errore è sufficiente:
1) andare nella pagina della documentazione https://italia.github.io/bootstrap-italia/docs/form/input-calendario/
2) Fare tasto destro sul campo data e andare in ispeziona elemento
3) aggiungere la classe `is-invalid` alle classi dell'input attraverso il pannello di controllo del browser

### Perché

Ritengo sia un errore perchè `is-invalid` è una classe nativa di bootstrap 5 (e infatti questo stesso test fatto sulla doc di bootstrap 5 va a buon fine) e su bootstrap italia sembra allineato per tutti gli altri input base ma non per le date

**Comment by zetareticoli** [comment]
Il bug nasce dal fatto che la `input` in questione non ha la classe `.form-control`, aggiungendola infatti lo stato `is-invalid` si comporta correttamente.

Nel CSS di BSI infatti c'è una dipendenza tra le due classi. 

@Fupete forse è un errore nella documentazione, perché tutti gli altri casi di `input` prevedono sempre la classe `.form-control`

**Comment by Fupete** [comment]
Sentiamo @astagi ⬆️ poi fai/fate pure una PR di fix.

**Comment by zetareticoli** [comment]
@Fupete aperta PR
