### ISSUE TITLE
JustValidate - costruttore non accetta dizionario per messaggi di validazione generici localizzati

### ISSUE THREAD

**Issue by lbertonicsc** [italia/bootstrap-italia#1212]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

v2.9.0

### Cosa

Buongiorno,

vorrei portare alla vostra attenzione la seguente richiesta.

La [documentazione di JustValidate](https://just-validate.dev/docs/instance/) riporta la possibilità di passare al costruttore un terzo parametro che consiste in un dizionario per messaggi di validazione generici localizzati.

Se possibile sarebbe utile avere questo parametro anche qui:
https://github.com/italia/bootstrap-italia/blob/main/src/js/plugins/form-validate.js#L16-L19

Grazie

### Perché

Ritengo rilevante la segnalazione perché può tornare utile poter specificare un dizionario di validazione generici.

**Comment by astagi** [comment]
Fixed

**Comment by lbertonicsc** [comment]
> Fixed

Buongiorno @astagi,

hai contrassegnato l'issue come fixed ma non vedo modifiche al codice sul branch main.
