### ISSUE TITLE
Aggiungere link alla dichiarazione di accessibilità negli skiplink

### ISSUE THREAD

**Issue by rscano** [italia/bootstrap-italia#1217]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.9.0

### Cosa

Il salto di blocchi - [criterio di successo 2.4.1 delle WCAG 2](https://www.w3.org/Translations/WCAG21-it/#bypass-blocks), prevede che sia disponibile un [meccanismo](https://www.w3.org/Translations/WCAG21-it/#dfn-mechanism) per saltare i blocchi di contenuto che si ripetono su più pagine Web. Lo scopo di questo criterio di successo è consentire alle persone che navigano in sequenza nei contenuti di accedere più direttamente al contenuto principale della pagina Web. Sarebbe interessante inserire tra i link anche un link diretto alla dichiarazione di accessibilità.

### Perché

Il link alla "Dichiarazione di accessibilità" viene posizionato, come da indicazioni europee (e conseguentemente di AgID) nel footer. Ciò comporta che l'utente per conoscere il problemi di accessibilità e per comprendere come attivare il meccanismo di feedback, deve scorrere tutti i contenuti. Sarebbe importante quindi garantire che l'utente che arriva al sito con navigazione tramite tastiera (non solo quindi utenti con lettore di schermo), possa raggiungere tale informazione già dall'accesso al sito come primo link di salto di blocchi (es: link: salta alla dichiarazione  di accessibilità, link: salta al contenuto, link salta alla ricerca).

### Altro
Similmente tale possibilità dovrebbe essere data per l'attivazione della scelta del cambio di lingua della pagina (ma se è altra issue, ignoratela :) )

**Comment by Fupete** [comment]
@rscano mi sembra una buona idea! 

Ne metto in priorità alta la verifica, e la aggiungo alla board di status come nota relativa al componente `Skiplinks`.

**Comment by Fupete** [comment]
@rscano @astagi ho aggiunto una PR di fix, per ora draft. Date un'occhiata se vi torna tutto. Consigli per migliorarla sono benvenuti.

**Comment by Fupete** [comment]
Qui l'anteprima corrente della nuova documentazione: https://bootstrap-italia-git-feat-sk-1843be-dip-trasformazione-digitale.vercel.app/docs/menu-di-navigazione/skiplinks/ 
1. Ho diviso in due varianti, una base più semplice e una avanzata come elenco più complessa.
2. In questa ultima più complessa a elenco ho anche 
   a. evoluto il markup per includere il tutto in un elemento `<nav>` e in un elenco `<ul>`, con la corretta `aria-label` sul primo;
   b. inserito e documentato i due link in più al modulo di feedback sulla pagina e alla dichiarazione di accessibilità nel footer. 

Cosa ne pensate? 

Domanda per voi in più: noi indichiamo che deve essere il primo elemento di pagina. 
Sarebbe utile specificare se metterlo dentro, o prima, l'elemento `<header>` laddove presente? 
Per adesso noi, vedi Designers Italia, lo mettiamo sempre prima.

**Comment by Fupete** [comment]
@astagi l'ho rivisto stamane con @rscano e @cfabry e fatto gli ultimi aggiustamenti. 

Per tutti: ho approfittato per sistemare anche il markup del componente footer nella stessa PR, eliminando gli inutili `title` sui link `<a>` e aggiungendo il link alla Dichiarazione di accessibilità.

**Comment by Fupete** [comment]
Intanto ho preparato anche la modifica di integrazione per lo stesso sito Designers Italia qui: https://github.com/italia/designers.italia.it/pull/1440 così possiamo testare il nuovo approccio in uso.
