### ISSUE TITLE
Focus visibile nel campo di ricerca

### ISSUE THREAD

**Issue by cfabry** [italia/bootstrap-italia#1292]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

2.12.1

### Cosa

Il focus nel campo di ricerca non è visibile.
<img width="1656" alt="Screenshot 2024-11-28 alle 16 28 58" src="https://github.com/user-attachments/assets/aa1d782e-f67c-4a60-90d2-37729300c3fb">

### Perché

È necessario uniformare anche BI

**Comment by astagi** [comment]
Grazie mille @cfabry great catch 🙌 il fix è sul ramo principale, sto aggiornando la documentazione online!
