### ISSUE TITLE
Select non inizializzata

### ISSUE THREAD

**Issue by skaffolder** [italia/bootstrap-italia#150]
## Comportamento atteso
Visualizzare la select (combo box)

## Comportamento attuale
Premendo F5 sulla pagina questa viene inizializzata correttamente, mentre arrivando da un link Angular (o singol page application in generale) questa non prende lo stile desiderato e non è utilizzabile

## Possibili soluzioni
Eseguire la funzione di init al cambio dell'hash URL

## Contesto
Applicazione Angular 6 standard, partendo con angular-cli

**Comment by enricouniurb** [comment]
### Visualizzazione select
![image](https://user-images.githubusercontent.com/38656571/41524642-7fbbacdc-72de-11e8-8f49-1a1e31cf4e82.png)

### Template componente
```
<div class="form-group col-md-2 mb-3">      
      <label for="gender" class="control-label">Sesso</label>      
      <select class="custom-select" formControlName="gender" id="gender">   
          <option value="" disabled selected>Seleziona</option>     
          <option *ngFor="let opt of options" [ngValue]="opt.key"> {{opt.value}} </option>
      </select>    
    </div>
```
### Comportamento attuale 
Utilizzando angular reactive form quando imposto il valore della selezione da codice (già visualizza) la select non si aggiorna correttamente. 
Non visualizza l'elemento selezionato.
Non mette la spunta sull'elemento selezionato.

### Codice componente
```
 options: object[] = [
    {key:'m', value:'Maschio'},    
    {key:'f', value:'Femmmina'}    
  ]
ngOnInit() {
...
   this.submissionForm.controls['gender'].setValue('m')
}

```

**Comment by snack-eater** [comment]
@skaffolder La select non viene visualizzata correttamente all'interno di Angular, perché Angular e Bootstrap-Italia gestiscono le componenti con un diverso ciclo di vita.
Bootstrap-Italia trasforma la semplice select in una custom-select quando viene scatenato l'evento "[load.bs.custom-select.data-api](https://github.com/italia/bootstrap-italia/blob/0cb6d5c30f13b9632d427937f2d6b2fc6603ba85/src/js/plugins/custom-select.js#L461)".

È importante quindi che, quando l'evento viene scatenato (all'avvio della pagina), l'elemento select sia già presente nel DOM, cosa non vera nel caso di Angular, che la inietta dinamicamente, dopo il caricamento della pagina.

Per rimediare a questo problema in Angular, propongo due possibili soluzioni:
1. Lancio dell'evento "**load.bs.custom-select.data-api**", ogni volta che viene iniettata la select nel DOM
2. Eseguire nella funzione "**ngAfterViewInit**" il seguente codice che inizializza la custom-select:
```typescript
const selects = $($.makeArray($('.custom-select')));
const win = window as any;

for (let i = selects.length; i--;) {
     const $select = $(selects[i]);
     win.Select._jQueryInterface.call($select, $select.data());
}
```


@enricouniurb Per impostare il valore predefinito della select è necessario l'attributo "**[formGroup]**" all'interno del div. Fatto questo, viene impostato e visualizzato il default, anche se non appare la spunta accanto al suo valore.
```html
<div class="form-group col-md-2 mb-3" [formGroup]="submissionForm">
  <select class="custom-select" formControlName="gender" id="gender">
      <option value="" disabled selected>Seleziona</option>
      <option *ngFor="let opt of options" [ngValue]="opt.key"> {{opt.value}} </option>
  </select>
  <label for="gender" class="control-label">Sesso</label>
</div>
```
