### ISSUE TITLE
Mega menù: visualizzazione errata su mobile e finestre non schermo pieno

### ISSUE THREAD

**Issue by lfassio** [italia/bootstrap-italia#151]
## Comportamento atteso
deve mantenere lo sfondo opaco e assicurare la leggibilità dei testi

## Comportamento attuale
Lo sfondo del menù diventa trasparente, anche i sotto livelli dell'hamburger menù sono illeggibili

## Contesto
Finestra non full screen o mobile

![issue_megamenu](https://user-images.githubusercontent.com/8473567/41344776-3c5f8c36-6f02-11e8-99fa-d39db601eda6.png)

![issue_megamenu2](https://user-images.githubusercontent.com/8473567/41344856-69a0ad38-6f02-11e8-8c86-b61f5925dbb0.png)

**Comment by francescozaia** [comment]
Ciao @lfassio,
Come comunicato privatamente, la pagina è in lavorazione; terremo comunque come d'accordo aggiornata la issue con i prossimi sviluppi. Detto questo, non riusciamo a riprodurre il problema segnalato: potresti cortesemente dettagliare le specifiche del tuo sistema (sistema operativo e versione di Chrome)? Grazie di nuovo!

**Comment by lfassio** [comment]
Francesco,

perdona ma sono in vacanza in Francia e cerco di non leggere la mail :)

Sto usando per i test Chrome Versione 67.0.3396.87 (Build ufficiale) (a 64 bit) e il mio Android 7 sempre con Chrome

Non riesco più a riprodurre i problemi segnalati perché li hai corretti, ottimo!

L'unico dubbio che mi rimane è il cambio lingua che dalla pagina:

https://italia.github.io/bootstrap-italia/docs/esempi/comuni/

è stato rimosso, per noi è importante perché siamo una regione bilingue e quindi italiano e francese sono obbligatori sul sito web dell'amministrazione regionale.

Con l'occasione ti segnalo che nella pagina:

https://italia.github.io/bootstrap-italia/docs/esempi/ 

il link a:

https://italia.github.io/bootstrap-italia/docs/esempi/form/ 

è rotto.

Grazie per il tio aiuto.

Lucio Fassio

**Comment by lfassio** [comment]
Francesco,

è possibile ripristinare il cambio lingua nella pagina https://italia.github.io/bootstrap-italia/docs/esempi/comuni/ ?

Serve che apro un incident su Slack?

Se non sei in ferie tu naturalmente :)

Grazie.

Lucio Fassio

**Comment by francescozaia** [comment]
Ciao @lfassio,
Il cambio lingua è stato temporaneamente rimosso perché in fase di revisione in termini di design: ti posso anticipare che le più recenti indicazioni lo configurano come una "modale", di cui allego uno screenshot, la quale poi diventa il classico menu a tendina su schermi grandi.

<img width="376" alt="schermata 2018-07-02 alle 12 24 55" src="https://user-images.githubusercontent.com/481084/42159141-fcaad6f4-7df2-11e8-9ca7-7ec1147f80df.png">

Non so darti tempistiche certe per la sistemazione di questo particolare snippet di codice, che ricordo ancora una volta essere solo un esempio. Potete per ora semplicemente gestirlo come un Dropdown, di cui trovate il codice a [questa pagina](https://italia.github.io/bootstrap-italia/docs/componenti/dropdown/).

Ad ogni modo ti invito a scrivermi su Slack dove puoi trovare sia me che la persona che si sta occupando della revisione del design kit, oltre che delle linee guida stesse, e dove possiamo parlare più in dettaglio di tematiche di procurement e roadmap che al momento affliggono il progetto, e che non sono affrontabili qui su GitHub.

Grazie
