### ISSUE TITLE
Hamburger menu: dovrebbe apparire come nell'esempio Offcanvas

### ISSUE THREAD

**Issue by lfassio** [italia/bootstrap-italia#152]
## Comportamento atteso
L'hamburger menù dovrebbe apparire come nell'esempio Offcanvas anche nell'esempio Comune

## Comportamento attuale
Appare l'hamburger menù standard di Bootstrap

## Contesto
Mobile o finestra non full screen

![issue_hamburgermenu](https://user-images.githubusercontent.com/8473567/41345291-823d471a-6f03-11e8-9510-7c5da03626fa.png)

**Comment by lfassio** [comment]
Hamburger menù su Offcanvas:

![issue_hamburgermenu2](https://user-images.githubusercontent.com/8473567/41345374-b1f35184-6f03-11e8-955f-24156237fbd7.png)

**Comment by francescozaia** [comment]
Ora è allineato con quanto segnalato, nonostante il layout della pagina rimanga non consolidato.
