### ISSUE TITLE
Cambio lingua: si posiziona in modo errato su mobile

### ISSUE THREAD

**Issue by lfassio** [italia/bootstrap-italia#153]
## Comportamento atteso
posizionamento corretto a sinistra dello schermo e sfondo opaco

## Comportamento attuale
si posiziona in modo errato su mobile o su finestre non full screen; lo sfondo diventa trasparente

## Contesto
mobile o su finestre non full screen su desktop

![issue_changelanguage](https://user-images.githubusercontent.com/8473567/41345798-ec66e64a-6f04-11e8-827b-8fba82aa0e20.png)

**Comment by francescozaia** [comment]
Il cambio lingua è un componente non ancora realizzato, per ora è stato rimosso.
