### ISSUE TITLE
CODE_OF_CONDUCT.md in italiano

### ISSUE THREAD

**Issue by nsanitate** [italia/bootstrap-italia#155]
## Comportamento atteso

Come gli altri documenti nel repository, mi aspetto che anche il codice di condotta sia scritto in italiano.

## Comportamento attuale

Attualmente è scritto in inglese.

## Possibili soluzioni

Tradurlo.

**Comment by francescozaia** [comment]
Grazie @nsanitate, sarebbe sicuramente utile avere una versione tradotta del file, dato che la libreria è indirizzata prevalentemente a fornitori e PA italiani.

Non rinuncerei però ad una versione inglese. Potremmo quindi mettere in piedi una versione `.it` dei file "informativi", in aggiunta ad una versione base in inglese (in un formato tipo `CODE_OF_CONDUCT.it.md`).

**Comment by francescozaia** [comment]
Aggiornato e tradotto `CODE_OF_CONDUCT.md`, conservato il precedente in `CODE_OF_CONDUCT.EN.md`
