### ISSUE TITLE
Area Contenuti: Tabelle

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#159]
## Comportamento atteso
Revisione del componente [Tabella](https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/tabelle/) come da Design UI Kit.

## Blocker
UI Design

**Comment by enricobasso** [comment]
Ciao,
non ho capito di preciso quale sia il compito da svolgere per risolvere questa issue.

**Comment by francescozaia** [comment]
Ciao @enricobasso perdona la poca chiarezza della issue.
Questa issue è al momento bloccata perché vorremmo, prima di lavorare su di essa, avere lo stile delle tabelle definito in modo formale nello [UI Kit](https://github.com/italia/design-ui-kit), visibile su [InVision](https://projects.invisionapp.com/share/RJFGS2UC3HS#/screens). Tutte le issue con il tag `design needed` sono in questo stato; grazie per il messaggio, magari ne approfitto per informarmi se ci sono sviluppi in merito lato design.

**Comment by francescozaia** [comment]
@nikorobins al momento se non erro non ci sono nello UI kit direttive particolari sul design di tabelle. Al momento Bootstrap Italia [prevede un po' di opzioni](https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/tabelle/) a riguardo, ma vogliamo avere qualcosa di dedicato nel nostro design system? Grazie

**Comment by nikorobins** [comment]
Ciao, ho appena aggiornato lo UI Kit. Ci sono due tipi tabelle. Per il secondo tipo che prevede un diverso comportamento su mobile stiamo facendo dei test di usabilità per capire se può funzionare. Nel caso vi aggiorno se ci sono novità. Grazie :-)

**Comment by nikorobins** [comment]
scusato ho dimenticato i riferimenti 
[file sketch](https://github.com/italia/design-ui-kit/blob/874a63317b0987dc6c6b703e3ce186d8461de9b3/Components/italia-DataDisplay-tables.sketch)
[invision](https://projects.invisionapp.com/d/main#/console/13150017/387419619/preview)

**Comment by francescozaia** [comment]
Grazie @nikorobins! 🥇
