### ISSUE TITLE
Inline Password Form con testo di aiuto: l'icona si sovrappone al testo

### ISSUE THREAD

**Issue by NicolaFerracin** [italia/bootstrap-italia#202]
## Comportamento atteso
Nel secondo esempio [qui](https://italia.github.io/bootstrap-italia/docs/componenti/form/#testo-di-aiuto),  l'icona per mostrare/nascondere la password dovrebbe essere allineata alla destra del testo di aiuto. [Immagine](https://gyazo.com/daf1cb4b3689d61c28a2a1853ae2b1be)

## Comportamento attuale
L'icona si sovrappone al testo. [Immagine](https://gyazo.com/b576f6afa22296ab7af4055e5860fc44)

## Possibili soluzioni
Aggiungere `right: icon-size + padding` (i.e. `right: -30px`) alla classe `.btn-eye`

## Contesto
Non necessario.

**Comment by francescozaia** [comment]
Dovrebbe essere ok ora.
