### ISSUE TITLE
Bootstrap Italia v0.15.4 non include il file italia-icon-font.css

### ISSUE THREAD

**Issue by NicolaFerracin** [italia/bootstrap-italia#221]
## Comportamento atteso

- scarica Bootstrap Italia v0.15.4
- importa `italia-icon-font.css` come da [documentazione](https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/), dalla cartella `css`

## Comportamento attuale

Nella cartella `css` non c'è alcun file `italia-icon-font.css`

Lo stesso avviene se si importa `bootstrap-italia` come una node dependency (`npm i bootstrap-italia`).

**Comment by francescozaia** [comment]
Grazie @NicolaFerracin, dev'esserci stato un problema di regressione nel deploy di una delle ultime versioni. 

Vediamo di sistemarlo il prima possibile.

**Comment by francescozaia** [comment]
Ok, ho verificato.
Era solo un rimasuglio della precedente documentazione.
Ora infatti non è più necessario includere alcun file aggiuntivo oltre al CSS principale `bootstrap-italia.min.css` poiché le icone sono incluse in esso (ora gestite con una sprite SVG e non più come font).

È una soluzione ancora in discussione e forse non definitiva, ma almeno [documentazione](https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/) e codice ora sono allineati.

Grazie per l'heads-up!
