### ISSUE TITLE
OwlCarousel 

### ISSUE THREAD

**Issue by glonis** [italia/bootstrap-italia#253]
## Comportamento atteso
Ciao,
sto utilizzando bootstrap-italia senza bundle in modo da poter gestire owl-carousel in modo indipendente.

## Comportamento attuale
Ho impostato gli item del carousel in modo responsivo, ma non funziona. C'è qualcosa sul file js bootstrap-italia.min.js che ricalcola la larghezza degli item.

## Possibili soluzioni
La Versione Semplice non dovrebbe avere nessun riferimento o modificare il comportamento di Owl-carousel.

**Comment by francescozaia** [comment]
Ciao @glonis, appunto corretto grazie. Vediamo di metterci mano appena possibile, è uno dei motivi per i quali quel componente è ancora marcato come `wip`.

Al volo posso dirti che il file incriminato dovrebbe essere [questo](https://github.com/italia/bootstrap-italia/blob/master/src/js/plugins/carousel.js), e forse nel frattempo puoi provare a [ricompilare la libreria](http://localhost:4000/docs/come-iniziare/strumenti-di-compilazione/) escludendo [carousel.js](https://github.com/italia/bootstrap-italia/blob/master/gulpfile.js#L66) dalla compilazione.

**Comment by glonis** [comment]
Grazie @francescozaia,
si esatto è proprio quello. Ho ricompilato e ora non va in conflitto.

**Comment by francescozaia** [comment]
Ho fatto una (brutta) [patch](https://github.com/italia/bootstrap-italia/commit/2c229f952ef705e857a6792b05c878dde264734c) al volo, poi lo sistemeremo a dovere. Se usi la versione `0.27.4` non dovresti avere più conflitti, anche includendo la libreria così com'è.

**Comment by francescozaia** [comment]
Chiudo per inattività, dovrebbe essere ok.
