### ISSUE TITLE
Bootstrap-Italia non caricato con webpack

### ISSUE THREAD

**Issue by Playrom** [italia/bootstrap-italia#254]
## Comportamento atteso
`import 'bootstrap-italia'`
in un file compilato da webpack dovrebbe caricare tutti quanti i componenti, esattamente come avviene usando `import 'bootstrap'` per bootstrap 

## Comportamento attuale
Module not found: Can't resolve 'bootstrap-italia'
probabilmente perchè manca un entry-point nel package.json di bootstrap-italia

## Contesto
Sto usando create-react-app

**Comment by Playrom** [comment]
quando esco da lavoro provo e ti faccio sapere, grazie mille per la veloce risposta 👍

**Comment by Playrom** [comment]
non so perchè mi da questo errore, eppure è uguale alla tua repo il mio codice di importazione

`./node_modules/bootstrap-italia/dist/css/bootstrap-italia.min.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/bootstrap-italia/dist/css/bootstrap-italia.min.css)

Module not found: Can't resolve '../../node_modules/owl.carousel/dist/assets/owl.video.play.png'`

**Comment by Playrom** [comment]
il succo penso sia nel css c'è un riferimento a owl.carousel che però , secondo bootstrap-italia, è installato dentro un node-modules dentro bootstrap-italia, mentre invece è una dipendenza di tutto il progetto 

Inoltre proprio bootstrap-italia non installa proprio nessuna dipendenza al suo interno

**Comment by Playrom** [comment]
se faccio yarn install dentro la directory bootstrap-italia funziona tutto correttamente

**Comment by francescozaia** [comment]
[Questo commit](https://github.com/italia/bootstrap-italia/commit/cd9a8190c65386f4aa9d0fb66f962b820cc7ca0f) dovrebbe aver escluso la parte di owl.carousel incriminata.
