### ISSUE TITLE
Problema Bootstrap-Italia v0.27.6

### ISSUE THREAD

**Issue by AciDBurneR0** [italia/bootstrap-italia#255]
Buongiorno,

Stavo installando l'ultima versione di bootstrap-italia per necessità di utilizzare il Datepicker e il Timepicker.

Purtoppo mi da un errore di css che non saprei come risolvere:

<img width="759" alt="prob 1" src="https://user-images.githubusercontent.com/34127177/50210731-2d72ca80-0377-11e9-813b-225e4d57091b.png">

Ho un bisogno urgente di risolvere il problema per una scandenza imminente.

Grazie in anticipo,

Dan.

**Comment by francescozaia** [comment]
Stai ricompilando la libreria dai file SASS giusto?
Sembra si tratti di un problema di path, puoi provare a sostituire `@import url('../../node_modules/...')` con `@import url('/node_modules/...')` nel file `src/scss/bootstrap-italia.scss`.

**Comment by Morpheu5** [comment]
La soluzione suggerita non ha funzionato per me, quello che ha funzionato è invece cambiare quei due `@import` togliendo `url()`, così:

    @import 'node_modules/bootstrap-select/dist/css/bootstrap-select.min.css';
    @import 'node_modules/owl.carousel/dist/assets/owl.carousel.min.css';

C'è un altro problema più giù con l'importazione di `datepicker`, ho dovuto togliere l'estensione:

    @import "custom/datepicker";

**Comment by francescozaia** [comment]
Ottimo, grazie @Morpheu5

**Comment by AciDBurneR0** [comment]
Grazie @Morpheu5 , la tua soluzione ha funzionato anche per me.

**Comment by francescozaia** [comment]
Nella versione 0.27.7 dovrebbero essere [sistemati gli import](https://github.com/italia/bootstrap-italia/commit/8a485e1e74e8a7385ec0362ef1621a6c4ffe4d57).
