### ISSUE TITLE
Font serif per corpo delle card

### ISSUE THREAD

**Issue by Morpheu5** [italia/bootstrap-italia#256]
## Comportamento atteso

Le card aderiscono alle [linee guida grafiche](https://italia.github.io/design-web-toolkit/components/detail/card--default.html).

## Comportamento attuale

Ho notato che le card di `bootstrap-italia` usano il font serif mentre le specifiche grafiche usano ancora il sans serif.

Mi chiedevo se fosse un bug o se le linee guida fossero cambiate senza aggiornamento corrispondente nel sito.

**Comment by Morpheu5** [comment]
Qualche info extra. Questa è la grafica delle card come appare con `bootstrap-italia` `^0.19.1`.

![image](https://user-images.githubusercontent.com/411507/50558987-c4823f80-0cf2-11e9-98d2-8dcd009a2068.png?)

Questa invece è la grafica usando l'ultima versione di `bootstrap-italia`

![image](https://user-images.githubusercontent.com/411507/50559171-7e2de000-0cf4-11e9-8ad1-b3997cef65ea.png)

Sto usando `bootstrap-vue` e il codice per generare la card è questo

    </b-row>
        <b-col md="6" lg="4">
            <b-card class="mt-5 mt-lg-5">
                <p v-if="currentLocale.iso == 'en-GB'">
                    We'd love to hear from you! Please get in touch if you want to share your ideas, help us out, or just say hi!
                </p>
                <p v-if="currentLocale.iso == 'it-IT'">
                    Vogliamo sapere cosa pensi! Contattaci se vuoi condividere un'idea, aiutarci, o anche solo per un saluto!
                </p>
                <b-btn :href="localePath('contact')" variant="primary" class="mt-4">{{ $t('contact_page.title') }} ›</b-btn>
            </b-card>
        </b-col>
    </b-row>

che produce questo

    <div class="col-md-6 col-lg-4">
        <div class="card mt-5 mt-lg-5">
            <div class="card-body">
                <p class="card-text">
                    We'd love to hear from you! Please get in touch if you want to share your ideas, help us out, or just say hi!
                </p>
                <a href="/en/contact" target="_self" class="btn mt-4 btn-primary">Contact Us ›</a>
            </div>
        </div>
    </div>

**Comment by francescozaia** [comment]
Ciao @Morpheu5,

Aspettavo a risponderti perché al momento purtroppo il nuovo [UI kit di Design](https://designers.italia.it/kit/ui-kit/) non è accessibile per problemi di rinnovo dell'account inVision (questo sarebbe il link: https://projects.invisionapp.com/share/RJFGS2UC3HS), ma ci provo lo stesso.

In breve, il web toolkit che hai linkato in alto come "linee guida grafiche" non sarà più, dal punto di vista di risultato finale, il riferimento (pur rimanendo una risorsa valida ai fini della creazione di servizi accessibili e conformi alle [Linee Guida di Design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/)).

Da qui in avanti il riferimento grafico sarà invece lo UI Kit che ho linkato sopra, a cui si affianca l'implementazione web di riferimento che è appunto Bootstrap Italia - che sarà allineato allo UI Kit al 100% e di cui rilasceremo a brevissimo una versione stabile 1.0 una volta sistemati alcuni bug.

Entrando un po' nel contesto della issue quindi, ti confermo che va benissimo (per essere future-proof) usare quanto presenti su Bootstrap Italia, in quanto il nuovo UI Kit definisce le card con font serif, e quindi anche Bootstrap Italia si è adeguato a questo nelle più recenti release.

Ti allego uno screenshot di quanto sarà visibile a quel link di InVision che purtroppo, al momento, non è accessibile:
![italia-datadisplay-cards](https://user-images.githubusercontent.com/481084/50561319-d6bba800-0d09-11e9-8ded-58904b293bea.jpg)

**Comment by Morpheu5** [comment]
Ciao @francescozaia, grazie mille per il chiarimento! Cominciavo a pensare di essere impazzito io :) E buon anno nuovo!
