### ISSUE TITLE
Dropdown non funzionante con la versione 6.1.5 di Angular.

### ISSUE THREAD

**Issue by AciDBurneR0** [italia/bootstrap-italia#258]
Buona sera,

Come da titolo sto lavorando utilizzando le versioni più aggiornate di bootstrap-italia e la versione 6.1.5 di Angular.

Ho notato adesso che il Dropdown non funziona. (Quando viene cliccato il button non viene aperto nessun menu a tendina). 

Funziona invece a dovere nella versione 7.0.1 di Angular.

Per accertarmi che sia il problema della versione di Angular ho creato due progetti appositamente per testare la cosa, uno con la versione 6 e l'altro con la 7. 

C'è qualche rimedio al problema? Pensavo di fare il downgrade di bootstrap (prima funzionava) ma perderei le ultime implementazioni.

P.s Nei log non da  nessun errore

Grazie in anticipo.

**Comment by gtico80** [comment]
Mi sembra un errore non dovuto al caricamento dei moduli globali aggiungendo il riferimento al bundle js bootstrap-italia nella sezione scripts di angular-cli.json (vedere https://github.com/angular/angular-cli/wiki/stories-global-scripts per riferimenti ) mi sembra funzionare.
