### ISSUE TITLE
Problema con OwlCarousel importando solo il SCSS (per tema personalizzato)

### ISSUE THREAD

**Issue by Morpheu5** [italia/bootstrap-italia#262]
Fino a poco tempo fa, importavo il scss di `boostrap-italia` dentro al mio scss così

    @import "~bootstrap-italia/src/scss/bootstrap-italia.scss";

perché ho bisogno di modificare alcuni colori al tema. Di recente, (quasi) sicuramente dalla versione 0.27 in avanti, e sicuramente dalla 0.29.1 che uso al momento, la compilazione si ferma all'importazione di un PNG da OwlCarousel. Ora, quel file (`owl.video.play.png`) è menzionato solo in questi due file

    ./dist/css/bootstrap-italia.min.css
    ./dist/css/bootstrap-italia.min.css.map

(relativi al path di bootstrap-italia) e quindi non dovrebbero essere inclusi quando includo il scss, no? O sto sbagliando qualcosa?

**EDIT** Repo di riferimento: https://github.com/Morpheu5/UniJobs-www/commit/58e3e2a2d0063986bd4f5b388d94a660508f10a1

**Comment by francescozaia** [comment]
Ciao, è possibile che l'inclusione di OwlCarousel abbia creato qualche issue (infatti la stiamo rivalutando), verifichiamo il prima possibile. Nel frattempo ti volevo chiedere perché non chiami direttamente il CSS di Bootstrap Italia come file CSS esterno invece di ripassarlo per la compilazione di SASS.

Ad ogni modo, da quanto vedo nel [file SASS di BI](https://github.com/italia/bootstrap-italia/blob/master/src/scss/bootstrap-italia.scss), esso importa `node_modules/owl.carousel/dist/assets/owl.carousel.min` che a sua volta contiene internamente quella png (presente nella directory), che penso per motivi di path relativo non riesca a vedere.

Ti aggiorno al più presto

**Comment by francescozaia** [comment]
@Morpheu5 ho appena pubblicato un fix al volo perché poi sono impegnato tutto il giorno. 🤞

Nella release [0.29.2](https://github.com/italia/bootstrap-italia/releases/tag/v0.29.2) questo problema dovrebbe essere sparito.

**Comment by Morpheu5** [comment]
@francescozaia grazie mille, poi provo e ti so dire.

**Comment by Morpheu5** [comment]
@francescozaia scusa, dimenticavo di spiegare. Includo direttamente il SASS per poter cambiare alcuni colori senza dover fare una build separata. Magari sbaglio io e c'è un altro metodo.

**Comment by francescozaia** [comment]
> @francescozaia scusa, dimenticavo di spiegare. Includo direttamente il SASS per poter cambiare alcuni colori senza dover fare una build separata. Magari sbaglio io e c'è un altro metodo.

Correttissimo. Era giusto per capire se era una necessità oppure no! Grazie del feedback.
