### ISSUE TITLE
ReferenceError: bootstrap is not defined

### ISSUE THREAD

**Issue by Playrom** [italia/bootstrap-italia#275]
Uso bootstrap-italia importandolo da repository npm, con react e webpack

Importo bootstrap-italia nell'entry point della mia app react

`import 'bootstrap-italia'`

ma mi da questo errore

`ReferenceError: bootstrap is not defined
(anonymous function)
node_modules/bootstrap-italia/dist/js/bootstrap-italia.min.js:1786`

**Comment by Playrom** [comment]
ho risolto inserendo prima dell'import

    import * as bootstrap from 'bootstrap'
    window.bootstrap = bootstrap

ma non penso sia un comportamento richiesto, penso necessiti di un fix la distribuzione

**Comment by francescozaia** [comment]
Ciao @Playrom grazie per la issue, ne siamo al corrente - c'è un po' di js che va rivisto in termini di struttura - la prendiamo in carico al più presto e aggiorniamo la issue quando ok.

**Comment by yashwanthambati** [comment]
Use bootsrap italia cdn on index.html on create-react-app

**Comment by Playrom** [comment]
sicuramente funzionerebbe, però si perde la potenza e la facilità di gestione di create-react-app e npm così facendo

**Comment by francescozaia** [comment]
Ricordo di aver fatto [questa prova](https://github.com/francescozaia/create-react-app-bootstrap-italia/) mesi fa... anche se probabilmente sarebbe da rivedere.

**Comment by astagi** [comment]
Perfetto @gpeirolo chiudo :)
