### ISSUE TITLE
Input con icona e bottoni label sovrapposta al bottone

### ISSUE THREAD

**Issue by gtico80** [italia/bootstrap-italia#287]
In https://italia.github.io/bootstrap-italia/docs/form/input/ la label "con etichetta e bottone primary" si sovrappone al bottone invio quando vista da un dispositivo mobile. 

## Possibili soluzioni
Il problema è nella screen width del dispositivo che non ha spazio per la parola "primary" inline. Due possibili soluzioni alternative : 1) aggiornare la documentazione per evidenziare il problema o 2) abilitare text elipsis per tali dispositivi .

**Comment by francescozaia** [comment]
Assolutamente corretto, vediamo di sistemare al più presto. Grazie!

**Comment by gtico80** [comment]
PR #288 con una soluzione che abilita il text-ellipsis solo in determinati casi-
