### ISSUE TITLE
Select W3C Compliant

### ISSUE THREAD

**Issue by giusnadd** [italia/bootstrap-italia#293]
## Comportamento atteso
L'html prodotto dalla select BI deve rispettare la validazione W3C

## Comportamento attuale

![w3c validation](https://user-images.githubusercontent.com/40893660/53646129-b8efbe00-3c3a-11e9-94fe-0fe115cf2c08.PNG)

**Comment by gtico80** [comment]
Una possibile soluzione modificando tramite javascript https://jsfiddle.net/w4r8s7em/2/ però potrebbe essere sensibile alle modifiche della libreria.
@francescozaia : qual'è la tua opinione?

**Comment by giusnadd** [comment]
@francescozaia temo che qualcosa non stia funzionando come deve. Dalla documentazione vedo che lo <span> con class="filter-option" non è stato sostituito con il <div>, in più riscontro delle anomalie sia sulla creazione del <div class="dropdown-menu"> che nel mero utilizzo della select sul mio progetto, ottengo questo errore:
ERROR TypeError: Cannot set property 'selected' of undefined
    at HTMLAnchorElement.<anonymous> (bootstrap-italia.bundle.min.js:7)
    at HTMLDivElement.dispatch (bootstrap-italia.bundle.min.js:7)
    at HTMLDivElement.g.handle (bootstrap-italia.bundle.min.js:7)
[...] 
Qualche indicazione ?

**Comment by giusnadd** [comment]
Sembrerebbe che l'errore derivi da una chiamata "di troppo" al `.selectpicker()` di `bootstrap-select' https://developer.snapappointments.com/bootstrap-select/methods/
Temo che forzando i cambiamenti al DOM abbiamo scassato qualche comportamento nativo.
Per ora ho trovato la soluzione, ma mi sa che le modifiche sono un attimo da rivedere.
Ci lavorerò ancora un po' su fin quando posso e ti farò sapere. 
Dimmi se preferisci che apra una nuova issue a questo punto.

**Comment by francescozaia** [comment]
Ciao @giusnadd evidentemente mergiare le PR di domenica mattina non funziona troppo bene. 😅 

Vedo anch'io appena posso (spero già in giornata), purtroppo assieme alle tue modifiche ho dovuto aggiornare anche la versione di `bootstrap-select` che sistemava un po' di questioni sia di a11y che di sicurezza, cosa che ha cambiato un po' la gestione del DOM generato. Aggiorniamoci pure qui o su [Slack](https://developersitalia.slack.com/).

**Comment by giusnadd** [comment]
Ah, quindi forse abbiamo generato una combo letale... infatti riscontro comportamenti anomali ogni volta che richiamo i metodi della `bootstrap-select`. Ci aggiorniamo.

**Comment by francescozaia** [comment]
Dovrei aver sistemato almeno il DOM al volo, disponibile nella versione 1.3.1.

**Comment by giusnadd** [comment]
Allora, ho continuato ad indagare:
1) riguardo l'errore sopra menzionato, prima per resettare da libreria il value della select si doveva eseguire `$(.bootstrap-select-wrapper select).val('default')` e poi il refresh. Adesso quando si esegue il primo comando invece si rompe la select, ovvero qualunque valore selezionato dal menu a tendina scatena quell'errore. Da documentazione ufficiale mi sono accorto che in realtà questo comando non era specificato, però è anche vero che la documentazione (come anche il download ufficiale) sono rimasti alla versione 1.3.9. Secondo me comunque si tratta di un bug di cui ancora non si sono accorti.
2) Nella 1.3.10 il DOM generato è leggermente cambiato, per cui alcune modifiche da me proposte nella PR non sono più valide. In più quando importo il bundle di boostrap-italia dai node_modules di progetto le modifiche non vengono recepite, come se il rendering di default venisse rieseguito sovrascrivendole o come se non venissero proprio eseguite

**Comment by giusnadd** [comment]
Nuova PR --> https://github.com/italia/bootstrap-italia/pull/344
