### ISSUE TITLE
TEMA wppa per sito scuola 

### ISSUE THREAD

**Issue by elenasass** [italia/bootstrap-italia#297]
Salve, gestisco il sito della scuola. é appena sparito il menu principale . Che succede? Me lo potete controllare? cpiabl.edu.it
il tema design ha smesso di funzionare (il menu lingua mostrava una casella di spunta)e ho scelto WPPA, va bene?
come posso reintallare e ripulire il tema e casomai controllare se va tutto bene? mi dà errore bootstrap e file json (che non so dove deve essere caricato) se guardo codice pagina o elemento.

Grazie
Elena

**Comment by francescozaia** [comment]
Salve @elenasass, non è possibile che una modifica fatta sulla libreria abbia fatto sparire il menu sul vostro sito. 

Gli errori che vedo e che indichi non dovrebbero creare alcun problema a sito. Ssono dovuti all'errato caricamento di file `bootstrap-italia.min.css.map` come CSS, che in realtà non va caricato, a differenza del CSS, che è importante.

In breve, questo va caricato (ed è già corretto):
`<link rel="stylesheet" id="bootstrap-italia-min-css" href="https://www.cpiabl.edu.it/wp-content/themes/wppa/bootstrap-italia/css/bootstrap-italia.min.css" type="text/css" media="all">`
Ma questo non serve (si può rimuovere):
`<link rel="stylesheet" id="bootstrap-italia-min-css" href="https://www.cpiabl.edu.it/wp-content/themes/wppa/bootstrap-italia/css/bootstrap-italia.min.css.map" type="text/css" media="all">`

Riguardo il menu, da questo screenshot si può però vedere che il codice (in verde) che dovrebbe mostrare il menu sembra commentato:
<img width="1434" alt="Screenshot 2019-03-17 at 21 13 14" src="https://user-images.githubusercontent.com/481084/54497324-91b31500-48f9-11e9-9713-50c1ccc0d0ea.png">

Per cui mi sa che dovreste chiedere a chi gestisce il vostro Wordpress di controllare. Spero possa aiutare.

**Comment by marcogargano** [comment]
Ciao @elenasass 
ho notato che stai usando una versione superata del tema.
Ora si chiama "Design Italia"; la versione aggiornata e la descrizione le puoi trovare qui:
[https://github.com/italia/design-wordpress-theme](https://github.com/italia/design-wordpress-theme)
