### ISSUE TITLE
[BUG] Form - Input numerico: supporto IE11

### ISSUE THREAD

**Issue by gtico80** [italia/bootstrap-italia#298]
## Comportamento atteso

Il campo numerico non dovrebbe permettere l'inserimento di lettere ed eventualmente supportare anche i bottoni su e giù (come su chrome)

## Comportamento attuale

Il campo numerico viene mostrato come un input di testo 

## Possibili soluzioni

Utilizzo di funzione di riconoscimento del browser per disabilitare il keydown su tale input

## Contesto

IE11 windows 10

**Comment by francescozaia** [comment]
Avevo [iniziato a metterci mano](https://github.com/italia/bootstrap-italia/commit/89b1acf066a86805802c82c77f3c7a75a39d6f26), ma poi non ho più avuto tempo purtroppo.

**Comment by gtico80** [comment]
Una soluzione per utilizzare l'input numerico su ie11 anche con i bottoni su e giù potrebbe essere di utilizzare un polyfill vedi ad esempio https://github.com/jonstipe/number-polyfill . Potrebbe essere ok o si vuole lasciare tale compito all'utilizzatore di bi? @francescozaia

**Comment by redbaron76** [comment]
Proposta PR https://github.com/italia/bootstrap-italia/pull/366
