### ISSUE TITLE
[Feature] Header "sticky"

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#302]
## Comportamento atteso
Vorremmo fornire agli sviluppatori che fanno uso di Bootstrap Italia la possibilità di avere un header che si comprima allo scorrere della pagina, pur lasciando visibile soltanto il menu principale e l'eventuale bottone per la ricerca, secondo questa logica che sarà aggiunta anche sulle [artboard di InVision](https://invis.io/VRR2TLB34TE) dello UI Kit a breve:
![italia-layout-footer](https://user-images.githubusercontent.com/481084/56191717-2d38c200-602d-11e9-92a3-ad0155b839da.jpeg).

Metterei l'esempio in coda alla [pagina dedicata all'header](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/#header-completa) nella documentazione.

In una issue separata aggiorneremo anche il [Template di Esempio](https://italia.github.io/bootstrap-italia/docs/esempi/template-vuoto/).

## Comportamento attuale
Tale funzionalità non è presente pur essendo implementata, in modo dedicato, sul [prototipo del sito del Cagliari](https://prototipo.comune.cagliari.it/ponmetroca/).

**Comment by francescozaia** [comment]
On hold, in attesa di feedback mio e di @nikorobins, sentita stamattina.

**Comment by francescozaia** [comment]
Abbiamo ridefinito un po' spazi e posizionamenti visto l'attuale ingombro eccessivo della barra in verticale. Pensavamo quindi di rivedere l'header in questo senso:
![header_medium](https://user-images.githubusercontent.com/481084/56670287-de38ff80-66b2-11e9-8858-46b25a4c7a1a.png)
In cui il logo si rimpicciolisce ulteriormente e rimane tutto in linea, centrato verticalmente. Il testo non si rimpicciolisce; resta da capire se lasciare il bottone "Accedi" o sacrificarlo nel caso ci sia poco spazio disponibile.

**Comment by redbaron76** [comment]
Inviata nuova proposta di layout per lo sticky come da bozza.
