### ISSUE TITLE
[Template Comuni] Creazione template base

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#307]
## Comportamento atteso
Creazione di un template "scheletro" vuoto con:
- header completo adattabile allo scorrere della pagina
- voci di menu
- footer completo

Il risultato sarà molto simile all'attuale [template vuoto](https://italia.github.io/bootstrap-italia/docs/esempi/template-vuoto/), ma con maggior focus su AI, contenuti e specificità del progetto Comuni, così come da [layout hi-fi su InVision](https://invis.io/9FL7CESJ8ZU).
La parte di _contenuto_ della pagina resterà per ora vuota con testo riempitivo di tipo _"Lorem Ipsum"_.

**Comment by enricobasso** [comment]
Non so se sia voluto ma il layout su InVision non è pubblico.

**Comment by francescozaia** [comment]
> Non so se sia voluto ma il layout su InVision non è pubblico.

Grazie @enricobasso, ora dovrebbe essere visibile a tutti.

**Comment by redbaron76** [comment]
Pushata la mia proposta di `Template Vuoto Comuni` inserita nella pagina `Esempi` di Bootsrap Italia.
Proposta ancora **WORK IN PROGRESS**

**Comment by francescozaia** [comment]
Una prima versione è online: https://italia.github.io/bootstrap-italia/docs/esempi/template-comuni-vuoto/
