### ISSUE TITLE
[Feature] Documentazione personalizzazione del colore primario

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#312]
## Comportamento atteso
Definire e documentare come creare/esportare una versione di Bootstrap Italia che personalizzi il colore primario blu, non utilizzabile dalle Pubbliche Amministrazioni Locali.

In caso di modifiche necessarie alla code base o a specifici componenti, creiamo issue dedicate.

**Comment by redbaron76** [comment]
La soluzione trovata implica il fatto di dover lavorare con i file sorgente `*.scss`, delegando la compilazione della libreria al bundler stesso del progetto.

In un ipotetico scenario di una applicazione _React_ in ambiente _Node_ e compilata da _Webpack_, è necessario:

1. Installare **Bootstrap Italia** con _yarn/npm_: `yarn add bootstrap-italia --save`
2. Installare **node-sass**: `yarn add node-sass`
3. Creare all'interno del progetto -> `/src` una cartella **scss**
4. Dentro alla cartella `/src/scss` creare un file del tipo **custom-bootstrap.scss**
5. Impostare le variabili di default da modificare con dei valori **custom**
6. Importare la libreria _Bootstrap-Italia_ da **node_modules** alla fine del file
```
// file: custom-bootstrap.scss

// override variabile
$primary: lime;

// import libreria
@import "../../node_modules/bootstrap-italia/src/scss/bootstrap-italia.scss";
```
7. Nei file _*.js_, importare `custom-bootstrap.scss` laddove serva utilizzare il framework _Bootstrap-Italia_

**Comment by redbaron76** [comment]
Consultare la documentazione ufficiale di Bootstrap Italia per ulteriori informazioni.
