### ISSUE TITLE
Errore in console dal codice dello sticky header

### ISSUE THREAD

**Issue by pdavide** [italia/bootstrap-italia#318]
## Comportamento attuale
Errore in console `Cannot read property 'cloneNode' of null` all'evento scroll che attiva lo sticky header se nell'header non è presente il componente di ricerca (`.it-search-wrapper`).

## Possibili soluzioni
Verificare l'esistenza del nodo prima di clonarlo.
https://github.com/italia/bootstrap-italia/blob/c5e0c1c9dc8acc1a047aa5ef2125548ecc015fe1/src/js/plugins/sticky-header.js#L42

**Comment by francescozaia** [comment]
Grazie @pdavide, ci guardiamo domani!

**Comment by pdavide** [comment]
Ho iniziato a lavorare, con molta lentezza, sul frontend di Web Analytics Italia e quindi, con bootstrap-Italia.
Spero di trovare più tempo per contribuire a questo fantastico progetto.
