### ISSUE TITLE
Pubblicare Bootstrap-Italia come WebJars

### ISSUE THREAD

**Issue by Skalda73** [italia/bootstrap-italia#326]
Ciao,
avete già preso in considerazione la possibilità di pubblicare la libreria Bootstrap-Italia tramite pacchetti webjars? 
https://www.webjars.org/

Utile soprattutto per quei poveracci come me che sviluppano in Java. :wink:
https://www.webjars.org/request 
(deve essere compilato da un contributor del progetto Bootstrap-Italia)
https://www.webjars.org/contributing 

In questo modo le librerie saranno disponibili su NPN e Maven Repository.

Edit:
Ho fatto un tentativo io, dal sito di WebJars è possibile fare una submit usando NPM  e  Bower GitHub, ma dato che non viene fatta alcuna "compilazione" ovviamente i files non sono utilizzabili:
https://www.webjars.org/listfiles/org.webjars.npm/github-com-italia-bootstrap-italia/1.2.8
Forse, in analogia ad altri progetti come:
https://github.com/twbs/bootstrap
https://github.com/ColorlibHQ/AdminLTE

Bisognerebbe mettere una directory \dist con il css e js compilato.

**Comment by Skalda73** [comment]
Come scritto su Slack sarebbe sufficiente avere un repository GitHub parallelo che contenesse dentro una directory /dist il contenuto dello zip dell'ultima versione disponibile qui:
https://github.com/italia/bootstrap-italia/releases

Ad esempio:
https://github.com/italia/bootstrap-italia-dist/dist/css/boostrap-italia.min.css

**Comment by astagi** [comment]
Interessante @Skalda73 ad oggi e nelle release future le release contengono lo zip con i file minificati. La parte interessante potrebbe essere integrare la pubblicazione su WebJars in CI, così come facciamo per NPM. Chiudo questa issue e semmai vorrai procedere con questa integrazione in CI saremo ben lieti di darti una mano!
