### ISSUE TITLE
Verificare icone

### ISSUE THREAD

**Issue by pdavide** [italia/bootstrap-italia#329]
Alcune icone introdotte con la #328 non sono allineate al centro del loro viewBox (come ad esempio `expand`). Questo causa un effetto di spostamento verticale all'apertura/chiusura dei dropdown e dei collapse.

Inoltre tutte le icone hanno anche un rettangolo trasparente non usato:
```svg
<g>
    <rect width="24" height="24" fill="none"/>
</g>
```

**Comment by francescozaia** [comment]
Grazie @pdavide se riesco vedo già oggi (uff).

**Comment by francescozaia** [comment]
Online a breve la v1.2.10 con il fix sulle 4 icone `expand`, `collapse`, `chevron-left` e `chevron-right`. Seguirà un check più approfondito riguardo gli assi su cui le icone sono posizionate.
