### ISSUE TITLE
Sticky header fa perdere lo slim header on scroll quando la console di sviluppo è aperta

### ISSUE THREAD

**Issue by robertogallea** [italia/bootstrap-italia#343]
## Comportamento atteso
Quando è presente uno sticky header, se si torna in testa alla pagina a seguito di uno scroll, dovrebbe riapparire lo slim header

## Comportamento attuale
1. In presenza di sticky header, effettuare uno scroll fino all'attivazione dello stesso
2. Aprire gli "strumenti per sviluppatori"
3. Chiudere gli "strumenti per svlippatori"
4. Effettuare lo scroll fino al top della pagina, lo slim header non riappare

## Contesto
Testato con i seguenti browser:
- Chrome
- Firefox
- Edge

![Sticky Header Bug](https://user-images.githubusercontent.com/19411470/59583774-9778ec00-90dc-11e9-82eb-873bb1c6cc53.png)

**Comment by redbaron76** [comment]
Problema risolto con la prossima release.
