### ISSUE TITLE
Classe text-white

### ISSUE THREAD

**Issue by jsb81** [italia/bootstrap-italia#351]
## Comportamento atteso
color: #fff !important;

## Comportamento attuale
color: #d9d9d9 !important;

## Possibili soluzioni
verificare il valore della variabile $white

**Comment by francescozaia** [comment]
Anche `text-primary` e gli altri colori subiscono un `darken($color, 15%)` in SASS da verificare.

**Comment by redbaron76** [comment]
Impostata eccezione al `text-emphasis-variant` per il colore bianco.
