### ISSUE TITLE
[Template Comuni] Creazione template di pagina per la lista di Argomenti

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#355]
## Comportamento atteso
Con riferimento alla [Pagina di lista degli argomenti](http://ponmetroca.consulmedia.it/ponmetroca/it/argomenti.page) del prototipo di Cagliari, metterne a disposizione una versione open.

Andranno inseriti gli argomenti presenti nel [foglio "Lista Argomenti"](https://docs.google.com/spreadsheets/d/1HpQ61viC4z5hcHEP4gGot2tPetFQGDyb9keF2ssA4ig/edit#gid=1102255231) del documento sull'Architettura dell'Informazione.

**Comment by redbaron76** [comment]
Aperta nuova PR per la prima bozza di proposta della pagina.
