### ISSUE TITLE
[BUG] Cookiebar div multiline behaviour

### ISSUE THREAD

**Issue by libremente** [italia/bootstrap-italia#358]
## Comportamento atteso

I believe the cookiebar should look like this:
![Schermata da 2019-07-07 11-56-05](https://user-images.githubusercontent.com/25111463/60766722-3e362400-a0ae-11e9-93a3-2f9c8e7785b4.png)

## Comportamento attuale

As of now, it looks like this:
![Schermata da 2019-07-07 11-53-31](https://user-images.githubusercontent.com/25111463/60766726-4aba7c80-a0ae-11e9-8e66-fc84370f2563.png)

## Possibili soluzioni

Now the two cookiebar divs are both `md-6`. I quickly tried changing them to `md-8` and `md-4` and I had the result shown in the first image. However, I'm not sure if this may break something.  I can make a PR if you wish @francescozaia. 

## Contesto

FF 67, GNU/Linux

**Comment by redbaron76** [comment]
This bug seems to be already fixed.
Current behaviour shows a flex container that contains two block, one for text and the other for the buttons. It works nicely IMHO.

**Comment by francescozaia** [comment]
Closing as no feedback
