### ISSUE TITLE
[BUG] Il toggle per la password rimane sopra alla testata

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#361]
## Comportamento atteso
L'header dovrebbe avere uno `z-index` maggiore o essere gestito in modo che rimanga in primo piano.

## Comportamento attuale
Il toggle per la password rimane sopra all'header.
![image](https://user-images.githubusercontent.com/481084/61201602-4fea7d80-a6e5-11e9-980f-b2d7950c51dd.png)

**Comment by redbaron76** [comment]
Proposta PR https://github.com/italia/bootstrap-italia/pull/367
