### ISSUE TITLE
[BUG] Verificare i path delle SVG nelle pagine di esempio

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#363]
## Comportamento atteso
Nelle pagine di esempio dei template dei comuni le SVG dovrebbero essere visibili

## Comportamento attuale
Nelle pagine di esempio dei template dei comuni le SVG non sono visibili 

## Possibili soluzioni
È necessario assicurarsi di usare sempre `xlink:href="{{ site.baseurl }}/dist/svg/sprite.svg#..."` e mai il path relativo `xlink:href="/dist/svg/sprite.svg#...`. Un find & replace dovrebbe essere sufficiente.

**Comment by redbaron76** [comment]
Aperta PR di correzione
