### ISSUE TITLE
[Template Comuni] Creazione template per pagina di risultato ricerca

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#365]
## Comportamento atteso
Con riferimento alla [pagina realizzata dal Comune di Cagliari](https://francescozaia.github.io/design-comuni-prototipi/esempi/comune-di-cagliari/pagine-statiche/ricerca.html), e adattandola ai componenti già presenti su Bootstrap Italia, realizzare un template riutilizzabile per la SERP.

**Comment by redbaron76** [comment]
Inviata PR #370
