### ISSUE TITLE
[BUG] Form - Input numerico: supporto completo IE11

### ISSUE THREAD

**Issue by gtico80** [italia/bootstrap-italia#371]
## Comportamento atteso

Il campo numerico dovrebbe comportarsi su ie11 come su Chrome ovvero supportare anche i bottoni su e giù ed avere uno stile simile.

## Comportamento attuale

Il campo numerico viene mostrato come un input di testo

## Contesto

IE11 windows 10

**Comment by francescozaia** [comment]
@redbaron76 puoi verificare che il **funzionamento** del campo sia ok e accessibile per ogni browser? Per quanto riguarda la issue, a meno che il fix sia banale, in questo caso secondo me possiamo anche accontentarci di gestirlo con _graceful degradation_, in quanto l'utenza di IE11 non vale l'effort.

**Comment by francescozaia** [comment]
Riferimento a #388
