### ISSUE TITLE
Notifiche non mostrate in pagine esempio

### ISSUE THREAD

**Issue by gtico80** [italia/bootstrap-italia#378]
## Comportamento atteso

Le notifiche "Notification 7s" e "Notification  icon/text 7s default" prsenti nella pagina di esempio https://italia.github.io/bootstrap-italia/docs/esempi/notifications/ devono essere mostrate al click e sparire dopo 7s
## Comportamento attuale

Al momento non vengono mostrate al click, nella console è possibile vedere che il parametro defaultTimeout è undefined.
## Possibili soluzioni

Definire il parametro defaultTimeout 

## Contesto

Chrome ed edge win10

**Comment by francescozaia** [comment]
Ooops, grazie! Dev'esserci stato un bug di regressione a seguito di altre modifiche.
