### ISSUE TITLE
[Template Comuni] Creazione template per area personale

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#379]
## Comportamento atteso
Con riferimento ai layout condivisi internamente e allegati di seguito, creare un template di pagina per l'area personale, che riporti il menu di primo livello in testata e come dropdown in alto a destra.

Le voci di menu corrette sono visibili nel foglio _"Sistema di navigazione"_ dell'area personale nel [file dell'architettura dell'informazione](https://docs.google.com/spreadsheets/d/1bE0Ns0LsU0VDvCBT1WXZ5_yIxJU5AbUYcu_F8yMfpHQ/edit#gid=0) redatto da @mamatteo, per cui:

- Le mie pratiche
- Pagamenti
- Documenti
- Messaggi
- Scadenze

E infine "Il mio profilo" al posto di ciò che è indicato come "Impostazioni" nella bozza di layout.

![image](https://user-images.githubusercontent.com/481084/63496793-cdfb2a80-c4c2-11e9-9cba-65f03f430ffb.png)
![image (3)](https://user-images.githubusercontent.com/481084/63496796-cdfb2a80-c4c2-11e9-9e10-19b601946e48.png)

**Comment by redbaron76** [comment]
Inviata prima proposta completa di template per l'Area Personale come da screenshot allegati in questa issue.

**Comment by francescozaia** [comment]
Daniela ha aggiornato i wireframe per l'area personale nel wireframe kit: https://projects.invisionapp.com/d/main#/console/14568522/382039810/preview
