### ISSUE TITLE
Arrow functions JavaScript su alcuni smartphone Xiaomi e Huawei (Mi Browser)

### ISSUE THREAD

**Issue by Sorby** [italia/bootstrap-italia#382]
## Comportamento atteso
Corretto funzionamento degli script JavaScript sui device non obsoleti.

## Comportamento attuale
Su alcuni dispositivi Huawei e Xiaomi che utilizzano il Mi Browser, gli script JavaScript non vengono caricati a causa di un SyntaxError.
In particolare non risultano supportate le arrow functions (e presumibilmente tutto ciò che è stato introdotto in ECMA6).
Ho catturato l'errore con una funzione che stampa un alert all'evento window.onerror, eccolo: [https://imgur.com/7FhYCdA](https://imgur.com/7FhYCdA) su Huawei
e [https://imgur.com/jQKPaTG](https://imgur.com/jQKPaTG) su Xiaomi.

Il problema è stato riscontrato su HUAWEI NXT-AL 10 (Huawei Mate 8 versione cinese) con versione software NXT-AL10 8.0.0.839 (C00patch02).
Il Mi Browser è la versione 10.8.5.4721.

Il problema è stato riscontrato anche con uno Xiaomi Mi 5.

Per cause a me sconosciute, con la stessa versione del Mi Browser (10.8.5) installata manualmente su uno Xiaomi Mi A1, ma anche con versioni meno recenti, **funziona correttamente**.

## Possibili soluzioni
Utilizzare la vecchia sintassi.

Resto a disposizione per eventuali test aggiuntivi.

**Comment by redbaron76** [comment]
Salve, è possibile avere una descrizione su come è stato eseguito il test e quale versione della libreria è stata caricata nei suddetti browser?

Utilizziamo Babel come transpiler durante la release della distribuzione, pertanto tutto il codice compilato è compatibile ES5 e non presenta arrow functions o altro codice con sintassi ES6.

**Comment by francescozaia** [comment]
Chiudo per inattività
