### ISSUE TITLE
Stile radio button disabilitato

### ISSUE THREAD

**Issue by gtico80** [italia/bootstrap-italia#386]
## Comportamento atteso

Il radio button disabilitato ha lo stile identico a quello non selezionato, dovrebbe avere una tonalità di grigio più chiara per il bordo.

## Comportamento attuale

Stile identico radio button disabilitati ed abilitati, solamente il cursor cambia.

## Possibili soluzioni

Modifica dello stile .

## Contesto

Indipendente dal browser.

**Comment by francescozaia** [comment]
Temo sia un bug di regressione, ricordo che funzionava correttamente secondo quanto definito nello UI Kit:
https://projects.invisionapp.com/share/RJFGS2UC3HS#/screens/290616039
