### ISSUE TITLE
L'Header nav scompare completamente su dispositivi mobile

### ISSUE THREAD

**Issue by dej611** [italia/bootstrap-italia#394]
## Comportamento atteso
L'Header nav dovrebbe ridursi fino a mostrare la classica icona "hamburger".

## Comportamento attuale
L'header nav scompare completamente:

![header-nav](https://user-images.githubusercontent.com/924948/65126600-37555700-d9f7-11e9-817f-a10631e84965.gif)
(il flashing è causato dal redrawing completo a causa dell'evento resize)

## Contesto
Testato su Firefox e Chrome su MacOS.

**Comment by francescozaia** [comment]
Mi sa che l'icona hamburger c'è ma è bianco su grigio chiarissimo. Cmq verifichiamo, grazie.
