### ISSUE TITLE
Disabilitare correttamente la select multipla

### ISSUE THREAD

**Issue by smartm0use** [italia/bootstrap-italia#395]
## Comportamento atteso
Quando ho una select multipla disabilita non è possibile selezionare nessun elemento.

## Comportamento attuale
Provando a disabilitare la select multipla, aggiungendo la classe `disabled` al `div`, il dropdown continua ad aprirsi al click e le scelte risultano selezionabili.

## Possibili soluzioni
Aggiungendo anche l'attributo `disabled` al tag `select`, le scelte non sono selezionabili, ma il dropdown continua ad aprirsi, lasciando gli elementi visibili. Magari questo è opinabile, ma nel caso sia corretto non far aprire il dropdown, allora occorrerebbe non far comparire la classe `show` sul dropdown in caso di multi select disabilitata.

**Comment by capochiani** [comment]
Una possibile soluzione potrebbe essere quella di utilizzare nella checkbox un ng-model="all" a cui associare ng-disabled per ogni espressione. Quindi, nel caso della select: < select ng-disabled="all" >

**Comment by smartm0use** [comment]
Questo nel caso si stesse utilizzando Angular Kit?

**Comment by asha15** [comment]
Is any  one taken this issue?  I would like to work on it

**Comment by smartm0use** [comment]
Ok, first we should take a decision: if the select is disabled would we see the disabled options? Or opening select should be avoided?

**Comment by francescozaia** [comment]
I would say the `select` is disable altogether (ie. _opening select should be avoided_).

**Comment by francescozaia** [comment]
@asha15 if you want to give it a try, you're more than welcome. You may find some difficulties as the project is in italian language. You can try using Google Translate and this page to start: https://translate.googleusercontent.com/translate_c?depth=1&hl=it&rurl=translate.google.it&sl=it&sp=nmt4&tl=en&u=https://italia.github.io/bootstrap-italia/docs/come-iniziare/strumenti-di-compilazione/&xid=25657,15700022,15700186,15700191,15700256,15700259,15700262,15700265,15700271&usg=ALkJrhj8YFuMKoAln1HFvOhYuJDzr7gMPw#compilare-la-documentazione

**Comment by asha15** [comment]
@francescozaia  I don't get where the code is located at. Could you please help me ?

**Comment by FredBonux** [comment]
Non riesco a replicare il problema. Aggiungendo la classe disabled al select, non viene mostrato alcun dropdown (Chrome 78 & Safari 13)

**Comment by smartm0use** [comment]
Andando [qui](https://italia.github.io/bootstrap-italia/docs/form/select) c'è l'esempio per la "Select disabilitata" che funziona senza problemi.
C'era già quando ho segnalato la issue più di un mese fa?

**Comment by arturu** [comment]
Non sono riuscito a replicare il problema. Sembra funzionare correttamente

**Comment by francescozaia** [comment]
Anche secondo me è tutto ok, chiudo.
