### ISSUE TITLE
Image flickers on hovering Avatar link

### ISSUE THREAD

**Issue by kushagrarora17** [italia/bootstrap-italia#404]
**Description**
I found this issue in docs actually on link to Avatars .

**To Reproduce**
1. Open link - https://italia.github.io/bootstrap-italia/docs/componenti/avatar/
2. Scroll down to 'Avatar Link' heading
3. Hover over the first avatar link with image.

**Expected behavior**
On hover, only highlight effect should be visible

**Screenshots**
https://ibb.co/hBznspg

**Other Required Information:**
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome
 - Version: 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
This issue was not found on Safari, Firefox. I could not check on Windows platform. So, it might be a browser-specific and/or platform specific bug

**Comment by nevnein** [comment]
This looks related to a rather old but well-known bug regarding transform transitions ignoring overflow: hidden from border-radius on webkit browsers, see:
[Transition on transform with border radius and overflow hidden doesn't work in Safari](https://stackoverflow.com/q/25891362)
[overflow:hidden ignored with border-radius and CSS transforms (webkit only)](https://stackoverflow.com/q/16878279)

To my knowledge it has been fixed for transitions on transforms, I guess that's not the case for filters though.

The old fix, using `-webkit-mask-image: -webkit-radial-gradient(white, black);` on the parent element, is rather hacky but works like a charm. You can try it by adding it to the `a.avatar` element.

As I said it's kinda hacky but it is the only solution that I know of that doesn't require design changes (removing the filter on the image), if it's approved I can open a PR.

**Comment by nevnein** [comment]
Oh I see there's already a PR, nevermind :)
