### ISSUE TITLE
Autocomplete - Comportamento differente tra Chrome e FF

### ISSUE THREAD

**Issue by gdmodellismo** [italia/bootstrap-italia#413]
Salve, 

volevo segnalare un comportamento differente per il componente Autocomplete tra Chrome e Firefox. Me ne sono accorto testando un sezione di un sito che sto sviluppando in Orchard CMS, all'inizio pensavo di non aver correttamente importato tutto il template, ma poi andando direttamente sul Bootstrap Italia su questa URL

https://italia.github.io/bootstrap-italia/docs/form/input/#autocomplete-grande

Mi sono accorto che su Chrome compilando il campo a dx compare l'icona che consente di cancellare il contenuto

Su Firefox questa icona non compare

Volevo solo segnalarvelo,

grazie

**Comment by francescozaia** [comment]
Grazie @gdmodellismo hai fatto bene, ci guardiamo appena possibile.

**Comment by astagi** [comment]
Grazie @gdmodellismo purtroppo il type="search" ha comportamenti diversi tra i browser che implementano webkit e firefox.
