### ISSUE TITLE
xlink:href deprecated

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia#418]
## Comportamento atteso

L'attributo "xlink:href" è stato deprecato in favore di "href"
[https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs](https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs)
La raccomandazione è ancora in bozza

## Comportamento attuale

[https://italia.github.io/bootstrap-italia/docs/utilities/icone/](https://italia.github.io/bootstrap-italia/docs/utilities/icone/)

## Possibili soluzioni

Secondo la bozza bisogna lasciare l'attributo "xlink:href" per retrocompatibilità e aggiungere "href".
Qui un report sulle linee di codice interessate [http://arturu.it/test-bi/report-xlink.txt](http://arturu.it/test-bi/report-xlink.txt)

**Comment by arturu** [comment]
Mozilla da `xlink:href` come morto, consiglia di aggiungere `href` https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

**Comment by gpeirolo** [comment]
@astagi le best practices suggeriscono di mantenere entrambi gli attributi `xlink:href` e `href`. Implementare i due attributi su tutti gli esempi di BI è abbastanza oneroso in termini di effort e forse anche un po' confusionario. Può avere senso usare `href `per gli esempi e nella pagina dedicata alle icone evidenziare il problema retrocompatibilità e l'uso di `xlink:href` con un callout? Oppure li inseriamo ovunque per evitare problemi quando si fa copia/incolla del codice?

**Comment by astagi** [comment]
@gpeirolo con una regexp potrei inserire entrambi gli attributi, nessun problema per quello però si, di fatto resterebbe molto confusionario.. agirei così se può tornare:

1. Utilizziamo per tutti gli esempi solo href
2. Specifichiamo nella parte iniziale l'utilizzo di xlink:href
3. Facciamo vedere xlink:href e href utilizzati insieme solo nel primo esempio

**Comment by gpeirolo** [comment]
@astagi ottimo, era esattamente quello che volevo fare.

**Comment by astagi** [comment]
Perfetto :)
