### ISSUE TITLE
Cannot use notificationShow() with webback generated app.js

### ISSUE THREAD

**Issue by robertogallea** [italia/bootstrap-italia#420]
## Comportamento atteso
Importando gli script del template mediante webpack, risulta impossibile usare funzioni, come ad esempio `notificationShow()`

## Comportamento attuale
la funzione non viene trovata nonostante sia presente all'interno del file app.js prodotto (probabilmente perchè non esportata)
```
Uncaught ReferenceError: notificationShow is not defined
    at HTMLDocument.<anonymous> ((index):467)
    at mightThrow (app.js:6285)
    at process (app.js:6353)
```

## Possibili soluzioni
Il comportamento è corretto in quanto la funzione non è esportata o sbaglio qualcosa io?

**Comment by lscorcia** [comment]
Se stai utilizzando la versione non-bundle della libreria, dai una occhiata alla issue #433 , probabilmente stiamo parlando dello stesso problema.

**Comment by francescozaia** [comment]
Potrebbe essere sistemato nella versione 1.3.10, anche se non ho avuto modo di verificarlo. Grazie a @lscorcia!
