### ISSUE TITLE
Validazione dei campi errata

### ISSUE THREAD

**Issue by jdeyla** [italia/bootstrap-italia#422]
Prendendo come esempio
https://italia.github.io/bootstrap-italia/docs/form/introduzione/?#stili-personalizzati

Le istruzioni sono errate, perchè premendo inviao, il form non viene spedito. 

## Comportamento atteso
I campi validi dovrebbero avere un segno di spunta verde a lato, rosso quelli invalidi. 
La verifica lato client dovrebbe anche tenere conto del valore o del formato di input o non sovrascrivere l'eventuale risultato (e modifica dell'aspetto/classe) fornito lato server.

## Comportamento attuale
La verifica avviene solo sul riempimento dei campi richiesti: in caso di dati non valid.
Abbiamo provato ad implementarlo, usando un form in postback, ma lo script di validazione agisce successivamente, e quindi a campi segnalati come errati, ha comunque associato l'icona verde.

e' un problema di usabilità o il campo è errato - X rossa (perchè contiene un dato errato o non è compilato, è lo stesso) o è corretto - spunta verde

**Comment by arturu** [comment]
Mi sa che anche io ho lo stesso problema, la validazione lato server viene sovrascritta. Lo script considera un campo valido o meno solo se è stato compilato e interviene anche se ci sono altri JS di validazione.

Ho riprodotto la problematica qua [https://drupal-bootstrap-italia.arturu.it/it/form/test-422](https://drupal-bootstrap-italia.arturu.it/it/form/test-422) , è evidente nel campo "Nome" e "Telefono".
N.B. Per la select non la tenete in considerazione, penso sia un mio problema, la devo ancora sistemare.

![Validazione_BI](https://user-images.githubusercontent.com/4628942/71517171-285f2a00-28ad-11ea-91e4-0e2c5c9030aa.png)

**Comment by arturu** [comment]
Un altro caso in cui il testo "Validato!" può essere fuorviante è nelle form di login o registrazione. Magari si potrebbe sostituire "Validato!" con un altro termine che fa intendere che un campo obbligatorio è stato compilato ma che non è ancora validato?

[https://drupal-bootstrap-italia.arturu.it/it/user/login](https://drupal-bootstrap-italia.arturu.it/it/user/login)

![login-422a](https://user-images.githubusercontent.com/4628942/71518174-df5da480-28b1-11ea-82c3-36ace0bb7499.png)

![login-422-b](https://user-images.githubusercontent.com/4628942/71518177-e4baef00-28b1-11ea-952e-6ed2b06542ce.png)

**Comment by francescozaia** [comment]
Per quanto riguarda eventuali collisioni tra il JS di Bootstrap Italia con validazioni server side dovremmo guardarci (al momento abbiamo carenza di risorse da dedicare al progetto), però volevo solo segnalare che il testo associato alla validazione (il `"Validato!"`) si può personalizzare senza problemi nell'html attraverso un div con classe `valid-feedback` (https://italia.github.io/bootstrap-italia/docs/form/introduzione/?#stili-personalizzati).

**Comment by arturu** [comment]
Mi sa che nel caso specifico di "Validato!" abbiamo interpretato la documentazione un po' troppo alla lettera. :)

**Comment by manica** [comment]
esiste un esempio di validazione di un campo select ?

**Comment by agrigio** [comment]
a me la validazione su campo select non funziona, anzi risulta fuorviante per gli utenti perchè non fornisce alcun feedback

**Comment by astagi** [comment]
@jdeyla @arturu @agrigio riscontrate il problema anche nell'ultima versione? c'è un nuovo plugin di validazione, [qua la demo](https://italia.github.io/bootstrap-italia/docs/esempi/form/)

**Comment by arturu** [comment]
@astagi Woow, Ottimo, molte sembra molto più pulito così https://bootstrap-italia.arturu.it/form/example-style-guide
