### ISSUE TITLE
nested linked lists

### ISSUE THREAD

**Issue by pdipietro** [italia/bootstrap-italia#424]
## Comportamento atteso

Vorrei creare delle liste di link **ricorsive** (nell'ambito di un link-list-wrapper)
Voglio costruire delle ```<li>``` ciascuna delle quali abbia un testo seguito da un'icona a destra, in modo tale da avere due tag ```<a>```:

- un primo tag ```<a>``` contenente il testo associato  ed un link specifico che invii ad uno specifico indirizzo
- un secondo tag ```<a>``` contenente l'icona, che funga da toggle per visualizzare/nascondere i contenuti

## Comportamento attuale

se si mette più di un ```<a>``` tag sulla stessa riga, il contenuto va a capo

PS: per accedere allo slack, mi viene richiesto un indirizzo email nel dominio developers-italia o agid: come è possibile contattarvi senza tale email?

**Comment by arturu** [comment]
Se non ho capito male intendi così?

https://jsfiddle.net/arturu/w7j3z95y/3/
