### ISSUE TITLE
I form nella modale non vengono visualizzati correttamente

### ISSUE THREAD

**Issue by landerover** [italia/bootstrap-italia#429]
come descritto già nel titolo della issue, le label dei form non vengono visualizzate correttamente, allego screenshot.
Non so perchè ma solo nella modale da questo problema, al caricamento della pagina viene impostato un css inline "width: 0px;", ho sostituito tutti gli "0px" presenti nel vostro js con un numero a piacere (giusto per fare una diagnosi velocissima), ma il risultato non cambia.

Per raggirare il problema ho fatto un piccolo workaround che incollo qui, è una piccola porcheria perciò non propongo pull request:

```
<script>
  $( document ).ready(function() {
      $('#IDMODALE').on('show.bs.modal', function () {
          $('.form-group label').css({'width': "auto"});
      })
  });
</script>
```

![bootstrap-italia-bug](https://user-images.githubusercontent.com/14308209/73695741-03937900-46db-11ea-8037-da034a66fd4f.png)

**Comment by brainssolutions** [comment]
Sto riscontrando lo stesso problema. Inoltre ho notato che mettendo un input di tipo file con la classe upload questo va a finire all'interno del footer del modale e non segue i form-row.

**Comment by brainssolutions** [comment]
Hai provato ad utilizzare :

`<div class="form-row">
          <div class="form-group col-12">
            <label for="nome">Nome Documento</label>
            <input type="text" class="form-control" id="nome" placeholder="Autocertificazione">
          </div>
          </div>`

Perchè ho provato ma a me non dà quel difetto.

**Comment by manica** [comment]
Ottengo lo stesso comportamento all'interno di un collapse

<div id="collapseDiv1" class="collapse-div" role="tablist">
			<div class="collapse-header" id="heading1">
				<button data-toggle="collapse" data-target="#collapse1"
					aria-expanded="false" aria-controls="collapse1">Inserisci nuova
					Anagrafica</button>
			</div>
			<div id="collapse1" class="collapse " role="tabpanel"
				aria-labelledby="heading1">
				<div class="collapse-body">
					<form class="form-horizontal" role="form" id="aggiungi"
						name="aggiungi" action="index.php" method="get">
					<div>
  						<div class="form-row">
    						<div class="form-group col-6">
								<input type="text" class="form-control" id="anome" name="anome">
								<label for="anome">Nome</label>
							</div>
						</div>
						<button class="btn btn-sm btn-primary" name="aggiungi"
							value="aggiungi" type="submit">Inserisci</button>
					</form>
				</div>
			</div>
		</div>

**Comment by riccardomarcigliano** [comment]
I form sia in modale che in collapse non vengono visualizzati correttamente perchè la width della label viene calcolata prima che sia finito l'effetto di comparsa (collapse o show). Impostare una min-width potrebbe risolvere?

**Comment by engineering87** [comment]
Un possibile fix, come riportato nella issue [https://github.com/italia/bootstrap-italia/issues/450](url) è la seguente:

`$(document).ready(function () { $("label").map(function () { $(this).css("width", "auto"); }).get(); });`
