### ISSUE TITLE
Dropdown e icone associate agli elementi

### ISSUE THREAD

**Issue by lscorcia** [italia/bootstrap-italia#435]
## Comportamento atteso
Buongiorno, sto cercando di implementare nella mia header una dropdown per gestire il menu di login dell'utente corrente. L'ideale sarebbe avere una dropdown con questo aspetto (immagine presa da internet per il momento):

![immagine](https://user-images.githubusercontent.com/16761934/76460902-2ce0ac80-63df-11ea-9679-f8630acb1ff2.png)

Ovvero con icona associata a ciascun elemento + una icona associata al trigger, oltre ovviamente al simbolo di dropdown a destra.

## Comportamento attuale
Il problema che sto riscontrando è che utilizzando le classi dropdown e le icone SVG di bootstrap italia, all'apertura della dropdown viene ribaltato il simbolo di dropdown, ma anche l'icona:

![immagine](https://user-images.githubusercontent.com/16761934/76461100-8943cc00-63df-11ea-989f-f5cd135ee198.png)

![immagine](https://user-images.githubusercontent.com/16761934/76461107-8fd24380-63df-11ea-9a32-1fdf1d18f828.png)

Sono nuovo all'uso di bootstrap quindi è possibile che il problema sia dovuto al fatto che non conosco le classi da utilizzare. Avete idee in merito?

**Comment by lscorcia** [comment]
Uhm. Guardando il codice in `_headerslim.scss`, più che a un mio errore il problema sembra più dovuto all'utilizzo del nome `icon` per la classe che definisce il simbolo di dropdown. Probabilmente sarebbe più sensato usare un nome diverso, ad es. `icon-expand`, in modo da poter avere all'interno dell'header slim entrambi gli elementi. Stessa cosa probabilmente anche nel megamenu.

Posso fornire una pull request per questa modifica, ma sarebbe una breaking change. Resto aperto ad altre soluzioni se ce ne sono...

**Comment by francescozaia** [comment]
Ciao, tutto corretto, purtroppo è un caso d'uso che non era previsto. Dovremmo quindi vedere un attimo più nel dettaglio per evitare breaking change. Per ora, nel tuo caso specifico magari puoi evitare di usare la classe `.icon` per la tua icona impostando le dimensioni ad-hoc per le bandierine.
Nel frattempo vediamo di trovare una soluzione, magari usando un selettore `+` o simile.
