### ISSUE TITLE
Thumbnav non funziona su Firefox

### ISSUE THREAD

**Issue by dej611** [italia/bootstrap-italia#436]
## Comportamento atteso
La documentazione BI, su Firefox, per il componente Thumbnav dovrebbe essere identica alla versione Chrome, di seguito riportata:

<img width="933" alt="Screenshot 2020-03-12 at 09 57 03" src="https://user-images.githubusercontent.com/924948/76504430-fdb25580-6447-11ea-9a21-66e798a8d410.png">

## Comportamento attuale
Su Firefox (73.0.1 su MacOS 10.15.3) il box con l'esempio del componente è vuoto:

<img width="941" alt="Screenshot 2020-03-12 at 09 57 14" src="https://user-images.githubusercontent.com/924948/76504483-17539d00-6448-11ea-81a0-4b3bc26ad8cf.png">

Questo vale per tutti gli esempio nella pagina.

**Comment by francescozaia** [comment]
Grazie @dej611, da un rapido debug da console mi pare che il problema sia nel sizing dei `li`: aggiungendo `.thumb-nav li {width: 100%;}` torna a funzionare. Ovviamente va capito perché e sistemato a dovere.

**Comment by astagi** [comment]
@dej611 non sembra essere riproducibile sulle ultime versioni di Firefox, chiudo. Grazie della segnalazione!
