### ISSUE TITLE
I colori custom non sovrascrivono correttamente

### ISSUE THREAD

**Issue by giuliolastra** [italia/bootstrap-italia#441]
Salve,
ho notato che la gestione dei colori custom, o aggiuntivi, non è del tutto funzionante, in particolare, vengono spesso sovrascritti dai colori base (credo debba essere il contrario). Do una breve spiegazione qui di seguito. Credo sia "facilmente" risolvibile posizionando degli important, come fa già bootstrap per le sue colorazioni, in modo da far correttamente sovrascrivere i colori

## Comportamento atteso

`<a href="#" class="btn analogue-2-bg analogue-2-border-color">
    <span>Cyan</span>
</a>` Dovrebbe mostrare un pulsante in colore analogo, che di default dovrebbe essere ciano

Si dovrebbero aggiungere degli !important nei colori che vengono generati, sia per il background, che per il color, che per il border color, come fa già bootstrap nei suoi colori default

## Comportamento attuale

Il pulsante viene mostrato nel suo colore default, che se non specificato è bianco

**Comment by francescozaia** [comment]
Correlato a #516
