### ISSUE TITLE
aggiornare bootstrap alla versione 4.4

### ISSUE THREAD

**Issue by astalegale** [italia/bootstrap-italia#442]
Salve,

sarebbe possibile aggiornare possibile aggiornare bootstrap alla versione 4.4?
tra le varie cose introduce i container con breakpoints: https://getbootstrap.com/docs/4.4/layout/overview/#responsive

Grazie

**Comment by francescozaia** [comment]
Salve,

L'aggiornamento alla versione più recente di Bootstrap è già pianificato, purtroppo al momento siamo un po' a corto di risorse, speriamo la situazione migliori al più presto.
Ti tengo aggiornato qui. Un saluto.

**Comment by astalegale** [comment]
> Salve,
> 
> L'aggiornamento alla versione più recente di Bootstrap è già pianificato, purtroppo al momento siamo un po' a corto di risorse, speriamo la situazione migliori al più presto.
> Ti tengo aggiornato qui. Un saluto.

Perfetto grazie

**Comment by francescozaia** [comment]
Abbiamo aggiornato la libreria a jQuery 1.5 e Bootstrap 4.5 ([qui](https://github.com/italia/bootstrap-italia/releases/tag/v1.4.0) le note di release).
