### ISSUE TITLE
Bug su liste di immagini Masonry in Safari

### ISSUE THREAD

**Issue by ilariopromutico** [italia/bootstrap-italia#453]
## Comportamento atteso
Le liste di immagini con stile Masonry non vengono visualizzate correttamente dal browser Safari (iOS/MacOs), mentre non si riscontra nessun problema con altri browser. 

## Comportamento attuale
Per verificare l'errore, basta visualizzare la pagina della documentazione ufficiale di Bootstrap Italia con Safari: [https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/liste-di-immagini/#masonry](https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/liste-di-immagini/#masonry
)

Grazie del supporto

**Comment by ilariopromutico** [comment]
Non c'è alcuna novità riguardo questo problema?

**Comment by astagi** [comment]
@ilariopromutico anch'io lo vedo leggermente sfalsato il secondo elemento

![image](https://user-images.githubusercontent.com/537363/150538695-0f5aca40-261b-4ef2-a1f2-c4078333d9e3.png)

confermi la stessa cosa anche su iOS sempre con le nuove versioni di Safari?
