### ISSUE TITLE
Npm audit vulnerabilità 

### ISSUE THREAD

**Issue by umberto12345** [italia/bootstrap-italia#456]
## Comportamento atteso

Nessuna vulnerabilità alta

## Comportamento attuale

Lanciando npm i nell'ultima versione della  soluzione (1.4.0) otteniamo 4 vulnerabilità basse e 1 alta.
Vorrei sapere se possiamo usare in sicurezza  in produzione la vostra libreria.
Sembrerebbe che browsersync sia la causa poichè non aggiornato nel lock.

## Possibili soluzioni

Aggiornare il package-lock.json

**Comment by francescozaia** [comment]
Esatto, purtroppo la issue dipende da https://github.com/BrowserSync/browser-sync/issues/1764 che non è nelle nostre possibilità sistemare, ma ti confermo che si tratta soltanto di un tool necessario allo sviluppo e non ha alcun impatto nella versione di produzione della libreria (quella scaricabile ad esempio da [qui](https://github.com/italia/bootstrap-italia/releases/tag/v1.4.0)).
Lascio aperta la issue finché non risolta.
