### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by p4trizio** [italia/bootstrap-italia#457]
## Comportamento atteso

Utilizzando jQuery.noConflict() e importando la libreria bootstrap-italia non dovrebbero esserci errori sulla console.

## Comportamento attuale
Sul file ./node_modules/bootstrap-italia/src/js/plugins/password-strength-meter/password-strength-meter.js si presenta l'errore "$ is not a function", come da codice seguente

`$(function() {
  var isShiftPressed = false
  var isCapsOn = null
  $('.input-password')
    .on('keydown', function(e) {
      var keyCode = e.keyCode ? e.keyCode : e.which
      if (keyCode == 16) {
        isShiftPressed = true
      }
    }) ....`

## Possibili soluzioni
Eseguire un refactor della suddetta funzione

## Contesto
Utilizzo della libreria bootstrap-italia su un tema custom Drupal9. 
Drupal implementa sempre un file js con l'attivazione di jQuery.noConflic()

**Comment by francescozaia** [comment]
Aggiungo che, oltre a `password-strength-meter.js` ci sono anche altre librerie di cui gestire correttamente l'alias.
Sarebbe anche bello usare dipendenze npm per queste librerie.
