### ISSUE TITLE
Mostra Titolo del sito e motto: il checkbox del customizer non ha effetto, #bug, risolto

### ISSUE THREAD

**Issue by luca-b-avng** [italia/bootstrap-italia#458]
## Comportamento atteso

Personalizza Tema, sezione "Denominazione del sito", checkbox "Mostra il titolo del sito e il motto":
a seconda che il checkbox sia marcato o meno Titolo e Motto dovrebbero apparire nella testata oppure non apparire.

## Comportamento attuale

Titolo e Motto appaiono sempre nella testata, indipendentemente dall'impostazione del checkbox

## Possibili soluzioni

nel file header.php il div che contiene Titolo e Motto va inserito in un if come segue

```
<?php if ( get_theme_mod( 'header_textcolor' ) != 'blank' ) { ?>
    <div class="it-brand-text">
        <h2 class="no_toc"><?php echo esc_html( get_bloginfo( 'name' ) ); ?></h2>`
        <h3 class="no_toc d-none d-md-block"><?php bloginfo( 'description' ); ?></h3>`
    </div>
<?php } ?>
```

(`<div class="it-brand-text">` dovrebbe trovarsi alla riga 48 di header.php).

purtroppo l'identificatore (non l'id!) del controllo ha un nome poco intuitivo (`header_textcolor`), mentre l'id si chiama, giustamente, `_customize-input-display_header_text`.

![temp](https://user-images.githubusercontent.com/67027634/87414481-28661380-c5cc-11ea-860b-cef4e63da7f0.jpg)

anche per il valore del controllo ha un comportamento un po' strano: se il checkbox **NON è marcato**, il valore restituito è `string(5) "blank"`, se il checkbox **E' marcato** il valore restituito è una stringa vuota, `string(0) ""`.

purtroppo entrambi gli aspetti mi pare dipendano da codice core WordPress.

**Comment by francescozaia** [comment]
Ciao @luca-b-avng questo è il repo della libreria Bootstrap Italia, non capisco a cosa fai riferimento perché parli di WordPress. Ci puoi dare una mano a capire quando avviene il problema?
