### ISSUE TITLE
Documentazione upload-dragdrop

### ISSUE THREAD

**Issue by vittore** [italia/bootstrap-italia#459]
Salve,

esiste un esempio di codice js per https://italia.github.io/bootstrap-italia/docs/form/upload/#upload-dragdrop in cui si vede l'invio della form?

Grazie.
V.

**Comment by arche94** [comment]
Mi accodo alla richiesta: dalla documentazione non è molto chiaro l'impiego in un caso reale, oltretutto non capisco se è un'estensione di un plugin/widget o è un componente proprio di Bootstrap Italia, non mi sembra che venga dal Bootstrap di base, non ho trovato nulla a riguardo.
Si potrebbe avere un esempio di applicazione reale o, in caso estenda un altro widget, qualche link alla documentazione originaria?

Grazie,
Paolo

**Comment by astagi** [comment]
@vittore @arche94 questa issue è un po' vecchiotta, non so se nel frattempo avete sviluppato un esempio di codice funzionante all'interno dei vostri progetti, nel caso sarebbe interessante includerlo nella documentazione. Grazie!
