### ISSUE TITLE
Refuso CSS

### ISSUE THREAD

**Issue by fabiodaniele** [italia/bootstrap-italia#461]
Ciao a tutti,
ho scaricato la versione corrente (1.4.0) del tema per provare a utilizzarlo in un'applicazione Angular, ma quando ho compilato il progetto, ho avuto evidenza di un problema relativo al CSS, in particolare con un'immagine SVG.

Andando a guardare nel file
**bootstrap-italia.min.css**
ho notato che l'URL dell'immagine in questione contiene un errore:

`.navbar-dark .navbar-toggler-icon{background-image:url(ata:image/svg+xml`

C'è scritto "ata" anziché "data".

Correggendo l'errore "a manina" :) compila :)

Spero di essere stato utile!

Un saluto,
FD

**Comment by francescozaia** [comment]
Grazie @fabiodaniele!
Cosa curiosa in effetti, verifichiamo (il [codice sorgente](https://github.com/italia/bootstrap-italia/blob/master/src/scss/_variables.scss#L48) sembra ok a prima vista, chissà).

**Comment by francescozaia** [comment]
Sistemato nella v1.4.1 👌 grazie ancora

**Comment by fabiodaniele** [comment]
Di niente! :)
