### ISSUE TITLE
Con Firefox non è possibile inserire il separatore dei decimali in un input numerico

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia#464]
## Comportamento atteso

Utilizzando Firefox dovrei riuscire ad inserire un numero decimale in un input numerico.

## Comportamento attuale

Il separatore dei decimali viene cancellato in automatico

## Contesto

Per riprodurre il problema bisogna visitare questa pagina https://italia.github.io/bootstrap-italia/docs/form/input-numerico/#valuta  usando Firefox (78 o 79 su Linux, Android o Windows), cancellare il contenuto del campo e provare a scrivere un numero con delle cifre decimali.
Il problema non si presenta con Chromium e Chrome.

**Comment by bunglegrind** [comment]
Non è proprio così: se vuoi inserirli devi prima digitare i decimali, poi torni indietro e inserisci la virgola...

Il problema è probabilmente causato da un bug di firefox su input di tipo numerico

https://bugzilla.mozilla.org/show_bug.cgi?id=1398528

Non mi sono chiari alcuni meccanismi interni, ma non sono sicuro che l'evento keyup sia quello corretto. Il punto è che questa patch per internet explorer è eseguita su tutti i browser (andrebbe anche corretta l'espressione regolare, che permette di avere più virgole nello stesso numero). 

Mi sto riferendo a input-number.js riga 105 e successive. 
https://github.com/italia/bootstrap-italia/blob/dd0a1d91b805a6719129ed4dd514ae7bc633a39e/src/js/plugins/input-number.js#L105

Se posso dare un consiglio di stile, dovreste sempre mettere i punto e virgola al termine delle righe, senza può creare problemi al parser del browser.

**Comment by bunglegrind** [comment]
Una possibile soluzione potrebbe essere quella di mettersi sull'evento keydown e validare il carattere appena digitato sulla base di una whitelist (o blacklist) e se nel campo è già presente una virgola

**Comment by arturu** [comment]
Ho notato che impostando gli step per parti di intero e utilizzando gli steppers è possibile inserire il numero decimale. Il problema si presenta solo con input da tastiera.
