### ISSUE TITLE
Le immagini del componente thumbnav non sono visibili quando si utilizza Firefox

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia#465]
## Comportamento atteso

Dovrei poter vedere le immagini dei primi capitoli.

## Comportamento attuale

In questa pagina https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/thumbnav/ le immagini dei primi capitoli non sono visibili (tutte le svg praticamente).

## Contesto

Visitando la pagina https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/thumbnav/ usando Firefox (78 o 79 su Linux, Android o Windows).
Il problema non si presenta con Chromium e Chrome.

**Comment by ffranchina** [comment]
Buonasera a tutti! Ho appena fatto una PR che risolve il problema.
Praticamente il tutto si verificava a causa di un'inconsistenza nelle dimensioni dei vari elementi. Ho spostato e sistemato il codice in modo che tutti i browser riescano a calcolare correttamente le dimensioni necessarie.
Fatemi sapere se avete commenti :)
