### ISSUE TITLE
[icon request] RSS feed (edit: icon requests bucket)

### ISSUE THREAD

**Issue by bfabio** [italia/bootstrap-italia#472]
It would be nice to have an [RSS feed icon](https://www.google.com/search?q=rss+feed+icon).

**Comment by francescozaia** [comment]
There's also few icons for Developers Italia website, as requested by @libremente on https://github.com/italia/developers.italia.it/issues/671

**Comment by francescozaia** [comment]
SVGs have been done, I just need to add them to the library

**Comment by libremente** [comment]
> SVGs have been done, I just need to add them to the library

Hi @francescozaia, awesome! Any update on this side? cc @emilioSp

**Comment by francescozaia** [comment]
New icons added in v1.4.2:


- it-open-source
- it-piattaforme
- it-rss.svg
- it-rss-square
- it-software
- it-telegram
