### ISSUE TITLE
Var $link-color not !default

### ISSUE THREAD

**Issue by riccardomarcigliano** [italia/bootstrap-italia#474]
## Comportamento atteso
Possibilità di effettuare override della variabile $link-color con associazione diretta ad altra variabile

## Comportamento attuale
La variabile $link-color è associata alla variabile $primary senza !default e di conseguenza non ne permette un override semplice.
Comprendo la scelta logica di unificare le azioni principali (link e bottoni) allo stesso colore, ma nel primo caso siamo in presenza di una applicazione su font mentre nel secondo su background; è possibile che esistano brandbook o palette che richiedano di aggiungere questa possibilità.

## Possibili soluzioni
Aggiunta di !default alla variabile $link-color

**Comment by PiemP** [comment]
é possibile aggiungere `!default` anche alle varianti cromatiche del colore di base? Perchè vengono utilizzati per definire i colori di background di alcuni elementi del layout *(es. $primary-a6, $primary-a7 e $primary-a10)* e potrebbe consentire una maggiore personalizzazione delle interfacce.

Grazie.

**Comment by giuliaghisini** [comment]
sono d'accordo con tutte queste richieste.. diventa molto laborioso personalizzare i colori, soprattutto se le varianti a1,a2 ecc non superano i requisiti per il contrasto

**Comment by PiemP** [comment]
Buongiorno a tutti, 

io sono a disposizione eventualmente per realizzare un PR che vada a risolvere questa situazione che sembra interessare alcuni utenti oltre al fatto che va a generare, in alcune circostanze, anomalie di accessibilità a causa del basso livello di contrasto dei colori. Ovviamente se sono tutti d'accordo col fatto di aggiungere `!default` anche sulle altre variazioni di colore.

La cosa che mi blocca un pò è il fatto che ho un altro PR aperto e vedo che è ancora fermo (#482).

Grazie.

**Comment by francescozaia** [comment]
Ciao @PiemP il lavoro sulla libreria dovrebbe riprendere entro l'anno 🤞 Di più non so dirti.
