### ISSUE TITLE
Hamburger menu per megamenu sopra i 992px

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [italia/bootstrap-italia#478]
## Comportamento atteso
Sto cercando di realizzare un megamenu che mostri hamburger button a tutte le dimensioni del viewport.
Per dispositivi larghi meno di 992px il comportamento è già corretto:
![image](https://user-images.githubusercontent.com/19283945/93605616-45053a00-f9c7-11ea-8cd7-d49fd85f16f8.png)
La motivazione è un menu di navigazione molto ampio e profondo, con troppe voci per essere mostrato bene anche a schermo intero.

## Comportamento attuale
Per schermi/finestre più larghe di 992px, ho provato a sovrascrivere, nel mio css aggiuntivo le classi css corrispondenti a quella funzionalità.
Purtroppo in _navigation.scss ci sono queste due linee https://github.com/italia/bootstrap-italia/blob/dd0a1d91b805a6719129ed4dd514ae7bc633a39e/src/scss/custom/_navigation.scss#L307 e https://github.com/italia/bootstrap-italia/blob/dd0a1d91b805a6719129ed4dd514ae7bc633a39e/src/scss/custom/_navigation.scss#L311

che mi vanno ad inibire la possibilità di usare le stesse classi allo stesso modo per avere il meno che appare da lato.

## Possibili soluzioni
Una soluzione che ho al momento è di cambiare quelle due linee per rimuovere `!important`. Questo però vorrebbe dire mantenermi io una mia versione modificata.

Quale è il ragionamento che ha portato ad inibire questi comportamenti del menu di navigazione?

**Comment by francescozaia** [comment]
Si preferisce dare evidenza alle voci di menu ove possibile (su schermi grandi).
