### ISSUE TITLE
Problema Select con live-search su IE

### ISSUE THREAD

**Issue by engineering87** [italia/bootstrap-italia#479]
## Comportamento atteso
Il componente **select** con la ricerca _data-live-search_ attiva presenta dei problemi di selezione su IE.
Il componente dovrebbe permettere la selezione di un qualsiasi elemento anche navigandolo tramite mouse scroll.

## Comportamento attuale
Provando a selezionare un elemento nascosto, ad esempio uno degli ultimi elementi della lista, la select si chiude preventivamente senza terminare correttamente la selezione e lasciando il precedente elemento selezionato. Questo comportamento si ottiene scrollando la select senza cliccare escplitamente sulla scrollbar verticale (utilizzando la scroll wheel del mouse).
Sembrerebbe quindi un problema di focus.

## Possibili soluzioni
Disabilitare la live search del componente.

## Contesto
Il bug viene riscontrato solo su browser IE (testata versione 11)

**Comment by astagi** [comment]
@engineering87  il componente con ricerca è deprecato, prova ad utilizzare l'autocomplete integrato nelle ultime versioni
