### ISSUE TITLE
La regola row.row-full-width crea uno scorrimento orizzontale

### ISSUE THREAD

**Issue by akamizi** [italia/bootstrap-italia#490]
Riferimento: https://italia.github.io/design-comuni-prototipi/esempi/bootstrap-italia/template-novita-notizia.html

## Comportamento atteso
Non dovrebbe esserci scrolling orizzontale della pagina

## Comportamento attuale
La pagina ha uno scrolling orizzontale

## Possibili soluzioni
modificare la regola da
`row.row-full-width {
    max-width: calc(100vw);
    margin: 0 calc(-50vw + 50%);
}`
a
`row.row-full-width {
    max-width: calc(100vw - 6px);
    margin: 0 calc(-50vw + 50%);
}`

## Contesto
verificato su Firefox e Chrome

**Comment by akamizi** [comment]
si ringrazia @arturu per la collaborazione a trovare il fix proposto

**Comment by arturu** [comment]
Facendo un po' di test e rifinendo meglio le ipotesi, `max-width: calc(100vw - 6px);` funziona meglio su tutti i breakpoint.
Scusa @akamizi per la risposta veloce di PM :)

**Comment by gpeirolo** [comment]
@astagi @Fupete analizzando il bug non esiste una soluzione CSS che funzioni su tutti i browser. Il valore `vw` non tiene conto della larghezza della scrollbar che varia a seconda dell'os/browser.
Una soluzione più compatibile consiste nel modificare l'HTML di quella pagina usando un `container-fluid` per la zona contenente l'immagine full-width e modificare il CSS custom di `.row-full-width` per mantenere questo layout (utilizzato solo su due pagine dei template dei comuni e non presente in Bootstrap Italia).
