### ISSUE TITLE
la classe .no_toc non esiste

### ISSUE THREAD

**Issue by DavideVitali** [italia/bootstrap-italia#495]
Buongiorno!

## Comportamento atteso
Ho appena scaricato la libreria e la sto sperimentando. Devo creare una sidebar e sto utilizzando, come specificato sulla [documentazione](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/sidebar/), le classi `.sidebar-wrapper`, `.sidebar-linklist-wrapper` e `.link-list`. Partendo da una lista basica, la documentazione consiglia una cosa del genere:

![image](https://user-images.githubusercontent.com/28304740/97561979-3efc7300-19e1-11eb-8a85-c5a20c5b0d7c.png)

Tuttavia, la classe `.no_toc` (che, da quanto intuisco, servirebbe per non mostrare il pallino della lista) sembra non esistere, e il pallino viene comunque mostrato.

## Contesto
Sto usando l'ultima versione disponibile: 1.4.1.

**Comment by francescozaia** [comment]
Sarebbe da rimuovere `no_toc` dall'html poiché la classe non fa parte di Bootstrap Italia, e verificare perché e dove viene mostrato il pallino (su Chrome sembra ok)
