### ISSUE TITLE
Font da CDN

### ISSUE THREAD

**Issue by MucaInera** [italia/bootstrap-italia#497]
## Info

È possibile deprecare il file fonts-loader.js e lasciare la libertà di caricare i font da una fonte a scelta?

**Comment by francescozaia** [comment]
Alcune scelte della libreria (come i font usati) sono state fatte espressamente per dare coerenza tra i siti della Pubblica Amministrazione. Inoltre, il caricamento di font da una CDN pone potenziali temi di privacy.
