### ISSUE TITLE
Campi di input e select non visualizzati correttamente con utilizzo di Partial Rendering mediante ajax

### ISSUE THREAD

**Issue by nicolaceliento** [italia/bootstrap-italia#498]
## Comportamento atteso
Campi di input e select visualizzati come da [Esempio Input](https://italia.github.io/bootstrap-italia/docs/form/input/) ed [Esempio Select Classica](https://italia.github.io/bootstrap-italia/docs/form/select/#select-classica)
<img width="746" alt="Capture2" src="https://user-images.githubusercontent.com/34268041/98935745-442ee700-24e4-11eb-99d9-7d2448df8039.PNG">

## Comportamento attuale
Campi di input e select visualizzati senza stili Bootstrap Italia
<img width="582" alt="Capture" src="https://user-images.githubusercontent.com/34268041/98935651-1cd81a00-24e4-11eb-8bf1-624aa8f6c8cf.PNG">

## Possibili soluzioni
Rendere disponibile una function js da richiamare al completamento della chiamata ajax, che includa le operazioni fatte dal bootstrap-italia.min.js al Page Ready.

## Contesto
Applicazione MVC Razor con chiamate jQuery ajax verso Action/Controller che restituiscono l'HTML delle Partial View richieste. 
All'interno dell'html restituito dalle chiamate ajax sono presenti i campi di input e select con la struttura indicata negli esempi, ma non sono formattati con gli stili previsti.
Dal momento che il workaround di include del file risolve la issue, è possibile sapere se esiste un modo per chiamare le stessi function richiamate da bootstrap-italia.min.js al Page Ready?

**Comment by effedetto** [comment]
Ciao @nicolaceliento, 
se può serivre, io ho risolto richiamando all'interno del $( document ).ajaxComplete e $( document ).ajaxStop la funzione di refresh del selettore, in questo mdo
`// jQuery
function datepickerReload(){
  $('.it-date-datepicker').datepicker({
      inputFormat: ["dd/MM/yyyy"],
      outputFormat: 'dd/MM/yyyy',
    });
    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
});
    $(function () {
  $('.selectpicker').selectpicker("refresh")
});

}
function replaceItems (html) { 
    $('#items').replaceWith($(html));
	$( document ).ajaxComplete(function() {
 	 datepickerReload();
	});
	$( document ).ajaxStop(function() {
  	datepickerReload();
	});
}

$('button[name="addItem"]').click(function (event) {
    event.preventDefault();
    var data = $('form').serialize();
    // Add parameter "addItem" to POSTed form data. Button's name and value is
    // POSTed only when clicked. Since "event.preventDefault();" prevents from
    // actual clicking the button, following line will add parameter to form
    // data.
    data += '&addItem=true';
   $.post('<URLDAUTILIZZARE>', data, replaceItems );
  
    $('.it-date-datepicker').datepicker({
      inputFormat: ["dd/MM/yyyy"],
      outputFormat: 'dd/MM/yyyy',
    });
});
`
