### ISSUE TITLE
Evento di modifica pulsanti input numerico

### ISSUE THREAD

**Issue by dpaissan** [italia/bootstrap-italia#501]
## Comportamento atteso
Quando incremento il valore di un input numerico attraverso i suoi pulsanti, mi aspetto che venga generato un evento dal quale sia possibile leggere il valore attuale dell'input.

## Comportamento attuale
Ho bisogno di intercettare via Javascript una qualsiasi modifica ad un input numerico. Questo per modificare altri campi di conseguenza.

Lato input numerico non trovo alcun problema: basta intercettare l'evento "onkeyup" o "onkeydown" o "onchange" ecc.

Quando invece la modifica dell'input avviene attraverso i suoi pulsanti "su" e "giù" (quelli con classe "input-number-add" e "input-number-sub") non avviene alcun evento nell'input. Posso intercettare il click dei pulsanti ma quando viene intercettato l'eventi, il valore dell'input è quello precedente alla modifica e non il valore attuale.

Faccio un esempio per chiarezza:
Ho un input numerico con valore ad esempio "3" a cui è collegato l'evento "onkeyup". Ai pulsanti "su" e "giù" dell'input viene collegato l'evento "onclick".
Quando modifico il valore attraverso l'input e lo imposto ad esempio a "5" premendo un tasto della tastiera, l'evento "onkeyup" viene richiamato: se nella funzione dell'evento recupero il valore dell'input trovo "5".
Quando invece modifico il valore attraverso il pulsante "su" (incrementando quindi il valore da "3" a "4") l'evento "onclick" del pulsante viene intercettato correttamente ma nella funzione dell'evento se recupero il valore dell'input ottengo "3", ovvero quello precedente alla modifica.

**Comment by astagi** [comment]
@dpaissan il fix è pronto, adesso l'evento change sarà triggherato anche sulla pressione dei tasti step

```js
$("#inputNumber2").on("change", function(){
  console.log($(this).val());
});
```
