### ISSUE TITLE
SelectItem stile non inizializzato

### ISSUE THREAD

**Issue by alexucgit** [italia/bootstrap-italia#505]
## Comportamento atteso
Mi aspetto che lo stile della selectitem rimanga invariato 

## Comportamento attuale
Spesso non viene inizializzato, oppure navigando in altre pagine e tornando alla home si perde lo stile

## Contesto
Web app angular10

www.reportquotidiano.it Prima pagina con select. Provate ad andare sul secondo link, tornare sul primo e vedrete il problema

**Comment by Crow0197** [comment]
salve sto riscontrando al stessa problematica, lei come ha risolto ?

**Comment by astagi** [comment]
@alexucgit @Crow0197 il sito linkato non è raggiungibile, non riesco a riprodurre il problema, consiglio di provare ad aggiornare alle ultime versioni (1.6.x) e aprire una nuova segnalazione nel caso si riscontri il problema di nuovo.
