### ISSUE TITLE
Select popolata dinamicamente all'interno di una modal, renderizzata in parte al di fuori della finestra

### ISSUE THREAD

**Issue by Cholo981** [italia/bootstrap-italia#513]
## Comportamento atteso
Mi aspetterei di vedere l'elenco delle voci della select, renderizzate all'interno della finestra.
![image (1)](https://user-images.githubusercontent.com/22217538/107768530-e4401a80-6d36-11eb-909b-73770d272ced.png)

## Comportamento attuale
L'elenco della select viene ancorato sul lato inferiore, e buona parte di questa non è visibile. 
Se tolgo il wrapper della select, L'elenco - al di là dei problemi di styling - viene renderizzato correttamente, facendo pensare che il problema non sia ereditato da bootstrap:
![image (2)](https://user-images.githubusercontent.com/22217538/107768913-721c0580-6d37-11eb-8087-6617d704c6f1.png)

## Contesto
La Select è popolata dinamicamente all'apertura della Modal

**Comment by Cholo981** [comment]
Se l'altezza della modal supera un "certo valore" (un modal-body di circa 400px credo) il problema non si presenta o quantomeno è molto più accettabile (rimane il problema che la larghezza dell'elenco per qualche ragione è settata al minimo del testo, anziché sulla larghezza della Select, ma almeno non ci sono voci non selezionabili).

Sembra un problema legato al calcolo del posizionamento dell'elenco. In particolare di questa traslazione verticale:
transform: translate3d(0px, -661px, 0px);
![image (3)](https://user-images.githubusercontent.com/22217538/107799432-ae625c80-6d5d-11eb-92ea-3229b16f009d.png)

**Comment by riccafi** [comment]
Ci sono degli aggiornamenti in merito a questo punto, o è stato pianificato qualche tipo di intervento?

**Comment by astagi** [comment]
@riccafi @Cholo981 la via più semplice e accessibile per risolvere questo inconveniente è utilizzare una normale select con la versione 1.6.2

<img width="948" alt="image" src="https://user-images.githubusercontent.com/537363/162493326-a8b57d19-c0fd-427b-94f9-f4cc18d9858e.png">

Di seguito riporto l'esempio di select standard popolata dinamicamente

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-italia@1.6.2/dist/css/bootstrap-italia.min.css">
    <title>Document</title>
</head>

<body>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Lancia la demo della
        modale</button>

    <!-- Modal -->
    <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal" aria-labelledby="exampleModalTitle">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalTitle">dialog header</h5>
                </div>
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-sm-6">
                            <div class="select-wrapper">
                                <label for="select_id">Etichetta</label>
                                <select id="select_id" title="Scegli una opzione">
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary btn-sm" data-dismiss="modal" type="button">Close</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-italia@1.6.2/dist/js/bootstrap-italia.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            buildSelect("select_id");
            setTimeout(() => {
                $('#select_id').val("val2");
            }, 1000);

        });

        function buildSelect(aDiv) {
            for(let i = 0 ; i < 100 ; i++) {
                $('#' + aDiv).append(new Option("Option " + i, "val" + i))
            }
        }
    </script>
</body>

</html>
```
