### ISSUE TITLE
Problema Select Bootstrap Italia con React

### ISSUE THREAD

**Issue by Crow0197** [italia/bootstrap-italia#514]
## Comportamento atteso
Visualizzazione corretta di una **select** all'interno della mia pagina

## Comportamento attuale
Attualmente, una volta aggiunto il **tag select** il div generato con la classe ".dropdown-menu .inner" non viene visualizzato

## Possibili soluzioni
come soluzione procedo con il forzare una volta su block il div che non viene visualizzato. Ciò permette di averlo valorizzato nel DOM

```
.dropdown-menu .inner {
display: block;
}

```

## Contesto
React

**Comment by dej611** [comment]
C'è un motivo percui usare questo e non il [`design-react-kit`](https://github.com/italia/design-react-kit) per la select?
Stiamo cercando di migliorare il kit e sarebbe utile capire il perchè di questa scelta.

**Comment by gianlu21** [comment]
Ciao il problema sorge nel momento in cui si installa design-react-kit dove il componente SELECT a quanto pare non è più implementato. Ci si può accorgere di questo andando nei pacchetti installati (node_modules/design-react-kit/src/components). In questo percorso manca proprio la SELECT. Il problema quindi persiste

**Comment by dej611** [comment]
Il componente `Select` sarà incluso nel kit dalla prossima minor release.
Ad ogni modo è possibile già al momento utilizzare una select che rispetti il kit importando `react-select` ed un paio di configurazioni. Puoi usare il codice della prossima release come base: https://github.com/italia/design-react-kit/blob/master/src/components/Select/Select.js

**Comment by astagi** [comment]
@dej611 direi possiamo chiudere questa issue che ne dici?

**Comment by dej611** [comment]
Si, dalla versione 4.0 del kit un componente `Select` viene esportato direttamente.

**Comment by astagi** [comment]
Perfetto! Grazie @dej611
