### ISSUE TITLE
È possibile importare solo un componente singolo invece che l'intera libreria?

### ISSUE THREAD

**Issue by stefanobartoletti** [italia/bootstrap-italia#529]
Ciao a tutti, come da titolo, vorrei sapere se è possibile utilizzare solo alcuni componenti in un progetto che utilizza Bootstrap 4 nativo, senza dovr importare tutta la libreria Bootstrap Italia.

Mi spiego meglio, vorrei utilizzare slo alcuni componenti scelti, ad esempio il megamenu, è possibile farlo in maniera semplice? Nella documentazione non mi pare di aver letto nulla a tal proposito, ma magari è qualcosa che è sfuggita a me.

Grazie!

**Comment by francescozaia** [comment]
Ciao @stefanobartoletti no purtroppo al momento non è possibile in modo semplice, sicuramente non appena riprendiamo a lavorare alla libreria la modularità sarà tra le priorità.

**Comment by stefanobartoletti** [comment]
Grazie, tutto chiaro
