### ISSUE TITLE
Export dei token di design come json

### ISSUE THREAD

**Issue by dej611** [italia/bootstrap-italia#540]
Sarebbe utile esportare i token del design kit come json.

Questo aiuterebbe a meglio interare alcune variabili di stile all'interno dei vari kit di integrazione senza hardcode a mano.

**Comment by francescozaia** [comment]
Cosa intendi per "token del design kit"?

**Comment by dej611** [comment]
A partire dalle variabili SASS, più informazioni ci sono machine readable meglio è.
Per il momento mi servono le variabili SASS, ma avere anche informazioni meta potrebbe essere comodo in futuro.
