### ISSUE TITLE
Popover: esempio titolo con icona non mostra alcuna icona

### ISSUE THREAD

**Issue by dej611** [italia/bootstrap-italia#544]
## Comportamento atteso
L'icona passata come titolo via HTML snippet dovrebbe essere mostrata.

## Comportamento attuale
L'HTML dell'icona viene sanificato mostrando unicamente il titolo:

<img width="282" alt="Screenshot 2021-05-25 at 08 22 52" src="https://user-images.githubusercontent.com/924948/119451949-18fc3e80-bd36-11eb-880b-5811eb4f93f7.png">

https://italia.github.io/bootstrap-italia/docs/componenti/popover/#titolo-con-icona-e-link

**Comment by astagi** [comment]
Fixed by https://github.com/italia/bootstrap-italia/commit/8e4a819a92e760987865598b04e14c7f9febfa93
