### ISSUE TITLE
Bug Bootstrap-Italia preselezione select popolata dinamicamente

### ISSUE THREAD

**Issue by alicastellano** [italia/bootstrap-italia#549]
Salve a tutti,
ho un problema con il prepolamento delle select con Bootstrap-Italia.
Le option sono popolate dinamicamente da backend usando la ‘setOptionsToSelect’ come indicato nella documentazione Bootstrap-Italia. In seguito al popolamento il valore delle select viene prepopolato con JQuery con $(’#select_id’).val(“val2”); Quest’ultimo però non funziona e il valore prepopolato appare per pochi istanti e poi sparisce. Ho fatto anche vari tentativi sfruttando l’attribute ‘selected’ delle option ma nulla. 
Analizzando la struttura della pagina il div con classe 'bootstrap-select-wrapper ’ che veste la select non ha un comportamento corretto in fase di prepopolamento dati in quanto l’etichetta testuale della option selezionata non viene scritta nell’elemento con classe ‘filter-option-inner-inner’. 
Qualcuno ha avuto lo stesso problema e sa come risolvere questa issue? Grazie mille !

Per maggiore comprensione riporto di seguito html della select e lo script con selezione del val che non funziona a valle del popolamento dinamico:

```
<div class="form-row">
		<div class="form-group col-sm-6">
			<div id="select_id_wrapper" class="bootstrap-select-wrapper">
				<label class="active">Etichetta</label>
				<select id="select_id" title="Scegli una opzione">
				</select>
			</div>
		</div>
</div>
 

 <script>
	$(document).ready(function () {
        	 buildSelect("select_id_wrapper");
        	$('#select_id').val("val2");	
        });
           
        function buildSelect(aDiv){
    	    		$('#'+aDiv).setOptionsToSelect([{
    		      text: 'option1',
    		      value: 'val1'
    		    },{
    		      text: 'option2',
    		      value: 'val2'
    		    },{
    		      text: 'option3',
    		      value: 'val3'
    		    }]);
    	}
			
</script>
```

## Comportamento atteso
la select dovrebbe apparire prevalorizzata col valore passato tramite JQuery (nell'esempio la option2 deve apparire prepopolata)

## Comportamento attuale
la select appare non valorizzata 

## Contesto
forzando $('#select_id').val("val2").change(); la preselezione funziona il più delle volte sui browser Firefox ed Explorer mentre non funziona mai su browser Chrome.

**Comment by astagi** [comment]
Con la nuova release caldeggiamo l'utilizzo della select standard accessibile. @alicastellano prova il seguente esempio completo.

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-italia@1.6.2/dist/css/bootstrap-italia.min.css">
    <title>Document</title>
</head>

<body>
    <div class="form-row">
        <div class="form-group col-sm-6">
            <div class="select-wrapper">
                <label for="select_id">Etichetta</label>
                <select id="select_id" title="Scegli una opzione">
                </select>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-italia@1.6.2/dist/js/bootstrap-italia.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            buildSelect("select_id");
            setTimeout(() => {
                $('#select_id').val("val2");
            }, 1000);

        });

        function buildSelect(aDiv) {
            $('#' + aDiv)
                .append(new Option("Option 1", "val1"))
                .append(new Option("Option 2", "val2"))
                .append(new Option("Option 3", "val3"))
        }

    </script>
</body>

</html>
```
