### ISSUE TITLE
migrazione a Boostrap 5

### ISSUE THREAD

**Issue by simevo** [italia/bootstrap-italia#552]
State valutando di aggiornare il tema a boostrap 5? Grazie

**Comment by AlessandroVecchi** [comment]
Prima di prendere in considerazione un passaggio alla versione 5 occorre tenere presente un punto chiave:

> Internet Explorer is not supported. If you require Internet Explorer support, please use Bootstrap v4.
https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/

Purtroppo nell'ambito della PA IE ha ancora un piccola fetta di utilizzatori

**Comment by bunglegrind** [comment]
per avere un quadro complessivo, l'EOL di bootstrap 4 è prevista per il 1 novembre 2022:

https://github.com/twbs/release

**Comment by AlessandroVecchi** [comment]
> 
> 
> per avere un quadro complessivo, l'EOL di bootstrap 4 è prevista per il 1 novembre 2022:
> 
> https://github.com/twbs/release

Prima di passare a bootstrap 5 il progetto sarebbe da aggiornare almeno alla 4.6, ma visto che l'ultima release è di gennaio mi chiedo se ci sia ancora qualcuno che lo porta avanti.

**Comment by simevo** [comment]
https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-end-of-support

> Starting June 15, 2022, the Internet Explorer 11 desktop application will no longer be supported on certain versions of Windows 10*.

**Comment by francescozaia** [comment]
Una piccola nota da ex maintainer: purtroppo al momento il progetto non è gestito.
Dovrebbe riprendere ad avere supporto entro l'anno, con l'aggiornamento a Bootstrap 5 e fix di accessibilità e quant'altro già segnalato da tempo nelle issue. 🤞

**Comment by AlessandroVecchi** [comment]
> 
> 
> Una piccola nota da ex maintainer: purtroppo al momento il progetto non è gestito.
> Dovrebbe riprendere ad avere supporto entro l'anno, con l'avvio delle attività per l'aggiornamento a Bootstrap 5 e fix di accessibilità e quant'altro già segnalato da tempo nelle issue. 🤞

Immaginavo infatti, con lo scioglimento del team digitale molti progetti hanno subito una battuta d'arresto, mi auguro che si possa ripartire presto.

**Comment by dej611** [comment]
Novità a riguardo?

Di recente Reactstrap è passato a Bootstrap 5.1 lasciando la versione precedente un po' in un angolo.
Come kit React stiamo preparando una release 4 con molti cambiamenti, ma vorremmo avere una idea di una roadmap per Bootstrap 5 così da organizzarci ed evitare breaking change continui.

**Comment by astagi** [comment]
I lavori stanno procedendo su un repo separato, il tutto sarà presto disponibile come branch principale di questo repository, utilizzando invece un branch 1.x per il mantenimento della vecchia versione. [Qui](https://designers.italia.it/notizie/Accessibilita-migliorata-con-bootstrap-italia/) la notizia.
