### ISSUE TITLE
Importare solo alcuni componenti

### ISSUE THREAD

**Issue by DrViente** [italia/bootstrap-italia#556]
Buongiorno,

È possibile importare solamente alcuni componenti della libreria (esempio: a me interessa usare solo le Tabelle https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/tabelle/) senza dover importare tutta la libreria?

Grazie in anticipo e cordiali saluti

**Comment by astagi** [comment]
L'unico modo per farlo è utilizzando la cartella `src` nei `node_modules` (https://www.jsdelivr.com/package/npm/bootstrap-italia?path=src) dove è possibile recuperare i file js e scss e importarli con Gulp o altri tool per creare il proprio bundle minificato. Nella nuova versione di Bootstrap Italia (2.0) sarà caldeggiata la metodologia tree-shaking.
