### ISSUE TITLE
Owl Carousel con Sticky Navbar

### ISSUE THREAD

**Issue by KevinShareIn** [italia/bootstrap-italia#560]
## Comportamento
Quanto utilizzo il Carousel (Fullscreen di immagini) assieme al menu di navigazione sticky:

Ciao,
gli owl-item "cloned"  mi spariscono magicamente. 
Nel mio caso il problema è quando utilizzo la classe .it-header-sticky nel menu di navigazione, viceversa con la classe .it-big-img inserita nel Carousel... da quello che ho capito le due cose non vanno d'accordo. Spero possa essere d'aiuto.

Quando la Navbar diventa Sticky (con la classe .is-sticky che si aggiunge automaticamente) tutto bene, ma quando ritorna il Classico menu di navigazione, gli Owl-item (più specificamente quelle con la classe .cloned) vengono totalmente rimosse dal DOM. Il comportamento del Carousel in loop non è quello atteso perchè gli item che si eliminano non mi permettono di scrollare le slide dalla 3, cioè l'ultima slide, alla 1 o viceversa.

**Comment by KevinShareIn** [comment]
Codice per risolvere il problema: 
`var lastScrollTop = 0;
$(window).scroll(function(event){
    var st = $(this).scrollTop();
    if(st > 50 && st < 150){
        //alert("Navbar -> .is-steacky removed!");
        var $owl = $('.owl-carousel');
        $owl.trigger('refresh.owl.carousel');
    }
    lastScrollTop = st;
});`

ATTENZIONE: Questa non è una soluzione definitiva ma solo momentanea. 
Grazie a tutti!

**Comment by astagi** [comment]
Nelle ultime versioni OwlCarousel è stato deprecato in favore di Splide che non dovrebbe presentare il problema. Chiudo la issue, se si ripresenta il problema riapriamo una segnalazione più specifica.
