### ISSUE TITLE
Funzione classe bg-dark su contenuto componente Hero

### ISSUE THREAD

**Issue by dej611** [italia/bootstrap-italia#561]
Nella documentazione [del componente Hero](https://italia.github.io/bootstrap-italia/docs/componenti/hero/), la classe di contenuto `it-hero-text-wrapper` è **sempre** accompagnta dalla classe `bg-dark`, che però non sembra avere alcun effetto - sembra essere sovrascritta dalla prima infatti.

Ha qualche funzione questa classe `bg-dark`? Quale? È possible avere un esempio in tal caso?

**Comment by KevinShareIn** [comment]
Nella documentazione non c'è nessun riferimento che indica cosa fa effettivamente questa classe ma in linea di massina la regola è questa: 
bg-dark{
  background-color: --var(dark);
}

Se vuoi vedere l'effetto sul tuo componente Hero utilizzando la classe bg-dark, devi avere dei componenti su cui applicare l'effetto del background color, ad esempio:

1) nel caso del hero viene utilizzato il bottone in questo modo,
<div class="it-btn-container"><a class="btn btn-sm btn-secondary" href="#">Label button</a></div>

2) oppure inserisci un semplice bottone, 
<button type="button" class="btn btn-primary">Primary</button>

Fammi sapere, spero di esserti stato d'aiuto. 
Kevin

**Comment by dej611** [comment]
Capisco che la classe `bg-dark` ha un suo scopo come utility class, ma nel contesto specifico del componente `Hero`, affiancato a `it-hero-text-wrapper`, a che serve?

Se contiene solo il `background-color` del container e questo viene sovrascritto dalla classe gemella `it-hero-text-wrapper`, dove entra in gioco il bottone?

**Comment by KevinShareIn** [comment]
Sei vai nella documentazione del componente hero, più precisamente nel paragrafo "Con testi ed immagine di sfondo", con "ispeziona elemento" levando `.bg-dark` puoi vedere l'effetto che ha sul tuo componente.

Il bottone entra in gioco proprio dentro al contenitore con classe `.it-hero-text-wrapper`, va inserito lì dentro.

La classe `.it-hero-text-wrapper` non ha` background-color` settati ma contiene `background: 0 0!important;` che sta rispettivamente per` background-position-x: 0;` e `background-position-y;`.

Quel `.bg-dark` entra in gioco solo quando nei suoi elementi (parent) c'è un bottone, vengo e mi spiego:
Nelle regole CSS `.bg-dark` è sempre affiancata da un altra regola, ad esempio:

.bg-dark .btn-secondary {
    background-color: #06c;
    border-color: #fff;
    -webkit-box-shadow: inset 0 1px 0 rgb(255 255 255 / 15%), 0 1px 1px rgb(0 0 0 / 8%);
    box-shadow: inset 0 1px 0 rgb(255 255 255 / 15%), 0 1px 1px rgb(0 0 0 / 8%);
    color: #fff;
}

.bg-dark .btn-outline-primary {
    color: #fff;
    background-color: transparent;
    background-image: none;
    -webkit-box-shadow: inset 0 0 0 1px #fff;
    box-shadow: inset 0 0 0 1px #fff;
    -webkit-box-shadow: inset 0 0 0 2px #fff;
    box-shadow: inset 0 0 0 2px #fff;
}

Invece c'è `.it-hero-wrapper`  che ha` background-color` settato.
Quindi credo che `.bg-dark` è inutile se non hai bottoni nel tuo componento hero..

A cosa ti serve la classe di bg-dark, che tipo di comportamento speravi di avere?
Kevin

**Comment by dej611** [comment]
Se non serve la voglio togliere.
Ho provato a notare le differenze sia con FF che Chrome, ma con o senza quella classe noto esattamente lo stesso risultato:
<img width="322" alt="Screenshot 2021-10-02 at 13 02 34" src="https://user-images.githubusercontent.com/924948/135713477-db7d97d1-e834-447c-bba0-e2f546cbfa87.png">
<img width="929" alt="Screenshot 2021-10-02 at 13 02 57" src="https://user-images.githubusercontent.com/924948/135713478-2b899ac3-b844-4eb1-b2d1-267655388ca7.png">
<img width="923" alt="Screenshot 2021-10-02 at 13 03 04" src="https://user-images.githubusercontent.com/924948/135713480-4a09aad2-f82f-4f4b-95f7-1e3225e28e0f.png">
<img width="928" alt="Screenshot 2021-10-02 at 13 03 24" src="https://user-images.githubusercontent.com/924948/135713482-476556ac-74d0-4969-92b3-70316c0b0de5.png">
<img width="913" alt="Screenshot 2021-10-02 at 13 03 31" src="https://user-images.githubusercontent.com/924948/135713483-864d23a9-09b2-4430-bdd4-9f10fa059fbe.png">

**Comment by KevinShareIn** [comment]
### **Con bg-dark:**

![111](https://user-images.githubusercontent.com/26541596/135714706-a400e2f9-a143-4e0d-ab46-5ef7ef645051.PNG)

### **Senza bg-dark:**

![2222222](https://user-images.githubusercontent.com/26541596/135714654-173c4151-7210-44e1-bc8e-de75ba6d5736.PNG)

Come si può vedere, se presente un bottone, nel primo caso e quindi con `.bg-dark` il bottone è ben visibile ma nel secondo caso e quindi levanto la classe `.bg-dark` il bottone pare scomparire.

P.S.: Se non riesci a vedere chiaramente le immagini cliccaci sopra per ingrandirle

Kevin

**Comment by dej611** [comment]
Ok chiaro. Certo, è un po' scomodo da portare appresso in ogni caso solo nell'eventualità di una CTA.
Se il bottone è l'unica applicazione funzionale della classe, non converrebbe invece agganciarla a `.it-btn-container`?
Ragionando in termini di componenti, sarebbe più facile ottenere lo stesso risultato, no?

**Comment by KevinShareIn** [comment]
Si, potrebbe avere senso ma fai attenzione a non metterlo direttamente sul bottone perché il funzionamento è diverso.
Nel `.it-btn-container` va più che bene.
Kevin
