### ISSUE TITLE
Validazione input di tipo "select" non funziona

### ISSUE THREAD

**Issue by rudy1976s** [italia/bootstrap-italia#564]
## Comportamento attuale

L'unico modo che mi permette di ovviare al problema è  togliere il novalidate dal form e lasciare che ci pensi il validatore standard di HTML a funzionare , ma non è più conforme

Rudy

**Comment by astagi** [comment]
Già citato anche in #422

**Comment by astagi** [comment]
@rudy1976s riscontri il problema anche nell'ultima versione? c'è un nuovo plugin di validazione, [qua la demo](https://italia.github.io/bootstrap-italia/docs/esempi/form/)
