### ISSUE TITLE
[Doc] Contenuto tabella responsive inizia prima della sezione responsive

### ISSUE THREAD

**Issue by dej611** [italia/bootstrap-italia#566]
Questa riga indica l'inizio della spiegazione per le tabella responsive con vari dettagli implementativi: https://github.com/italia/bootstrap-italia/blame/master/docs/organizzare-i-contenuti/tabelle.md#L384

Il contenuto è ancora dentro la sezione `classi contestuali`.

A seguito di questa sezione segue una sezione `Captions`, che poco a che fare con il responsive. Infine la sezione `responsive`.

**Comment by dej611** [comment]
C’è una sezione dedicata alle tabelle responsive che è stata inserita an anticipo (sopra Captions e dentro Classi contestuali che si riferiscono ai colori).

Il contenuto andrebbe spostata nella sezione Tabelle responsive poco sotto

**Comment by astagi** [comment]
@dej611 spostati i contenuti, se ritieni ci sia altro da aggiungere dimmi pure, grazie!
