### ISSUE TITLE
Estensione Set di Icone Bootstrap Italia

### ISSUE THREAD

**Issue by riccafi** [italia/bootstrap-italia#568]
## Comportamento atteso
Al fine di aumentare l'espressività consentita dalle icone fornite con Bootstrap italia, si propone di estenderle includendo alcune tipologie presenti ad oggi su Bootstrap (https://icons.getbootstrap.com/), ma non su Bootstrap Italia.

## Comportamento attuale
Rispetto alle icone presenti, potrebbero esserne incluse altre.
Di seguito alcune proposte di aggiunta:

- https://icons.getbootstrap.com/icons/bar-chart-line/
- https://icons.getbootstrap.com/icons/bell/
- https://icons.getbootstrap.com/icons/briefcase/
- https://icons.getbootstrap.com/icons/calculator/
- https://icons.getbootstrap.com/icons/calendar* serie
- https://icons.getbootstrap.com/icons/card-image/
- https://icons.getbootstrap.com/icons/file-pdf/
- https://icons.getbootstrap.com/icons/file-word/
- https://icons.getbootstrap.com/icons/file-ruled/
- https://icons.getbootstrap.com/icons/fingerprint/
- https://icons.getbootstrap.com/icons/laptop/
- https://icons.getbootstrap.com/icons/keyboard/
- https://icons.getbootstrap.com/icons/magic/
- https://icons.getbootstrap.com/icons/meta/
- https://icons.getbootstrap.com/icons/mouse/
- https://icons.getbootstrap.com/icons/qr-code/
- https://icons.getbootstrap.com/icons/recycle/
- https://icons.getbootstrap.com/icons/smartwatch/

**Comment by riccafi** [comment]
Ci sono degli aggiornamenti in merito a questo punto, o è stato pianificato qualche tipo di intervento?

**Comment by astagi** [comment]
Ciao @riccafi per ora non ci sono aggiornamenti in merito, porto la questione in sviluppo e ti aggiorno. Probabilmente un set di icone più ampio potrebbe essere previsto su BSI 2.0
