### ISSUE TITLE
Setup Badges per build system e Slack

### ISSUE THREAD

**Issue by francescozaia** [italia/bootstrap-italia#6]
Definire quali servizi integrare e aggiungere nel file README.md badge che mostrino lo stato dell'eventuale sistema di CI, oltre ai classici badge della community di Developers Italia su Slack.

**Comment by ruphy** [comment]
In generale, sarebbe interessante definire un elenco di badge che ci piacerebbe avere.
Un po' di idee sul motore che usiamo oggi: shields.io
