### ISSUE TITLE
Select con ricerca con più di 599 opzioni

### ISSUE THREAD

**Issue by vinset** [italia/bootstrap-italia#619]
## Comportamento atteso
La select con ricerca mostra le opzioni normalmente se sotto i 600 valori. 

## Comportamento attuale
Oltre i 599 la visualizzazione grafica viene deformata impedendone la corretta lettura.

## Contesto
Versione bootstrap-italia 1.4.3
Browser Chrome

**Comment by astagi** [comment]
Grazie per aver riportato questa issue @vinset puoi fornire un codice di esempio anche su CodePen per replicare il comportamento?

**Comment by astagi** [comment]
Gentilissimo @vinset grazie! Provvederemo a risolvere il problema.

**Comment by vinset** [comment]
Ho provato ad installare la versione beta-2 in sviluppo del componente bootstrap-select. Il problema persiste.

**Comment by vinset** [comment]
Il problema si risolve disabilitando virtualScroll
$('.select').selectpicker({ virtualScroll: false });

**Comment by astagi** [comment]
grazie @vinset possiamo chiudere il bug in questione quindi? Magari possiamo citare questa soluzione in documentazione, il plugin utilizzato per la select non è aggiornato da tempo..

**Comment by vinset** [comment]
Sull'aggiornamento del plugin ci stanno lavorando e si sta provvedendo ad una versione compatibile con bootstrap 5 che non preveda l'utilizzo di jquery. Credo, comunque, che inserendo in documentazione questo workaround il bug si possa chiudere.

**Comment by astagi** [comment]
@vinset aggiunta PR con documentazione
