### ISSUE TITLE
Aggiornare base Bootstrap 4.x.x a Bootstrap 5

### ISSUE THREAD

**Issue by xXConcasXx** [italia/bootstrap-italia#620]
## Comportamento atteso

Sarebbe opportuno **iniziare a pensare allo sviluppo** di un nuovo wrapper basato su **Bootstrap 5**.

Alcuni dei vantaggi possono essere i seguenti:

- Abbandono di jQuery.
- Abbandono di Internet Explorer.
- Passaggio da px a rem per la misurazione delle griglie.
- Responsive Front Size.
- Ottimizzazione della Navbar.

## Comportamento attuale

Wrapper basato su una versione obsoleta di Bootstrap.

## Possibili soluzioni

Avviare lo sviluppo di un progetto parallelo e offrire la possibilità allo sviluppatore di scegliere la versione più appropriata per il suo progetto.

**Comment by arturu** [comment]
Esiste già la issue https://github.com/italia/bootstrap-italia/issues/552

**Comment by astagi** [comment]
@xXConcasXx sarà prevista la migrazione a Bootstrap 5, è in fase di analisi al momento.

Duplicato di #552 chiudo.
