### ISSUE TITLE
notificationShow is not defined in non-bundle version 

### ISSUE THREAD

**Issue by vinset** [italia/bootstrap-italia#621]
## Comportamento atteso

notificationShow() dovrebbe mostrare la notifica

## Comportamento attuale

Si presenta lo stesso problema descritto in questa issue  #433 compilando la libreria.

**Comment by astagi** [comment]
Ciao @vinset stai provando la versione su master attualmente in sviluppo o quella su NPM?

**Comment by vinset** [comment]
Versione master

**Comment by astagi** [comment]
Grazie della segnalazione @vinset come al solito ti chiedo se hai la gentilezza di condividere se hai già un esempio riproducibile, in alternativa possiamo provvedere noi, tanto è facilmente riproducibile.

**Comment by vinset** [comment]
Purtroppo questa volta non riesco a fornire esempio

**Comment by astagi** [comment]
@vinset di nuovo grazie per il tuo prezioso contributo, il fix su #631 dovrebbe risolvere il tuo problema, facci sapere e lo includiamo nella nuova versione

**Comment by vinset** [comment]
Confermo risoluzione problema. Grazie
