### ISSUE TITLE
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia#639]
## Comportamento attuale

Durante la compilazione viene restituito questo warning

`
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
`

## Possibili soluzioni

1. individuare dove viene usato l'operatore della divisione `/` fuori dalla funzione `calc()`
2. usare `calc()` presumo, o qualcosa di simile.

## Contesto

sass: ^1.49.7
webpack: ^5.68.0

**Comment by arturu** [comment]
Trovata la linea di codice, è nella dipendenza bootstrap-select

https://github.com/snapappointments/bootstrap-select/blob/6c4c75f61e69ca54d5ab557a2b90ffdccf1c63cd/sass/bootstrap-select.scss#L26

    $amnt: $amnt / 100; // convert to percentage if int

nella nuova versione (che è in beta) hanno fixato il problema.

**Comment by astagi** [comment]
Grazie @arturu attendiamo un loro rilascio allora, vedo stanno lavorando sul branch `dev` anche a dei fix sulla ricerca, farò dei test, magari risolvono anche la #619

**Comment by StefanoVollono** [comment]
Ho fixato da poco lo stesso problema su un mio progetto personale, migrando da node-sass a sass (dart-sass)  e si, vi confermo che con la versione Dart Sass 2.0.0 verranno deprecate le divisioni al di fuori del calc. Qui per maggiori dettagli: https://sass-lang.com/documentation/breaking-changes/slash-div.

**Comment by astagi** [comment]
ho fatto una PR al volo, sembra funzionare :) ditemi anche voi!

**Comment by StefanoVollono** [comment]
@astagi ho visto la PR, è un peccato dover includere un intero css all'interno della codebase per modificare una sola riga di una funzione, però al momento é l'unica soluzione se vogliamo eliminare quel warning in console. Almeno finché non pubblicheranno la versione che fixa quel problema e possiamo ripristinare il vecchio import dalla node_modules.

**Comment by astagi** [comment]
Esatto @StefanoVollono unica strada al momento :(
