### ISSUE TITLE
Segnalazione Icone bootstrap Italia

### ISSUE THREAD

**Issue by matteolcd** [italia/bootstrap-italia#643]
## Comportamento atteso
Riporto alcuni problemi a visualizzare determinate icone nel set di icone bootstrap-italia. Stavo lavorando con una vecchia versione e ho scaricato solamente il nuovo pacchetto di icone sostituendolo al vecchio, ho pensato fosse una mancanza di aggiornamento del file "sprite.svg" utilizzato ma il problema continua ad essere presente.

## Comportamento attuale
Non ricevo errori in console ma non riesco a collegarmi ad alcune icone come ad esempio "it-flag", mentre altre funzionano correttamente.
Potrebbe essere un problema mio dovuto a qualche configurazione errata eseguita sul progetto qualche anno fa, tuttavia ho pensato di segnalarlo che magari poteva essere comodo.

## Contesto
Le cartelle sono così predisposte

ROOT
| - dist
| -- svg
| --- sprite.svg
| - layout
| -- index.html

Inserisco il codice di chiamata all'icona:

```html
...
<div class="col-12 col-md-6 col-lg-4">
  <svg class="icon">
    <use href="../dist/svg/sprite.svg#it-arrow-down-circle"></use>
  </svg> it-arrow-down-circle
</div>
...
```

Il problema si ripete sui diversi browser utilizzati con lo stesso comportamento.
Allego uno screen di ciò che accade 
<img width="1385" alt="Schermata 2022-02-17 alle 16 45 48" src="https://user-images.githubusercontent.com/33934759/154520180-0f355fb2-a044-4def-9d84-6fb61c7b765c.png">

**Comment by astagi** [comment]
Ciao! Grazie della segnalazione. Ho provato sia con la versione 1.5.2 che 1.3.7 (immagino sia quella che stai utilizzando). In entrambi i casi lasciando intatto il file sprite, le icone si visualizzano correttamente. Ti allego qua i due zip di esempio che ho lanciato con un semplice server locale.

[Esempio BSI 1.5.2 example-BSI-1.5.2.zip](https://github.com/italia/bootstrap-italia/files/8102270/example-BSI-1.5.2.zip)
[Esempio BSI 1.3.7 example-BSI-1.3.7.zip](https://github.com/italia/bootstrap-italia/files/8102272/example-BSI-1.3.7.zip)
