### ISSUE TITLE
Missing dependency browserslist-config-design-italia ?

### ISSUE THREAD

**Issue by freddi301** [italia/bootstrap-italia#647]
## Comportamento atteso

Creando un progetto con create-react-app e aggiungendo `import "bootstrap-italia"` il css dovrebbe essere incluso correttamente

## Comportamento attuale

Per poter importare il css ho dovuto istallare `browserslist-config-design-italia` come dipendenza

## Possibili soluzioni

indicare come peer-dependency?

**Comment by freddi301** [comment]
E una cosa da fare nel progetto che usa bootstrap-italia o nel codice di bootstrap-italia?

**Comment by astagi** [comment]
@freddi301 l'operazione che dico io è da fare nel codice di bootstrap-italia, per indagare meglio hai del codice open da condividere dove posso provare questo problema?

**Comment by freddi301** [comment]
Per replicare:
- creare nuovo progetto con create-react-app
- aggiungere dipendenza boostrap-italia
- aggiungere `@import "bootstrap-italia"` nel file index.css
- compilare

NOTA:
con "react-scripts": "5.0.0" si presenta questo problema
con "react-scripts": "4.0.0" sembra di no

**Comment by astagi** [comment]
Grazie @freddi301 provo!

**Comment by astagi** [comment]
@freddi301 1.6.0 appena rilasciata, questo problema dovrebbe sparire con l'installazione della stessa :)
