### ISSUE TITLE
Incoerenza tra documentazione componenti carousel e carousel legacy e sezione per iniziare

### ISSUE THREAD

**Issue by achy72** [italia/bootstrap-italia#656]
Nella pagine di dettaglio dei componenti carousel e carousel legacy si fa presente che gli script css e js necessari al loro funzionamento devono essere referenziati a parte perchè non più presenti nel bundle mentre nella pagina come iniziare l'owl carousel risulta ancora essere incluso nel bundle.

**Comment by astagi** [comment]
Grazie @achy72 risolto qui https://github.com/italia/bootstrap-italia/commit/16ffd4979c4026559791cf09b09bfaa575a63e06
