### ISSUE TITLE
Script js carousel-legacy: errore di assegnazione variabile nella sezione di accessibilità 

### ISSUE THREAD

**Issue by achy72** [italia/bootstrap-italia#657]
## Comportamento atteso

Ai singoli elementi viene aggiunto un attributo aria-label="elemento i di n" dove i è l’indice dell’elemento ed n il numero totale di elementi. Agli owl-dot viene aggiunto un attributo aria-label="slide i di n del carousel" dove i è l’indice della slide del carousel attiva ed n il numero totale di slide.

## Comportamento attuale

Il funzionamento è corretto per gli elementi owl-item mentre per gli owl-dot viene riportato sempre il numero degli owl-item totali anzichè degli owl-dots

  var dots = $(event.target).find('.owl-dot')
  $(dots).each(function (index) {
    var dotDescText = dotDesc.replace('{{i}}', index + 1)
    dotDescText = dotDescText.replace('{{n}}', **slides.length**)
    $(this).attr('aria-label', dotDescText)
  })

## Possibili soluzioni

Nel ciclo dots sostituire **slides.length** con **dots.length**

var dots = $(event.target).find('.owl-dot')
$(dots).each(function (index) {
  var dotDescText = dotDesc.replace('{{i}}', index + 1)
  dotDescText = dotDescText.replace('{{n}}', **dots.length**)
  $(this).attr('aria-label', dotDescText)
})

**Comment by astagi** [comment]
Buonasera @achy72 grazie del report. Si il tuo suggerimento mi torna, mi confronto anche con il resto del team ma credo si tratti di una semplice svista. Apro una PR per il fix dovrebbe risultare il template seguente 

```html
<div class="owl-dots">
    <button role="button" class="owl-dot active" aria-label="Slide 1 di 3 del carousel"><span></span></button>
    <button role="button" class="owl-dot" aria-label="Slide 2 di 3 del carousel"><span></span></button>
    <button role="button" class="owl-dot" aria-label="Slide 3 di 3 del carousel"><span></span></button>
</div>
```

**Comment by astagi** [comment]
@achy72 rilasciata versione 1.6.1 con fix

**Comment by astagi** [comment]
a te @achy72
