### ISSUE TITLE
Bug sulla modifica  da bottone del valore dell'input numerico con step decimale

### ISSUE THREAD

**Issue by Erminz87** [italia/bootstrap-italia#659]
## Comportamento atteso

Con input numerico settato con step decimale (es. 0.1) modificando il valore attraverso i bottoni dovrebbe mostrare di volta in volta un valore pari al valore precedente + valore decimale settato nell'attributo step (es. partendo da zero con step settato a 0.1 mi aspetto in sequenza: 0 , 0.1, 0.2 ecc...)

## Comportamento attuale

Modificando il valore attraverso i bottoni, dopo aver inizialmente aggiunto/sottratto consecutivamente (e con successo) la quantità prevista, inizia invece a mostrare un risultato arrotondato per difetto (es. partendo da zero con step settato a 0.1 mi restituisce in sequenza: 0, 0.1, 0.19999999999999, 0.29999999999998 ecc...)
![Schermata 2022-03-29 alle 11 49 07](https://user-images.githubusercontent.com/49489630/160588223-a3692791-df7f-4c5a-b9e9-6cb5d037857b.png)

## Contesto

Il problema pare si presenti solo su chrome e safari, su firefox funziona correttamente (ambiente mac e windows 10)

**Comment by astagi** [comment]
Buongiorno @Erminz87 grazie del report, per verificare correttamente il tuo problema avrei bisogno di sapere quale versione di Bootstrap Italia stai utilizzando.

**Comment by Erminz87** [comment]
Attualmente sto usando la v1.4.3 ma anche passando alla v1.6.1 il problema si ripresenta

**Comment by astagi** [comment]
Perfetto grazie @Erminz87 ci muoviamo alla risoluzione e rilasciamo patch asap

**Comment by astagi** [comment]
@Erminz87 PR aperta. L'aggiunta riguarda un attributo `digits` da aggiungere  che permette di specificare i decimali del valore nel caso di input numerico. Questo risolve anche problemi di approssimazione cross browser oltre che mantenere una corretta visuallizzazione del dato. Trovi un esempio sulla preview di Vercel
