### ISSUE TITLE
[question] perché si è deciso di limitare l'altezza dell'header slim?

### ISSUE THREAD

**Issue by PiemP** [italia/bootstrap-italia#664]
## Comportamento atteso

Gli header slim (div con classe it-header-slim-wrapper) non dovrebbero avere un altezza limitata da codice CSS. 

## Comportamento attuale

Attualmente le classi it-header-slim-wrapper e it-header-slim-wrapper-content sono limitati in altezza tramite la valorizzazione del parametro height. 

## Possibili soluzioni

Vorrei inizialmente comprendere il motivo che ha portato a questa limitazione prima di procedere alla modifica del file _headerslim.scss (riga 94, 97, 111 e 139) per la rimozione del parametro height e rimozione del parametro $header-slim-height (riga 403 del file _variables.scss).

**Comment by astagi** [comment]
@PiemP all'epoca era stata una richiesta esplicita dei designer per mantenere una dimensione identica fra i vari siti PA. Volendo si può fare comunque override della variabile.
