### ISSUE TITLE
Interfaccia grafica – Componente Alert

### ISSUE THREAD

**Issue by RCPrato** [italia/bootstrap-italia#665]
## Comportamento atteso

I messaggi del componente Alert dovrebbero essere più evidenti e distinguibili tra loro.

## Comportamento attuale

Gli stili del componente Alert sono stati ridefiniti aggiungendo un’icona grafica per ogni tipo di messaggio e limitando l'uso del colore al solo bordo sinistro.

L'aggiunta dell'icona grafica va a correggere l'errore degli stili standard di bootstrap che prevedono solo l’utilizzo del colore, però la soluzione adottata secondo noi presenta ancora dei difetti in quanto le icone non sono facilmente distinguibili tra loro. Per fare un esempio, nei messaggi di tipo "warning" e di tipo "danger" viene utilizzato il punto esclamativo (!) e l'unica cosa che li distingue è la forma del bordo, rotonda in una e ottagonale nell'altra. Il tondo e l'ottagono sono forme molto simili tra loro e, per chi ha problemi di vista, non è immediato distinguere una dall'altra.

Anche la scelta di limitare l'uso del colore al solo bordo sinistro secondo noi è fallimentare perché non da alcun vantaggio, anzi, crea uno svantaggio agli utenti con una capacità visiva normale che potrebbero distinguere l'informazione in modo rapido a "colpo d’occhio".

Per finire, le scelte dei colori potrebbero essere più efficaci, ad esempio, sempre nel caso dei due messaggi di "warning" e "danger", i colori adottati sono molto "simili" tra loro.

## Possibili soluzioni

Noi proponiamo di:
- tornare all’uso del colore di sfondo su tutta l’area come da standard di Bootstrap, eventualmente con l’aggiunta di un bordo sempre dello stesso colore ma di tono più scuro
- utilizzare per l’alert di tipo “danger” e “warning” i colori di sfondo standard di Bootstrap, con colori di primo piano che passino l'algoritmo di validazione
- utilizzare per l’alert di tipo “danger” l’icona a forma di X dentro un bordo tondo
- utilizzare per l’alert di tipo “warning” l’icona a forma di punto esclamativo (!) dentro un bordo tondo

**Comment by astagi** [comment]
Buongiorno @RCPrato e grazie per le informazioni utili, giro sicuramente al team. Una soluzione potrebbe essere anche quella di allineare gli alert con quelli della versione basata su Bootstrap 5 i quali contengono le i cone colorate come il bordo, non so se può migliorare la situazione

![image](https://user-images.githubusercontent.com/537363/167582047-b425c6ea-dd09-46f7-9446-026b8b6fb6f4.png)

**Comment by RCPrato** [comment]
Abbiamo analizzato la questione e cercato di ipotizzare una soluzione grafica per le aree che:
1. mantengano un adeguato contrasto/luminosità dei colori
2. utilizzino icone ben riconoscibili per l'utente,  siano esplicative rispetto al messaggio da veicolare e coerenti con altri messaggi (vedi per esempio la X per rappresentare l'errore sia nel componente alert sia nel messaggio di errore specifico per ogni singolo campo di input in una form);
3. siano immediatamente visibili per l'utente rispetto qualsiasi altro messaggio presente nella pagina.

Chiaramente utilizzando le classi di bootstrap 5 e personalizzandole in modo da ottenere il risultato che vedete nello screenshot.
![screenshot-componente-alert](https://user-images.githubusercontent.com/26006220/169341119-8bbaa8fe-78c2-4987-b5ee-153849fdb912.jpg)

**Comment by zetareticoli** [comment]
Ciao @RCPrato, grazie della segnalazione.

Il componente in oggetto sarà aggiornato in base alla [nuova versione del kit UI](https://www.figma.com/community/file/1105848677422572920) che è stata pubblicata sulla community di Figma in versione alpha.3

Sicuramente quanto da te evidenziato sulle icone può essere preso in esame per una differenziazione più efficace.

I suggerimenti relativi ad un maggiore uso dei colori saranno discusse internamente e ti faremo sapere. L'obiettivo di base di ogni componente è di essere adattabile a scenari molto diversi. 

Ad esempio, l'uso di uno sfondo colorato è congeniale a messaggi di status molto brevi. Funziona meno per messaggi più lunghi. Tutto deve essere bilanciato. Salvo che, comunque, nelle implementazioni c'è libertà di customizzazione.
