### ISSUE TITLE
Aggiungere documentazione per modal-xl

### ISSUE THREAD

**Issue by astagi** [italia/bootstrap-italia#666]
Attualmente ci sono solo modal-sm e modal-lg (500px)

ref. https://github.com/italia/developers.italia.it/blob/master/assets/js/components/Search/SearchModal.js#L14

**Comment by Fupete** [comment]
@astagi il link ref. si riferisce alla possibilità di integrare una nuova modale "full-screen", da inserire nel codice oltre che nella documentazione quindi.

Il riferimento corretto per la classe `modal-xl`, già usabile oggi in Boostrap Italia perché ereditata da Bootstrap, è questo: https://getbootstrap.com/docs/4.6/components/modal/#optional-sizes 😃

**Comment by Fupete** [comment]
Just to know... this is issue #666 😈 🔴 🔥

**Comment by astagi** [comment]
@Fupete 😁 👹

closed by https://github.com/italia/bootstrap-italia/commit/f008fbba712522ec7c040737d049ccdf6d15ea2d
