### ISSUE TITLE
dropdown non funzionante

### ISSUE THREAD

**Issue by StefanoFlamigni** [italia/bootstrap-italia#667]
E' un problema verificato su https://italia.github.io/bootstrap-italia/docs/esempi/template-vuoto/# (in cui non compaiono le icone)
se restringo la pagina fino a fare "comparire" l'hamburger, apro il menu a scomparsa, clicco sul dropdown, chiudo il menu a scomparsa e riallargo la finestra, se a questo punto provo a riaprire il menu dropdown non si apre. 
In alcuni casi ho notato si verifica la stessa cosa per il megamenu.

**Comment by astagi** [comment]
Ciao @StefanoFlamigni grazie della segnalazione! provvedo a sistemare le icone, intanto ti dico che non riesco a riprodurre il tuo bug. Puoi fornire un video? te ne sarei davvero grato!

**Comment by StefanoFlamigni** [comment]
Eccolo, come puoi vedere alla fine non si apre più il menu...(ho usato edge nel video ma ho provato anche firefox e chrome con lo stesso risultato)
https://user-images.githubusercontent.com/63600770/171120397-7ffe568e-c651-45b1-83ce-c6f5ee59d98f.mp4

**Comment by astagi** [comment]
Grazie @StefanoFlamigni ora dovrebbe essere risolto puoi controllare dalla preview di Vercel nella Pull Request
