### ISSUE TITLE
Dropdown - Menu icona a sinistra non centrate

### ISSUE THREAD

**Issue by sabato-galasso** [italia/bootstrap-italia#670]
## Comportamento atteso

Menù icona a sinistra non è centrato come menù icona a destra di default.

Differenza tra i due menù:
![Schermata 2022-05-23 alle 10 38 34](https://user-images.githubusercontent.com/52424004/169779357-687eba42-36aa-4573-9ca4-5d50501d0d5e.png)
![Schermata 2022-05-23 alle 10 38 24](https://user-images.githubusercontent.com/52424004/169779364-970df749-b08f-4e15-97dc-2ab644c3d751.png)

**Comment by astagi** [comment]
@sabato-galasso ho aperto una PR ad hoc, è il comportamento atteso?

**Comment by sabato-galasso** [comment]
Si, grazie per la risoluzione!
