### ISSUE TITLE
Nell'header centrale in versione light, l'icona it-burger ha lo stesso colore dello sfondo

### ISSUE THREAD

**Issue by andrea-conforto** [italia/bootstrap-italia#675]
Nella versione 1.6.3 e nelle precedenti l'icona hamburger ha lo stesso colore dello sfondo. Questo avviene solo quando l'Header centrale è light.

**Comment by andrea-conforto** [comment]
Un problema analogo è stato segnalato nella versione **bootstrap-italia-next**. Il file ed il fix sono gli stessi  così come indicato nel [rif #35](https://github.com/italia/bootstrap-italia-next/issues/35).

**Comment by astagi** [comment]
@andrea-conforto potresti aprire una PR con l'analogo fix? almeno possiamo verificare, mergiare e rilasciare una nuova versione :) grazie!

**Comment by astagi** [comment]
grazie infinite @andrea-conforto !!
