### ISSUE TITLE
Install con npm

### ISSUE THREAD

**Issue by dvero23** [italia/bootstrap-italia#678]
## Comportamento atteso

Poter gestire bootstrap-italia come dipendenza (`npm install bootstrap-italia`) senza dover importare script o altro sulla pagina html, ma con `import 'bootstrap-italia';`

## Comportamento attuale

Installando **bootstrap-italia** come dipendenza con npm e facendo `import 'bootstrap-italia';` in _main.ts_ (nel mio caso), ho un errore a console per non aver installato jquery. Installandolo a parte e importandolo per primo, c'è sempre lo stesso errore.
Ho visto che dipende dal fatto che l'import prende la versione _min_ che non include jquery e popper. Sul sito è indicato di includere lo script scelto (bundle o min) nella pagina HTML.

**Comment by astagi** [comment]
Ciao @dvero23 si esatto, nella main del package è specificata la versione senza dipendenze. Aggiungendo jQuery dalla pagina HTML dovrebbe risultare tutto ok. Fammi sapere!

**Comment by dvero23** [comment]
Ciao @astagi facendo così funziona, ma mi chiedevo se si potesse fare senza dover toccare la pagina HTML.
Comunque essendo uscita la versione 2.x, adesso non ho più questo problema da gestire. E' più una curiosità mia a questo punto.
