### ISSUE TITLE
Errore nel controllo di caricamento di jquery

### ISSUE THREAD

**Issue by bobonov** [italia/bootstrap-italia#680]
bootstrap italia v1.6.4
Utilizzando il template base di esempio (hello world)
L'errore riportato si verifica sia utilizzando bootstrap-italia.bundle.min.js che utilizzando bootstrap-italia.min.js e includendo jquery separatamente prima del js di boostrap Italia 

## Comportamento atteso
La pagina si deve  caricare senza errori nel debug del browser.

## Comportamento attuale
si verifica un errore nel caricamento della pagina
Uncaught ReferenceError: jQuery is not defined
    <anonymous> http://localhost:81/build/assets/bootstrap-italia.bundle.min.acb153d3.js:10
    <anonymous> http://localhost:81/build/assets/bootstrap-italia.bundle.min.acb153d3.js:282

**Comment by bobonov** [comment]
Ho capito il problema, l'errore si verifica quando il bundle javascript viene incluso come type="module"
Questo crea qualche problema con i sistemi che pubblicano automaticamente gli assets dove non è detto che si possa avere un controllo così preciso sulla pubblicazione

**Comment by astagi** [comment]
Buongiorno @bobonov si includerlo specificando type="module" non è corretto, visto che riguarda solo file js che sono moduli.

Chiudo come risolto.
