### ISSUE TITLE
💬 Errore documentazione

### ISSUE THREAD

**Issue by dvero23** [italia/bootstrap-italia#682]
## Comportamento attuale

E' presente un errore alla pagina [Linked List](https://italia.github.io/bootstrap-italia/1.x/docs/organizzare-i-contenuti/liste-di-link/#primary-e-secondary-action)

![image](https://user-images.githubusercontent.com/106613927/180229709-da2f99af-6649-4d50-b7d6-21f4f6ec4510.png)

Dovrebbe essere a destra, non a sinistra.

**Comment by astagi** [comment]
@dvero23 risolto in https://github.com/italia/bootstrap-italia/commit/22e4e565753176ada253b200991710203dd0274c

Ti ricordo che la documentazione adesso per la versione 1 si trova al link https://italia.github.io/bootstrap-italia/1.x/ e il relativo branch su GitHub è `1.x`
