### ISSUE TITLE
Adattare il componente cookiebar alle indicazioni del Garante della Protezione dei dati personali del 21 giugno 2021

### ISSUE THREAD

**Issue by bondvaleria** [italia/bootstrap-italia#686]
## Comportamento atteso

Il cookie banner, secondo le indicazioni del GPDP (vedi FAQ: https://www.garanteprivacy.it/faq/cookie ) dovrebbe:

1. contenere un testo informativo sintetico con il link all’informativa privacy estesa
2. contenere una x di chiusura del banner in alto a destra
3. precisare, nel testo, che, chiudendo il banner, saranno mantenute le impostazioni predefinite che **non** consentono l’utilizzo di cookie o altri strumenti di tracciamento diversi dai tecnici.
4. in caso di nessuna esplicita scelta da parte dell'utente (scrolling o prosecuzione della navigazione), i cookie non si possono intendere come accettati

## Comportamento attuale

1. manca un testo informativo sintetico con il link all’informativa privacy estesa
2. manca una x di chiusura del banner in alto a destra
3. manca la precisazione che, se l’utente sceglie di chiudere il banner utilizzando il pulsante con la X, saranno mantenute le impostazioni predefinite che **non** consentono l’utilizzo di cookie o altri strumenti di tracciamento diversi dai tecnici.
4. in caso di nessuna esplicita scelta da parte dell'utente (scrolling o prosecuzione della navigazione), i cookie si intendono accettati

## Possibili soluzioni

1. aggiungere un testo informativo sintetico con il link all’informativa privacy estesa
2. aggiungere una x di chiusura del banner in alto a destra
3. precisare che, se l’utente sceglie di chiudere il banner utilizzando il pulsante con la X, saranno mantenute le impostazioni predefinite che **non** consentono l’utilizzo di cookie o altri strumenti di tracciamento diversi dai tecnici.
4. non rendere automatica l'accettazione dei cookie e togliere la frase "Proseguendo nella navigazione accetti l’utilizzo dei cookie."

## Contesto

Il Garante per la Protezione del Dati Personali, con provvedimento del 10 giugno 2021, ha rivisto le sue linee guida del 2014 aggiungendo le novità determinate anche dal parere n. 5/2020 del 4 maggio 2020 dell'European Data Protection Board (EDPB). Tra queste novità, si fa esplicito riferimento al fatto, tra le altre cose, che l'accettazione dei cookie deve essere esplicita, non collegata al semplice scroll della pagina o alla prosecuzione della navigazione.
https://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/9677876

**Comment by astagi** [comment]
Bump
