### ISSUE TITLE
Errore documentazione Margini automatici Flex

### ISSUE THREAD

**Issue by Gio4Everr** [italia/bootstrap-italia#693]
## Comportamento atteso

Le classi non sono corrette e non non quelle (.me-auto e .ms-auto). Sessione documentazione consultabile al link
https://italia.github.io/bootstrap-italia/docs/organizzare-gli-spazi/flex/
nel paragrafo margini automatici.

## Possibili soluzioni

Quelle corrette da inserire in documentazione sono .mr-auto e .ml-auto

**Comment by mariantanase** [comment]
Che io sappia, le classi .mr-auto e .ml-auto sono classi di bootstrap 4.
In bootstrap 5 sono sostituite con .ms-auto e .me-auto

**Comment by Gio4Everr** [comment]
> Che io sappia, le classi .mr-auto e .ml-auto sono classi di bootstrap 4.
> In bootstrap 5 sono sostituite con .ms-auto e .me-auto

Mia colpa stavo lavorando su la release di due mesi fa. Corretto
