### ISSUE TITLE
AutoComplete  dinamico con chiamata ajax

### ISSUE THREAD

**Issue by stefanodesimone** [italia/bootstrap-italia#702]
## Versione di Bootstrap Italia
versione di Bootstrap Italia 1.6.3

## Comportamento atteso
Far scattare l'autocomplete dopo l'inserimento del terzo carattere

## Comportamento attuale
Abbiamo provato ad utilizzare l'autocomplete senza chiamata ajax

```js
var inputElement = document.getElementById('autocomplete-test')
var inputSearch = new bootstrap.InputSearch(inputElement, {
  autocomplete: '[{"text":"Abruzzo","link":"#"},{"text":"Basilicata","link":"#"},{"text":"Calabria","link":"#"},{"text":"Campania","link":"#"},{"text":"Emilia Romagna","link":"#"},{"text":"Friuli Venezia Giulia","link":"#"},{"text":"Lazio","link":"#"},{"text":"Liguria","link":"#"},{"text":"Lombardia","link":"#"},{"text":"Marche","link":"#"},{"text":"Molise","link":"#"},{"text":"Piemonte","link":"#"},{"text":"Puglia","link":"#"},{"text":"Sardegna","link":"#"},{"text":"Sicilia","link":"#"},{"text":"Toscana","link":"#"},{"text":"Trentino Alto Adige","link":"#"},{"text":"Umbria","link":"#"},{"text":"Valle d’Aosta","link":"#"},{"text":"Veneto","link":"#"}]',
})
```
Errore  "InputSearch" non è un costruttore valido

Dove è possibile trovare un **esempio** di autocomplete dinamico con chiamata ajax a metodo remoto?

Grazie
Stefano

**Comment by astagi** [comment]
@stefanodesimone hai provato questo esempio https://italia.github.io/bootstrap-italia/1.x/docs/form/autocompletamento/ ?
