### ISSUE TITLE
Le icone di Bootstrap Italia non compaiono

### ISSUE THREAD

**Issue by mariantanase** [italia/bootstrap-italia#703]
## Versione di Bootstrap Italia
Bootstrap Italia 2.0.2

## Comportamento atteso
Le icone devono essere visibili

## Comportamento attuale
Le icone non compaiono

## Contesto
Creata una semplice pagina HTML di esempio secondo le istruzioni sul sito.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="bootstrap-italia.min.css" />
</head>
<body>
<h1>
<svg class="icon"><use href="sprites.svg#it-tool" xlink:href="sprites.svg#it-tool"></use></svg>
<svg class="bg-light icon icon-lg"><use href="sprites.svg#it-check-circle"></use></svg>
<svg class="icon icon-warning bg-light"><use href="sprites.svg#it-check-circle"></use></svg>

</h1>

<script src="bootstrap-italia.bundle.min.js"></script>
</body>
</html>
```
Caricati nella root i file:

- bootstrap-italia.min.css
- bootstrap-italia.bundle.min.js
- sprites.svg

**Comment by astagi** [comment]
Ciao @mariantanase ho provato ad eseguire il tuo codice mettendo Bootstrap Italia in una cartella `dist`

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link rel="stylesheet" href="dist/css/bootstrap-italia.min.css" />
</head>
<body>
  <h1>
    <svg class="icon">
      <use href="dist/svg/sprites.svg#it-tool" xlink:href="dist/svg/sprites.svg#it-tool"></use>
    </svg>
    <svg class="bg-light icon icon-lg">
      <use href="dist/svg/sprites.svg#it-check-circle"></use>
    </svg>
    <svg class="icon icon-warning bg-light">
      <use href="dist/svg/sprites.svg#it-check-circle"></use>
    </svg>
  </h1>
  <script src="dist/js/bootstrap-italia.bundle.min.js"></script>
</body>
</html>
```

la risultante è stata questa

<img width="167" alt="image" src="https://user-images.githubusercontent.com/537363/185906231-97682a52-a241-4038-9446-b822f99f2622.png">

**Comment by mariantanase** [comment]
Ciao @astagi ,
Ho creato anch'io una cartella "dist" con le sottocartelle che hai menzionato e dove ho inserito i file, ma nulla cambia. Non ho capito perché creare una cartella dist.
Io ho scaricato il pacchetto zip e presso solamente i fine necessari per creare una semplice html. Sbaglio ?

https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/
`Per utilizzare il codice compilato di Bootstrap Italia nel proprio progetto, è sufficiente scaricare ed includere nella pagina HTML alcuni file, tra cui un file CSS, un Javascript, i fonts e una SVG sprite, il tutto scaricabile qui`
Forse non e chiara la documentazione nell'utilizzo delle librerie bootstrap-italia.

L'utilizzo di Bootstrap Italia 2.0.2 non dovrebbe funzionare nello stesso modo come Bootstrap 5.2 ?

**Comment by astagi** [comment]
Secondo me @mariantanase stai forse sbagliando la path nell'html, in ogni caso ti lascio qua uno zip della demo funzionante, la cartella `dist` è assolutamente facoltativa, l'ho messa solo per separare la libreria dal resto. Se trovi alcuni punti della doc da sistemare fammi sapere :) Grazie!

📦 [Scarica pacchetto demo (bs-demo.zip)](https://github.com/italia/bootstrap-italia/files/9402860/bs-demo.zip)

**Comment by mariantanase** [comment]
Ti ringrazio per la pazienza, ho scaricato, scompattato lo zip, aperto index.html.
Ecco come vedo io la pagina:

![icone-bs-mancanti](https://user-images.githubusercontent.com/3976174/186183167-c448da1a-3e6d-4e22-88ff-a0c12caff158.png)

**Comment by mariantanase** [comment]
Ok, credo di aver risolto con la visualizzazione delle icone svg.
In Firefox (about:config) ho modificato le impostazioni per "**security.fileuri.strict_origin_policy**" a "**false**".
Non so se è la soluzione giusta.
Adesso le icone si vedono  correttamente.
![icone-svg-ok](https://user-images.githubusercontent.com/3976174/186362384-62812ffe-edc6-4946-a40e-826f03f66aeb.png)
Devo indagare per gli altri errori che escono, quelli di downloadable font..., magari apriro una issue diversa.

**Comment by astagi** [comment]
Esatto @mariantanase dalle tue valutazioni risulta essere proprio un problema di policy del browser. Per aggirare questo problema io di solito faccio partire un server locale che mi serve index.html e di conseguenza tutti gli asset a partire dalla root. Puoi utilizzare ad esempio [questo validissimo server per Node](https://www.npmjs.com/package/http-server). Chiudo la issue come risolta.

Buon lavoro!
