### ISSUE TITLE
Citazioni: problema padding ed elemento decorativo dark

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia#704]
## Versione di Bootstrap Italia
v2.0.2

## Comportamento atteso
Il testo non dovrebbe essere attaccato al bordo, nel caso di card dark non dovrebbe essere visualizzato l'elemento decorativo di colore ciano.

## Comportamento attuale
Quando si usa l'opzione `blockquote-simple` con `text-end` il testo della citazione è attaccato all'elemento grafico decorativo della citazione.

![Schermata del 2022-08-19 11-19-41](https://user-images.githubusercontent.com/4628942/185587663-394890f6-26a6-4dcc-a4f6-6b05d0ff11e7.png)

Quando si usa l'opzione `blockquote-card dark` con `text-end` viene visualizzato un elemento decorativo di colore ciano che non dovrebbe esserci

![Schermata del 2022-08-19 11-27-15](https://user-images.githubusercontent.com/4628942/185589084-86e57eb4-1d6f-4792-ac2b-e7ddb3fa1189.png)

Ciao

**Comment by astagi** [comment]
@arturu fixata da @OscarBresolin e rilasciata nuova versione 2.0.3

<img width="972" alt="image" src="https://user-images.githubusercontent.com/537363/186434423-4796bdbb-7cbf-43e5-99bb-95c0f1e8591e.png">
