### ISSUE TITLE
Link errati barra ricerca algolia (documentazione v1.x)

### ISSUE THREAD

**Issue by kedniko** [italia/bootstrap-italia#705]
## Versione Documentazione Bootstrap Italia
1.x

## Comportamento atteso
I risultati della barra di ricerca di algolia della documentazione di bootstrap versione 1.x dovrebbero puntare alla versione 1.x della documentazione (esempio: _https://italia.github.io/bootstrap-italia/1.x/docs/..._)

## Comportamento attuale

I risultati della barra di ricerca di algolia della documentazione di bootstrap versione 1.x reindirizzano (in modo errato) sempre verso la **nuova versione della documentazione** (esempio: _https://italia.github.io/bootstrap-italia/docs/..._)

**Comment by astagi** [comment]
Grazie @kedniko indaghiamo subito!

**Comment by astagi** [comment]
Pushato il fix sulla 1.x vediamo se funziona 🤞🏻

**Comment by astagi** [comment]
Fixato, ancora grazie @kedniko
