### ISSUE TITLE
Componente timeline breakpoint xs

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia#708]
## Versione di Bootstrap Italia
2.0.3

## Comportamento atteso
pin-text e pin-icon forse non si dovrebbero sovrappore in cima al componente, non so se è una cosa voluta ma se c'è una label più lunga (pin-text) si nota subito il problema.

## Comportamento attuale
pin-text e pin-icon si sovrappongono in cima al componente

![Schermata del 2022-08-26 18-48-58](https://user-images.githubusercontent.com/4628942/186954109-28b42ab3-c7f3-4b0e-82ff-0f87229625b0.png)

**Comment by OscarBresolin** [comment]
Ciao @arturu, non ho capito a cosa si fa riferimento. Se simulo a browser il comportamento mi sembra corretto. La timeline parte sempre con una linea verticale che distanzia il primo pin
![image](https://user-images.githubusercontent.com/38532141/187615852-a4f7ae1b-0eff-4b70-84e9-cae1a8f22090.png)

**Comment by arturu** [comment]
Ciao @OscarBresolin, scusa mi sa che ho scritto frettoloso e non si capisce.
Gli step per riprodurre sono:

- Visualizza https://italia.github.io/bootstrap-italia/docs/componenti/timeline/ 
- Riduci la finestra del browser fino a simulare il breakpoint più piccolo

Tutti gli elementi `it-pin-wrapper` si sovrappongono in cima al componente. Se il testo contenuto nei vari nodi `pin-text` è sempre della stessa lunghezza il problema non è evidente, invece, nel caso in cui il testo nei nodi `pin-text` è di lunghezza casuale il problema è evidente. Es:


![Schermata del 2022-08-31 09-39-00](https://user-images.githubusercontent.com/4628942/187620907-f84a64ee-1a04-4d27-af82-222bc00fb109.png)

**Comment by OscarBresolin** [comment]
Ciao @arturu , grazie. Fixo subito

**Comment by arturu** [comment]
A linea 36

https://github.com/italia/bootstrap-italia/blob/554abd7bd97d1e52941cc9aaff83e6e8c6820ac5/src/scss/custom/_timeline.scss#L36

Forse `$timeline-padding;` non ci dovrebbe essere perché da come output `12px` e l'icona è decentrata rispetto alla linea:

![Schermata del 2022-08-31 11-47-31](https://user-images.githubusercontent.com/4628942/187650499-43e3d21b-a9f4-428f-9db7-f9bf9f373495.png)

con un valore di `6px` risulta centrata in tutti i breakpoint

![Schermata del 2022-08-31 11-49-02](https://user-images.githubusercontent.com/4628942/187650786-7eb66521-4cd9-453f-95b0-4b759e1050e0.png)

Non ho fatto una PR perché non so se è meglio dividere per due `$timeline-padding;` oppure scrivere direttamente `6px`.

**Comment by OscarBresolin** [comment]
$timeline-padding / 2 è la soluzione migliore, faccio io?

**Comment by arturu** [comment]
Ho inviato una PR :)

**Comment by astagi** [comment]
Grazie @arturu e @OscarBresolin 💪
