### ISSUE TITLE
funzione notificationShow non presente in bundle 2.0.3

### ISSUE THREAD

**Issue by rudy1976s** [italia/bootstrap-italia#711]
## Versione di Bootstrap Italia

2.0.3
## Comportamento atteso

funzionamento delle notifiche

## Comportamento attuale

`Uncaught ReferenceError: notificationShow is not defined
`
Ho seguito alla lettera l'implementazione e scaricato dalla repository l'ultima versione: 2.0.3,  ma le notifiche non funzionano più : ho provato a guardare dentro il file di bundle ma funzione notificationShow non c'è più.

**Comment by astagi** [comment]
@rudy1976s grazie della segnalazione verifichiamo. Una domanda, che versione usavi precedentemente? questa funzionalità andava correttamente?

**Comment by rudy1976s** [comment]
Usavo  l'ultima precedente il branch 2.
Ho verificato nel file minimized la funzione non c'è , mentre nel branch precedente era presente.

Saluti

Rudy

**Comment by astagi** [comment]
@rudy1976s sembra che la funzione non sia implementata, io in [questa demo](https://github.com/astagi/demo-bsitalia-2/blob/develop/demo.entry.js) ho utilizzato la classe Alert. Guarda anche il codice [qua](https://italia.github.io/bootstrap-italia/docs/esempi/notifications/). Mi informo comunque e ti faccio sapere, grazie!

**Comment by astagi** [comment]
@rudy1976s no no hai ragione, il fix è in progress, appena abbiamo aggiornamenti rilasceremo una nuova versione!

**Comment by astagi** [comment]
@rudy1976s documentazione aggiornata con l'attuale implementazione delle notifiche! Grazie ancora della segnalazione!

Riferimento: https://italia.github.io/bootstrap-italia/docs/componenti/notifiche/
