### ISSUE TITLE
Testo di aiuto per i campi input

### ISSUE THREAD

**Issue by nicolabove1** [italia/bootstrap-italia#719]
## Versione di Bootstrap Italia

2.0.3

## Comportamento atteso

Input con testo aggiuntivo ha del margine in più

## Comportamento attuale

Nella documentazione è presente codice css del tipo: 
.bd-example>.form-group:last-child {
    margin-bottom: 1rem;
}
questo comporta meno margine fra il campo input e il tag small contenente del testo integrativo.

**Comment by astagi** [comment]
Figurati! se vuoi condividere la soluzione per qualcun altro che può avere lo stesso problema ben venga, scrivi pure in questo thread :) a presto!
