### ISSUE TITLE
Icone mancanti nella documentazione del componente tabs

### ISSUE THREAD

**Issue by Fupete** [italia/bootstrap-italia#724]
## Versione di Bootstrap Italia
2.0.4

## Problema 
Documentazione del componente Tabs non mostra le icone in alcuni esempi: https://italia.github.io/bootstrap-italia/docs/componenti/tab/

## Possibili soluzioni
Le icone svg sono referenziate talvolta con un src che comincia con /bootstrap-italia/dist... e funzionano. Quelle invece solo /dist/... no. Uniformare alla prima soluzione?

**Comment by astagi** [comment]
Messo il fix in branch `main`
