### ISSUE TITLE
Icone Social aggiuntive

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#728]
## Versione di Bootstrap Italia

2.0.4

## Comportamento atteso

è possibile aggiungere ulteriori icone social alla sprite?

## Comportamento attuale

Elenco parziali di social aggiuntivi:
- Vimeo
- TikTok
- Pinterest

**Comment by AlessandroVecchi** [comment]
Altra icona assolutamente necessaria è quella del log out.
Nel modello comuni è stata associata al pulsante "esci" l'icona dei link esterni che è concettualmente sbagliata.

![immagine](https://user-images.githubusercontent.com/20642463/191513657-a3165557-a6bd-4b77-b580-14b059c60209.png)

**Comment by astagi** [comment]
@AlessandroVecchi qua la preview https://bootstrap-italia-axunlk9at-dip-trasformazione-digitale.vercel.app/docs/utilities/icone/
