### ISSUE TITLE
Floating labels non funzionanti (Angular 12)

### ISSUE THREAD

**Issue by AntoninoBonanno** [italia/bootstrap-italia#729]
## Versione di Bootstrap Italia

^2.0.4 (Tramite npm)

Importazione scss: `@import "bootstrap-italia/src/scss/bootstrap-italia";`

## Comportamento atteso
Mi aspetto il classico comportamento delle floating labels come da [documentazione](https://italia.github.io/bootstrap-italia/docs/form/input/) 

## Comportamento attuale
La label non si rimpicciolisce

```
<div class="form-group">
    <label for="form-title">Titolo form</label>
    <input type="text" class="form-control" id="form-title">
  </div>
```
![Cattura1](https://user-images.githubusercontent.com/56137431/191940788-1e98304a-f102-4e99-85fc-53af47aa209e.PNG)
![Cattura2](https://user-images.githubusercontent.com/56137431/191940791-0d16b9c3-faa0-4ffe-9ffe-7a768af011c4.PNG)

**Comment by OscarBresolin** [comment]
Ciao @AntoninoBonanno, ho testato ora in locale e funziona correttamente.
Hai importato il js bootstrap-italia.bundle.min.js?

**Comment by AntoninoBonanno** [comment]
Ciao @OscarBresolin si, 
ho provato ad includerlo in uno dei seguenti modi 
- npm:
  - nel campo scripts dell'angular.json (Mi sono dimenticato di specificare che lo sto utilizzando in Angular)
  - nell'head dell'index.html
  - alla fine del body dell'index.html
- locale:
  - Scaricato bootstrap-italia
  - Inserito nella cartella assets
  - Messi i riferimenti di css e js nell'index.html utilizzando

In tutti questi modi, sia css che js vengono caricati, infatti uso gli altri elementi senza problemi (come ad esempio gli Accordion)

![Cattura1](https://user-images.githubusercontent.com/56137431/193051595-814873ea-ed7a-4a3b-a082-cb7a138b83ea.PNG)

Ho notato che se inserisco l'input nel file index.html le floating labels funzionano, se invece lo inserisco all'interno di un componente Angular (ad esempio app.component.html) le floating labels non funzionano
![Cattura2](https://user-images.githubusercontent.com/56137431/193057714-fbf3f7a7-560e-439c-b928-9cd9a84515fe.PNG)
![Cattura3](https://user-images.githubusercontent.com/56137431/193057718-663b0d98-5a4a-4def-a998-bc94979c051b.PNG)

**Comment by fabioportieri** [comment]
seguo, abbiamo lo stesso problema
sapete di un workaround, o il numero di versione passato per cui questo problema non si presenta? (testato su angular 13 e 14)
sulla vecchia versione bootstrap italia 1.4.0 (angular 13) il problema non c'e'

**Comment by astagi** [comment]
@AntoninoBonanno @fabioportieri potrebbe essere un problema relativo al two way binding di Angular? ovvero del JS che viene eseguito in contemporanea e porta a questo bug grafico? se non mettete il binding sull'input continua a presentarsi questo problema?

**Comment by fabioportieri** [comment]
@astagi nell'esempio di @AntoninoBonanno come vedi non viene fatto nessun binding da Angular:

```
<div class="form-group">
    <label for="form-title">Titolo form</label>
    <input type="text" class="form-control" id="form-title">
  </div>
```

**Comment by astagi** [comment]
Vero @fabioportieri molto strano.. sembra proprio il JS comunque, forse il loading dei componenti angular viene fatto a posteriori, la classe CSS viene applicata correttamente ma non viene reinizializzato il campo input. Occorrerebbe un componente ad hoc che inizializza l'input di testo con il JS di Bootstrap Italia, avete provato ad importare il solo componente e ad inizializzare l'input solo after init?

**Comment by astagi** [comment]
@fabioportieri @AntoninoBonanno vi passo un piccolo esempio di una app angular che usa però il drop down e l'import dei componenti

```ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Dropdown } from 'bootstrap-italia';

@Component({
 // ....
})
export class HeaderComponent implements OnInit, OnDestroy {
  ngOnInit(): void {
    new Dropdown(document.querySelector('#select-language-loggedin'));
    new Dropdown(document.querySelector('#select-profile'));
  }
```

io farei all'`ngAfterViewInit` mi sembra più corretto, ma il concetto è sostanzialmente questo.. appena siamo sicuri che il componente è istanziato da Angular facciamo girare la parte JavaScript di Bootstrap Italia.

**Comment by AntoninoBonanno** [comment]
Non riesco a importare la libreria nel codice TS (sembra che i types non vengano riconosciuti)

`TS2307: Cannot find module 'bootstrap-italia' or its corresponding type declarations.`

![Cattura](https://user-images.githubusercontent.com/56137431/194261387-09e5e752-c375-407a-8c9b-c2003905d030.PNG)

Ho provato anche `import { Dropdown } from 'bootstrap-italia';`, stesso risultato.

Se utilizzo il `// @ts-ignore` nell'import, utilizzando la classe forzatamente degli errori di compilazione.


Inoltre ho provato a rimuovere l'import e digitare da console di Chrome  `new Input(document.getElementById('input-id'))` ma la classe Input non viene riconosciuta, stesso risultato con la classe Dropdown.


Nota: ho usato `import { Input as BootstrapInput }` poichè esiste `import {Input} from '@angular/core';`

**Comment by astagi** [comment]
@AntoninoBonanno grazie del report! ho paura ci sia un errore con i tipi allora.. Potresti provare a fare la seguente modifica? Vai in `node_modules/bootstrap-italia` e nel package.json modifica l'attributo `types` (https://github.com/italia/bootstrap-italia/blob/main/package.json#L14). Come vedi il contenuto dovrebbe essere 

```json
"types": "./types/decs.d.ts"
```

e non com'è ora.. riavvia poi il progetto (e vscode stesso) e dimmi se funziona :)

**Comment by astagi** [comment]
@AntoninoBonanno prova a mettere quei css negli style di angular.json

```
"styles": ["./node_modules/@splidejs/splide/dist/css/splide-core.min.css", "./node_modules/accessible-autocomplete/dist/accessible-autocomplete.min.css"]
```

in modo che riesca a parsarli a dovere. [Maggiori informazioni](https://github.com/angular/angular-cli/issues/23273).

**Comment by astagi** [comment]
@AntoninoBonanno avevo dimenticato di precisare: ovviamente non rimuovere gli altri styles se ci sono, ma aggiungili e basta :)

**Comment by AntoninoBonanno** [comment]
Funziona. Grazie 😁

**Comment by astagi** [comment]
Figurati @AntoninoBonanno :) fammi sapere se pure le floating label funzionano così chiudiamo la issue!

**Comment by AntoninoBonanno** [comment]
@astagi Sisi funziona tutto. Grazie ancora

**Comment by astagi** [comment]
Ottimo grazie a te :) a breve rilascio nuova versione con il fix dei types così non devi modificare direttamente in node_modules @AntoninoBonanno cc @fabioportieri
