### ISSUE TITLE
Nuova funzionalità "ribbon" ( nastro ) su angoli card

### ISSUE THREAD

**Issue by rudy1976s** [italia/bootstrap-italia#732]
## Versione di Bootstrap Italia

2.0.4

E' possibile creare un nuovo componente "ribbon" per poter applicare un piccolo "nastro" sugli angoli di una card ? Sarebbe una cosa molto utile e funzionale allo stesso tempo, scalabile magari con un titlo per l'usabilità.
Per capire meglio la richiesta, una cosa tipo questa soluzione fornita da un toolkit esterno : 
https://toruskit.com/docs/components/ribbons/

Grazie mille !!

Rudy

**Comment by AlessandroVecchi** [comment]
Ciao @rudy1976s è abbastanza semplice da fare, direi che non serve un componente perché si fa tutto in css, è sufficiente definire una classe.

**Comment by astagi** [comment]
Lascierei l'idea di @AlessandroVecchi , ovvero non creare un componente ad hoc ma semplicemente agire tramite CSS custom
