### ISSUE TITLE
card-img card-body con bordo o ombra: mantenere padding sinistra e destra

### ISSUE THREAD

**Issue by PiemP** [italia/bootstrap-italia#737]
## Versione di Bootstrap Italia

2.0.5

## Comportamento atteso

Quando vengono applicati bordi o ombre a un elemento card-img il contenuto testuale del card-body dovrebbe mantenere il padding a destra e a sinistra. Vedi immagine:

![con_padding](https://user-images.githubusercontent.com/2736009/194906748-82f811f1-1df9-4c1d-bffd-2cb8de54b33e.png)

## Comportamento attuale

Vedi immagine: 

![attuale](https://user-images.githubusercontent.com/2736009/194906840-3c68625e-5f33-4bb8-99e5-a4f61d8f9298.png)

## Possibili soluzioni

modificare il file _card.scss ed aggiungere il codice necessario per generare le seguenti regole: 

```
.card.card-img.shadow .card-body,
.card.card-img.border .card-body,
.card.card-img.border-start .card-body,
.card.card-img.border-end .card-body {
    padding-left: 24px;
    padding-right: 24px;
}
```
Dove 24px verrà derivato dal calcolo originale del padding relativo al `card-body`.

Oppure andrebbe rimossa la regola che va ad azzerare il padding a destra e a sinistra per il `card-body` associato a un elemento `card-img`.

**Comment by astagi** [comment]
Ciao @PiemP si il padding dovrebbe mantenersi tale. Puoi aprire una PR che va a risolvere questo problema?
