### ISSUE TITLE
dropdown-item

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#743]
## Versione di Bootstrap Italia

2.0.4

## Comportamento atteso

Effetto hover sul voci menu dropdown

## Comportamento attuale

in bootstrap-italia-comuni.min.css sono presenti 2 regole apparentemente in conflitto tra loro
```
.dropdown-item:hover,.dropdown-item:focus{color:#17324d;background-color:#e6ecf2}
.dropdown-item:hover,.dropdown-item:focus,.dropdown-item:active,.dropdown-item.active{background-color:rgba(0,0,0,0)}
```
Prevale la seconda essendo scritta dopo.
Inoltre gli item con classe .active durante l'hover diventa bianco su bianco.
Problema simile a quello descritto qui: https://github.com/italia/design-comuni-pagine-statiche/issues/37

## Possibili soluzioni

Ha senso che ci sia un effetto hover sui dropdown-item.
La soluzione più semplice sarebbe ripristinare il funzionamento standard di bootstrap
https://getbootstrap.com/docs/5.2/components/dropdowns/

**Comment by astagi** [comment]
Grazie @AlessandroVecchi ! Ci guardiamo, se hai modo di intervenire sul codice e vuoi aprire una PR come hai fatto su *Comuni pagine statiche* ben venga così facciamo review.

**Comment by AlessandroVecchi** [comment]
Ciao,
Il bug non è ancora stato risolto, volevo capire se sarà previsto oppure se mi conviene applicare una mia regola di override.
Grazie

**Comment by astagi** [comment]
@AlessandroVecchi come descritto nella PR bisogna fare un ragionamento a valle dell'inserimento dei token.. intanto si puoi andare di override.. ci siamo quasi a tal proposito! Grazie per la pazienza
