### ISSUE TITLE
Icone SVG non hanno tag `title`

### ISSUE THREAD

**Issue by dej611** [italia/bootstrap-italia#749]
## Versione di Bootstrap Italia 2.x & 1.x

Nella versione 2.x del kit il tag `<title>` è mancante per tutte le icone SVG (requisito di accessibilità).
Nella versione 1.x le seguenti icone non hanno il tag `<title>`:
 * it-rss-square.svg
 * it-rss.svg
 * it-software.svg
 * it-open-source.svg
 * it-piattaforme.svg
 * it-telegram.svg

## Comportamento atteso

Tutte le icone SVG (ma in generale tutte le SVG) dovrebbero avere il tag `<title>`

**Comment by astagi** [comment]
Riporto quanto detto da @cfabry che segue la parte di accessibilità

> A mio avviso è giusto che non ci siano i title nei file SVG negli esempi (quindi nei framework), per una questione di praticità. L’uso di title è solo uno dei modi con cui si può aggiungere supporto per l’accessibilità, ti incollo qui un link dove vengono illustrati una decina di metodi diversi. I tag title, text, desc, dentro SVG rimangono nascosti e in fase di sviluppo possono creare confusione. Nel nostro caso le SVG sono usate quasi esclusivamente al posto di png al solo fine di avere una resa più scalabile, quindi meglio usare i metodi più “visibili” al di fuori del tag SVG con alt, aria-label ecc. https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/
