### ISSUE TITLE
Classe su label dei toggles

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#753]
## Versione di Bootstrap Italia

2.0.x

## Comportamento attuale

Nella pagina https://italia.github.io/bootstrap-italia/docs/form/toggles/ la label ha sempre class="active" a prescindere dallo stato checked/non checked dell'interruttore

## Comportamento atteso

A mio parere la classe dovrebbe essere active solo se l'interruttore è attivo

**Comment by alenap93** [comment]
dal file _form-toggles.scss leggo:
```
&.active {
    transform: none;
    font-size: 1rem;
  }
```
non so se da qualche parte c'è scritto il comportamento atteso, ma con questo scss non porta nulla (visto anche l'albero)...perciò la presenza di quella classe mi sembra superflua...
