### ISSUE TITLE
back-to-top - back-to-top dietro it-bottom-navscroll

### ISSUE THREAD

**Issue by PiemP** [italia/bootstrap-italia#760]
## Versione di Bootstrap Italia

2.0.8

## Comportamento atteso

Pulsante di back-to-top accessibile anche in presenza dell'elemento `it-bottom-navscroll`. 

Secondo voi potrebbe essere interessante introdurre una classe per mostrare un bordo superiore, solo in modalità a schermo sotto `lg`, che separi in modo più deciso l'elemento `it-bottom-navscroll` dal contenuto della pagina o anche modificare l'attuale ombreggiatura accentuandola un pò di più?

## Comportamento attuale

![Screenshot 2022-11-02 170141](https://user-images.githubusercontent.com/2736009/199540507-d5306668-d97d-4519-8dc7-37ec53de342b.png)

**Comment by PiemP** [comment]
Grazie a voi per il lavoro svolto.

**Comment by Fupete** [comment]
Direi che è più un tema di Design needed @astagi, magari da risolvere prima nel kit UI. Cosa ne pensi @zetareticoli?

**Comment by gpeirolo** [comment]
@Fupete segnalo una possibile soluzione applicata in alcuni nostri progetti non AGID: shift verticale del back-to-top a seguito di rilevazione (via js) della presenza di un elemento ancorato al fondo.

**Comment by astagi** [comment]
@PiemP potremo risolvere inserendo nella doc la risoluzione via JS di questo caso particolare, @gpeirolo che ne dici?
