### ISSUE TITLE
Nella documentazione trovare un capitolo "Implementazione" per ogni componente

### ISSUE THREAD

**Issue by Fupete** [italia/bootstrap-italia#763]
## Versione di Bootstrap Italia

2.x

## Comportamento atteso

Nella documentazione, per ogni componente, avere un capitolo "Implementazione", che sia utile come guida per futuri sviluppi e/o sviluppi dedicati di altri _framework_ partendo da Bootstrap Italia. 

Utile sopratutto nel caso di componenti il cui comportamento è cambiato, rispetto alla base Bootstrap, eg. con JS custom per cambiare interazione da tastiera migliorandone l'accessibilità nel caso [esempio sul componente Accordion](https://italia.github.io/bootstrap-italia/docs/componenti/accordion/#implementazione)

## Comportamento attuale

È presente nel solo componente [Accordion](https://italia.github.io/bootstrap-italia/docs/componenti/accordion/#implementazione)

## Soluzione

Validate il formato impostato dal team di @gpeirolo per il componente Accordion, e poi replicarlo riempiendolo dei corretti contenuti per tutti gli altri componenti. Da capire se dividere questa issue in più issue e milestone per gruppi di componenti direi. 

cc @astagi

**Comment by DomeT99** [comment]
Ciao!
Ho ispezionato la documentazione per vedere dove aggiungere i componenti, ma mi sembra sia stato già fatto.
Magari è possibile chiudere questa issue?

**Comment by Fupete** [comment]
Ciao @DomeT99! 

Verifichiamo appena c'è un attimo con @astagi (e magari @gpeirolo ✌️), ma credo che la issue sia ancora valida, il capitolo Implementazione allo stato dell'arte dovrebbe essere presente solo in alcuni componenti, accordion in primis. Lo scopo del capitolo era, ed è tuttora, supportare specie per le soluzioni custom migliorative di js o markup rispetto a Bootstrap, l'uso dei componenti stessi o anche il porting in altri framework.

**Comment by DomeT99** [comment]
@Fupete ti ringrazio per la risposta, postate degli aggiornamenti sulla questione appena possibile.

Grazie ancora ✨

**Comment by astagi** [comment]
@DomeT99 dopo l'8 Gennaio al rientro di tutti vediamo come impostare questa parte nella documentazione! Grazie ancora e buon anno!

**Comment by DomeT99** [comment]
Buon anno a tutti voi! ✨

**Comment by astagi** [comment]
@DomeT99 cerco di impostare una struttura nei prossimi giorni riguardo a questa issue, poi ne possiamo parlare :) Grazie della disponibilità!

**Comment by DomeT99** [comment]
Figurati!

**Comment by Fupete** [comment]
@stale nope :-)
