### ISSUE TITLE
Elementi non funzionzanti VueJs 3

### ISSUE THREAD

**Issue by roskio** [italia/bootstrap-italia#766]
## Versione di Bootstrap Italia

^2.0.8

Import della libreria avviene nel main.js:
```
import 'bootstrap-italia/dist/css/bootstrap-italia.min.css'
import 'bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js'
```

Nel file index.html
```
<link rel="stylesheet" href="node_modules/bootstrap-italia/dist/css/bootstrap-italia.min.css">
<script src="node_modules/bootstrap-italia/dist/js/bootstrap-italia.bundle.min.js"></script>
```

## Comportamento atteso

Per alcuni elementi presi dalla documentazione non ho il comportamento atteso, per esempio:
I campi imput non hanno l'animazione "floating" al momento della scrittura.
Il transfer è visibile ma non funzionante in tutte le sue parti.

## Comportamento attuale
```
<div class="form-group">
    <label for="exampleInputText">Campo di tipo testuale</label>
    <input type="text" class="form-control" id="exampleInputText">
</div>
```
Non effettua nessuna animazione attesa

![Bootstrap italia vue](https://user-images.githubusercontent.com/59048932/200292647-2d886703-309b-4198-87f3-aa8a897863cb.png)

Unico alert in console:
![Immagine 2022-11-07 115330](https://user-images.githubusercontent.com/59048932/200293209-d99314d4-8e8e-4df4-9ec7-41f2b51eeede.png)

**Comment by astagi** [comment]
Buongiorno @roskio , è lo stesso problema relativo a questa issue https://github.com/italia/bootstrap-italia/issues/729

Anche per Vue succede la stessa cosa. Lo chiudo come duplicato.
