### ISSUE TITLE
Versione non bundle

### ISSUE THREAD

**Issue by geel97** [italia/bootstrap-italia#774]
## Versione di Bootstrap Italia
2.x

## Comportamento atteso
Ricevere il file bootstrap-italia.min.js

## Comportamento attuale
Viene fornito solamente il file bootstrap-italia.bundle.min.js

## Possibili soluzioni
Sarebbe possibile avere il file JS che non includa i componenti aggiuntivi? In modo tale da poterli includere separatamente come con le versioni 1.x

**Comment by astagi** [comment]
@geel97 grazie della segnalazione. Si potremmo aggiungerlo, vediamo come strutturarlo. Nel frattempo è possibile sfruttare gli import dei componenti singoli con tree shaking magari utilizzando Webpack o Rollup per poter ottimizzare la parte JavaScript.

**Comment by astagi** [comment]
@geel97 rettifico: vista la fretta e i cambiamenti per la versione 2.2.0 rilasceremo un minfix entro la metà di questo mese, dobbiamo semplificare la parte di moduli come su Bootstrap, includendo versione non-bundle. Per ora quello che posso suggerire è di utilizzare un bundler come Rollup o Webpack per ottimizzare le risorse (qui un esempio https://github.com/astagi/demo-bsitalia-2). Buon anno e a presto!
