### ISSUE TITLE
Icone per tipi di file

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#775]
## Versione di Bootstrap Italia

2.0.9

## Comportamento atteso

È molto pratico poter associare ai file scaricabili un'icona che identifica l’estensione del file stesso.
Da css è poi possibile anche colorarle per distinguerle più facilmente. 

es. 
![immagine](https://user-images.githubusercontent.com/20642463/202431720-0688e8c8-8916-47d6-b80b-00b1989defb8.png)

## Comportamento attuale

Al momento il framework non contiene icone di file specifici, c'è solo un generico it-file

## Possibili soluzioni

l'ideale sarebbe avere almeno le icone relative ai tipi di file più usati: pdf, word, excel, odt, ods, xml, csv, p7m, zip, immagini, audio e video
es. https://fontawesome.com/search?o=r&m=free&c=files4

**Comment by astagi** [comment]
Interessante @AlessandroVecchi abbiamo tra l'altro una PR con alcune nuove icone https://github.com/italia/bootstrap-italia/pull/740 ancora in corso di discussione. CC @albertopasqualetto

**Comment by astagi** [comment]
@AlessandroVecchi update: le icone sono in progress lato design, a breve apriremo una PR.

**Comment by astagi** [comment]
@AlessandroVecchi qua la preview https://bootstrap-italia-axunlk9at-dip-trasformazione-digitale.vercel.app/docs/utilities/icone/
