### ISSUE TITLE
Togliere il node_modules dagli @import scss

### ISSUE THREAD

**Issue by francescm** [italia/bootstrap-italia#781]
## Versione di Bootstrap Italia

non rilevante

## Comportamento atteso

Ruby On Rails può adottare bootstrap-italia ma adotta una convenzione differente sugli scss.

Rails si aspetta che i file scss si richiamino senza il prefisso ``node_modules``.

E' lo yarn build che si occupa di aggiungerlo:

```
{
  "scripts": {
    "vercel": "rm -rf ./bootstrap-italia && cp -r node_modules/bootstrap-italia/ ./bootstrap-italia",
    "build": "yarn vercel && sass --load-path=node_modules scss/bootstrap-italia-custom.scss:css/compiled/bootstrap-italia-custom.min.css --style=compressed",
    "start": "http-server ."
  }
} 
```
(frammento tratto da bootstrap-italia-playground e modificato nel load-path che prima era: --load-path=.)

Con questa convenzione gli @import in src/scss/bootstrap-italia.scss si abbreviano, così come
ad esempio lo @import nel file scss/bootstrap-italia-custom.scss di bootstrap-italia-playground.

Si potrebbe seguire questo schema?

**Comment by francescm** [comment]
Ho sottomesso PR #791 e PR gemella su bootstrap-italia-playground (#24).

**Comment by astagi** [comment]
@francescm grazie del contributo! Facciamo una verifica dopo l'8 Gennaio al rientro di tutti in modo da fixare questa parte e il playground!

**Comment by lscorcia** [comment]
Con l'occasione, per noi costretti ancora a usare bootstrap4, si potrebbe sistemare anche il path dell'import alla riga seguente sul branch 1.x?

https://github.com/italia/bootstrap-italia/blob/badc5e54a87f7c05666f7be34595aa2941a9cb8d/src/scss/bootstrap-italia.scss#L155

Quel `../..` iniziale impedisce di procedere con la nostra build webpack. Se serve posso inviare PR.
