### ISSUE TITLE
Font-display - swap

### ISSUE THREAD

**Issue by MassimoLuise** [italia/bootstrap-italia#786]
## Versione di Bootstrap Italia
Bootstrap Italia 2.0.9

## Comportamento atteso
Verificando con Lighthouse il risultato di una pagina creata utilizzando Bootstrap Italia, uno dei problemi rilevati è FOIT (Flash of invisible text) dovuto al caricamento dei Font (plugins/fonts-loader.js)
Penso potrebbe essere utile inserire nel plugin indicato sopra l'istruzione "font-display: swap".

## Comportamento attuale
Il comportamento attuale è FOIT (Flash of invisible text)

## Possibili soluzioni
Inserire "font-display: swap" in plugins/fonts-loader.js 

## Contesto
Caricamento dei fonts

**Comment by astagi** [comment]
Buongiorno @MassimoLuise abbiamo visto anche noi diversi problemi dati dal caricamento asincrono lato js, si ottiene proprio un flash. Abbiamo optato su un nuovo sito costruito a partire da bootstrap-italia per inserire la parte di font direttamente nel css e pensare in una breaking change di bootstrap-italia a rendere opzionale l'uso di fonts-loader.js. Non saprei davvero quanto cambia con l'utilizzo di `font-display: swap` in questo caso in cui viene caricato tutto in async.

**Comment by MassimoLuise** [comment]
> Buongiorno @MassimoLuise abbiamo visto anche noi diversi problemi dati dal caricamento asincrono lato js, si ottiene proprio un flash. Abbiamo optato su un nuovo sito costruito a partire da bootstrap-italia per inserire la parte di font direttamente nel css e pensare in una breaking change di bootstrap-italia a rendere opzionale l'uso di fonts-loader.js. Non saprei davvero quanto cambia con l'utilizzo di `font-display: swap` in questo caso in cui viene caricato tutto in async.

Modificando manualmente inserendo "font-display: swap" mi sembra funzionare...sia visivamente (non vedo flash) sia con lighthouse (e l'app di valutazione) non ho più segnalazioni relative a FOIT

**Comment by astagi** [comment]
grazie @MassimoLuise 💪
