### ISSUE TITLE
Componente TAB non rispetta il pattern wai-aria per l'interazione da tastiera

### ISSUE THREAD

**Issue by Fupete** [italia/bootstrap-italia#789]
## Versione di Bootstrap Italia

2

## Comportamento atteso

Componente tab rispetti il [pattern wai-aria per l'interazione da tastiera dei tabs](https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/).

TAB per entrare sul componente con focus sulla voce attiva, TAB per uscire dal componente. 
FRECCE per spostarsi da una voce all'altra. 
INVIO e SPAZIO per selezionare una voce. 
...

## Comportamento attuale

Ereditando il comportamento di Bootstrap, si entra sempre sulla prima voce con TAB e si naviga solo con il TAB tra tutte le diverse voci prima di poter uscire sempre col TAB. Si seleziona con l'INVIO. 

## Possibili soluzioni

Sviluppare un plugin JavaScript custom, sul modello di quanto fatto per il componente Accordion, per rispettare il pattern di interazione da tastiera corretto. Migliorando quindi l'accessibilità rispetto al framework di partenza Bootstrap. 

cc tx @cfabry per la review comune

**Comment by alenap93** [comment]
@Fupete come da changelog di bootstrap, la fix è stata rilasciata con la v5.2.0-beta1 (https://github.com/twbs/bootstrap/releases/tag/v5.2.0-beta1)

**Comment by Fupete** [comment]
Ottima notizia. @astagi direi che abbiamo da aggiornare la versione di Bootstrap quanto prima al rientro. Buon inizio anno a tutti.

**Comment by astagi** [comment]
Si @Fupete mettiamo l'attività in backlog

**Comment by AlessandroVecchi** [comment]
Ciao,
Segnalo che è uscita la v[5.3.0-alpha1](https://blog.getbootstrap.com/2022/12/24/bootstrap-5-3-0-alpha1/)
Non credo che manchi molto al rilascio della versione definitiva.

**Comment by astagi** [comment]
Sto provvedendo all'upgrade a Bootstrap 5.2.3, restano alcuni problemi di accessibilità riguardanti la tab e segnalati da pa11y.

**Comment by Fupete** [comment]
@astagi se questa è la preview che dici https://bootstrap-italia-8halgoi0z-dip-trasformazione-digitale.vercel.app/docs/componenti/tab/ non è proprio cambiata l'interazione da tastiera dei tab nella documentazione, è ancora quella sbagliata precedente.
 Così come è sbagliata quella sui tabs di B 5.3 ancora... https://getbootstrap.com/docs/5.3/components/navs-tabs/  🤔 
 anche se poi più sotto c'è questa parte Javascript che è corretto in tutti gli esempi invece https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior 👏

**Comment by alenap93** [comment]
@Fupete bisognerà armarsi di pazienza 😄 e modificare la doc rispettando i selettori scritti qui https://github.com/twbs/bootstrap/blob/main/js/src/tab.js 😄

**Comment by astagi** [comment]
Come non è cambiata @Fupete? adesso con tab usciamo e con le frecce invece ci muoviamo, prima potevamo muoverci solo con la tab. L'unica cosa che vorrei capire è perchè in automatico si aprono le tab spostandosi con le frecce.

**Comment by astagi** [comment]
Concordo @alenap93 stavo pensando anch'io di overridare qualche elemento, soprattutto per evitare che in automatico si aprano le tab. Sostanzialmente Bootstrap implementa [questo](https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-automatic.html).

**Comment by Fupete** [comment]
@astagi dici nella [ns](https://bootstrap-italia-8halgoi0z-dip-trasformazione-digitale.vercel.app/docs/componenti/tab/) preview? Io continuo a vedere solo tab... 🤔 
Negli [esempi](https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior) del loro plugin js ad hoc anche a me non torna che si aprano le tab con le FRECCE. Dovrebbero farlo solo con INVIO e SPAZIO.

**Comment by astagi** [comment]
Prova qua @Fupete :) https://bootstrap-italia-8halgoi0z-dip-trasformazione-digitale.vercel.app/docs/componenti/tab/#tab-con-testo-e-icona-2 ho paura che il tab sia dovuto al fatto che non è una tab completa di contenuto...

**Comment by Fupete** [comment]
Ok. Chiaro. Direi di rivedere proprio la documentazione sennò tutti i primi esempi solo "estetici" sono fuorvianti, ci vuole una bella nota accessibilità anche rivista. 

Rispetto all'attivazione automatica è un pattern previsto nelle WAI ARIA https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-automatic.html anche se con un warning a contenuti dei panel già presenti nel dom. Continuo a preferire l'attivazione manuale sinceramente https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-manual.html, o, almeno, andrebbe prevista anche quella come variante probabilmente. Coinvolgerei @cfabry su questo.

**Comment by cfabry** [comment]
Concordo con @Fupete che il comportamento con attivazione manuale rispetto a quella automatica mi sembra più corretto, l'utente è sicuramente consapevole di quale tab sia attivo. Se si pensa a tab informativi non è determinante, ma se si pensa a possibili tab che implicano scelte consapevoli (es: scelta tra prodotti, servizi, piani tariffari), è giusto avere l'attivazione manuale. Non a caso negli esempi del W3C sono stati pensati entrambi.

**Comment by cfabry** [comment]
Rispetto all'argomento dei primi esempi che ci sono, dove i tab non attivano la relativa scheda di contenuto: in teoria non sono tab, ma semplici elementi di lista e attualmente non hanno neanche la semantica di tab. Pertanto sarebbe giusta l'interazione con tasto tab e non con frecce. Tuttavia mi chiedo cosa ci facciano elementi Tab di questo tipo in questa sezione se non sono realmente dei tab, mi sembra un po' fuorviante.
