### ISSUE TITLE
Errore visualizzazione icona validazione su textarea

### ISSUE THREAD

**Issue by alfredotranchedone** [italia/bootstrap-italia#792]
## Versione di Bootstrap Italia

2.1.1 - 2.2.0

## Comportamento atteso

Alla validazione di una `textarea` tramite JustValidate, in caso di esito positivo, deve comparire l'icona verde analoga al campo `input`.

## Comportamento attuale

L'icona viene visualizzata in maniera errata.

## Possibili soluzioni

Il problema credo nasca dall'assenza della classe `.form-control` nel campo textarea all'interno di un form (come da documentazione).

Workaround temporaneo:
```
.form-group textarea {
  background-position: right 0.2rem !important;
  background-repeat: no-repeat !important;
  background-size: 28px 16px !important;
}
```
![Schermata 2022-12-26 alle 13 34 41](https://user-images.githubusercontent.com/8742666/209549662-b7da1345-210a-4a9e-bb20-7fc87ffb2d5a.png)
![Schermata 2022-12-26 alle 13 34 32](https://user-images.githubusercontent.com/8742666/209549677-a0bb263d-4f98-44ed-8e13-faee5285c768.png)

## Contesto

Codice della textarea:

```
<div class="form-row">
  <div class="form-group col-md-12">
    <label for="formIndirizzo">Indirizzo</label>
    <textarea id="formIndirizzo" rows="3" name="formIndirizzo"></textarea>
  </div>
</div>
```

**Comment by astagi** [comment]
@alfredotranchedone hai un esempio html dove poter riprodurre la tua issue?

**Comment by alfredotranchedone** [comment]
@astagi ho caricato qui: https://static.developy.it/form/

**Comment by astagi** [comment]
@alfredotranchedone ho aperto la PR che utilizza il tuo fix, dimmi se ti torna tutto :) Grazie ancora!

**Comment by alfredotranchedone** [comment]
sì, sì! Tutto a posto, grazie!
