### ISSUE TITLE
Liste di immagini e tag figure

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#793]
## Versione di Bootstrap Italia
2.1.x

## Comportamento atteso

Uso del tag figure per le immagini con didascalia al fine di migliorare la semantica.

## Comportamento attuale

Nella pagina https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/immagini/#figure viene descritto l'uso di figure ma poi nella pagina https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/liste-di-immagini/ non viene mai usato per le liste con didascalia.

## Possibili soluzioni

Il codice dell'esempio "Standard con didascalie" potrebbe diventare

```
<div class="it-grid-list-wrapper it-image-label-grid">
  <div class="grid-row">
    <div class="col-6 col-lg-4">
      <figure class="it-grid-item-wrapper">
        <a href="#">
          <div class="img-responsive-wrapper">
            <div class="img-responsive">
              <div class="img-wrapper"><img src="https://via.placeholder.com/660x300/ebebeb/808080/?text=Immagine" alt="descrizione immagine"></div>
            </div>
          </div>
          <figcaption class="it-griditem-text-wrapper">
            <span class="it-griditem-text">Didascalia</span>
            <svg class="icon">
              <use href="/bootstrap-italia/dist/svg/sprites.svg#it-code-circle"></use>
            </svg>
          </figcaption>
        </a>
      </figure>
    </div>
...
```

**Comment by astagi** [comment]
Molto interessante @AlessandroVecchi va bene! Se vuoi aprire una PR a riguardo ben venga!
