### ISSUE TITLE
Creare i types per la libreria Bootstrap Italia

### ISSUE THREAD

**Issue by astagi** [italia/bootstrap-italia#794]
## Versione di Bootstrap Italia

2.x

## Comportamento atteso

Ci si aspetta di avere i types per la libreria derivandoli da quelli di Bootstrap (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bootstrap)

**Comment by astagi** [comment]
CC @elgorditosalsero @antoninobonanno

**Comment by elgorditosalsero** [comment]
@astagi PR pronta 😄 

Come descritto in essa, molti tipi dovranno essere modificati per un miglior supporto 💯 

cc @AntoninoBonanno
