### ISSUE TITLE
Divisori in Toolbar non accessibili

### ISSUE THREAD

**Issue by alenap93** [italia/bootstrap-italia#796]
## Versione di Bootstrap Italia

2.2.0

## Comportamento attuale

All'interno della pagina [Toolbar](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/toolbar) nella sezione **Divisori** viene riportato:
`Per aggiungere degli elementi divisori fra gli elementi utilizzare dei tag <li> con classe .toolbar-divider, aggiungendo l’attributo aria-hidden="true" per nasconderli agli screen reader.`

Ciò implica che il separatore dato l'aria-hidden a true sarà invisibile per gli screen reader.

## Possibili soluzioni

Potrebbe essere riportato:
`Per aggiungere degli elementi divisori fra gli elementi utilizzare dei tag <li> con classe .toolbar-divider, aggiungendo l’attributo role="separator" per indicare la presenza di un elemento di separazione agli screen reader.`

**Comment by astagi** [comment]
@alenap93 aggiungerei nella documentazione di inserirlo sempre (anche nell'esempio). Puoi fare tu la PR per questo fix?

**Comment by alenap93** [comment]
@astagi ok, in questi giorni faccio la PR

**Comment by astagi** [comment]
Gentilissimo @alenap93 grazie ancora! E ottimi catch per l'accessibilità fanno solo bene al progetto!
