### ISSUE TITLE
Formattazione tag <Abbr>

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#799]
## Versione di Bootstrap Italia

2.2.x

## Comportamento atteso

Utilizzando (es.) `<abbr title="Posta Elettronica Certificata">PEC<abbr>` mi aspetto che il testo abbia una sottolineatura dotted (standard) e magari un cursore con il punto di domanda al passaggio del mouse, come da default di boostrap (https://getbootstrap.com/docs/5.1/content/typography/#abbreviations)

## Comportamento attuale

Il CSS bootstrap-italia-comuni.min.css contiene due definizioni contrastanti.
Prima c'è
```
abbr[title], abbr[data-bs-original-title] {
    text-decoration: underline dotted;
    cursor: help;
    text-decoration-skip-ink: none;
}
```
Ma più avanti c'è questa che sovrascrive la precedente
```
abbr[data-original-title], abbr[title] {
    text-decoration: none;
    cursor: default;
}
```

## Possibili soluzioni

Eliminare la seconda definizione e capire perché è stata messa.
Se uno vuole modificare la regola è giusto che lo faccia un un css separato.

**Comment by DomeT99** [comment]
Ciao, mi sono preso la libertà di dare un'occhiata al codice e ho notato che il primo snippet che hai indicato sopra non è presente nei file Scss, ma solo il secondo.

Nel frattempo, da quando è stato segnalato il problema, sono state prese delle decisioni diverse riguardo questa issue?

**Comment by AlessandroVecchi** [comment]
Ciao @DomeT99, 
Preciso che io mi riferivo al file .css generato, non al file .scss.

**Comment by astagi** [comment]
@AlessandroVecchi inseriamo il fix di @DomeT99 nella prossima release!
