### ISSUE TITLE
[1.x] Issue with jQuery override of the $ shorthand

### ISSUE THREAD

**Issue by lscorcia** [italia/bootstrap-italia#802]
## Versione di Bootstrap Italia

Versione 1.6.4 (Bootstrap 4).

## Comportamento atteso

Bootstrap Italia non dovrebbe interferire con il caricamento di jQuery e in particolare con lo shorthand `$` .

## Comportamento attuale

Attualmente, da quando è stata mergeata la pull request #545 , Bootstrap Italia sostituisce il valore di `$` nello scope globale con una chiamata a `jQuery.noConflict`. La PR citata non chiarisce per quale motivo ciò è stato fatto, citando generiche incompatibilità con Wordpress (e lì il problema è probabilmente di Wordpress) e asserendo che lo shorthand `$` sarebbe stato rimosso da jQuery (cosa che non trova riscontro nella documentazione di alcuna versione della libreria).

Il modo in cui viene eseguito l'override di tale operatore causa problemi quando si tenta di utilizzare Bootstrap Italia con Webpack. Normalmente sarebbe possibile eseguire l'esposizione di `$` e di `jQuery` all'esterno dei moduli utilizzando il plugin `expose-loader`, ma poiché Bootstrap Italia lo sostituisce con un suo export, questo viene a sparire nel momento in cui siamo fuori dallo scope del modulo di Bootstrap Italia, causando errori del tipo `ReferenceError: $ is not defined`.

## Possibili soluzioni

Soluzione 1) Revert integrale della PR #545 . Non riesco a interpretarne il senso e in ogni caso non c'è motivo per cui la libreria debba fare qualcosa di diverso rispetto alla bootstrap upstream;

Soluzione 2) Capire cosa si voleva effettivamente risolvere e individuare una fix più appropriata;

~~Soluzione 3) Aggiungere una guard intorno all'assegnazione e assegnare il valore di `$` solo se `$` non è già definito.~~

## Contesto

Se necessario posso caricare un semplice repro su github. Per le soluzioni 1 ~~e 3~~ posso fornire PR rapidamente.

**Comment by astagi** [comment]
Buongiorno @lscorcia la versione 1.x di Bootstrap Italia ha finito il suo supporto il 31 Dicembre 2022. Posso fare review della tua PR solo alla fine delle attività più urgenti e eventualmente rilasciare una versione, ma non garantisco, mi dispiace.

**Comment by lscorcia** [comment]
Il problema è proprio che chiama la noConflict senza motivo. noConflict rimuove dal contesto la variabile $, ma non solo ciò non dovrebbe mai essere necessario, è qualcosa che al massimo il singolo utente della libreria dovrebbe fare nel suo codice per gestire eventuali conflitti con altre librerie o versioni multiple di jQuery nella stessa pagina. Di sicuro non vedo il senso di richiamarlo all'interno della libreria bootstrap-italia, a maggior ragione perché bootstrap italia non usa mai lo shorthand ma solo il nome per esteso.

Comprendo comunque che non si può supportare all'infinito la versione 1.x. Stiamo valutando l'upgrade alla versione 2, abbiamo giusto qualche dubbio relativo al supporto di IE11. So che non dovremmo preoccuparcene ma... ci sono troppi utenti che usano IE ancora in giro :'-(

**Comment by astagi** [comment]
@lscorcia capisco ok, su quello devo indagare.. Ci sono ancora diversi utenti ma oramai anche per motivi di sicurezza bisogna che si aggiornino, abbiamo dato alla 1.x una estesa LTS. Io consiglio vivamente di fare l'upgrade, magari prima fate un giro utilizzando IE11 sulla documentazione, vedere se si rompe qualcosa e quanto grave sia questa rottura.

**Comment by astagi** [comment]
@lscorcia son costretto a chiudere questa issue. Grazie del supporto ma il termine di supporto per Bootstrap Italia 1.x è giunto al termine già da un mese. Se necessiti di fare upgrade alla 2.x scrivici su Slack o apri opportune issue.

Grazie lo stesso del contributo!
