### ISSUE TITLE
Card.title e h5

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#807]
## Versione di Bootstrap Italia

2.2.0

## Comportamento atteso

Non capisco come mai per display > 992px il font del titolo della card viene stampato più piccolo.

## Comportamento attuale

Nel file bootstrap-italia-comuni.min.css ci sono queste regole (le prendo dal browser per praticità).
```
@media (min-width: 992px)
.card .card-body h5.card-title, .card .card-body .card-title.h5 {
    font-size: 1rem;
}
.card .card-body h5.card-title, .card .card-body .card-title.h5 {
    font-size: 1.125rem;
    line-height: 1.4444444444rem;
    font-weight: 700;
    color: #17324d;
    margin-bottom: 16px;
    transition: all .3s;
}
```

## Possibili soluzioni

Eliminerei la regola @media lasciando che sia eventualmente lo sviluppatore a applicare eventuali correzioni su un css custom.

**Comment by DomeT99** [comment]
Ciao!
Potrebbe magari essere un'idea valida l'eliminazione solo del `font-size:1rem` in modo che durante il display > 992px il font venga stampato più grande, invece di eliminare completamente la regola?

**Comment by AlessandroVecchi** [comment]
> Ciao! Potrebbe magari essere un'idea valida l'eliminazione solo del `font-size:1rem` in modo che durante il display > 992px il font venga stampato più grande, invece di eliminare completamente la regola?

Ciao, sì scusa, non ho riportato bene le graffe, il codice corretto è 
```
@media (min-width: 992px) {
  .card .card-body h5.card-title, .card .card-body .card-title.h5 {
      font-size: 1rem;
  }
}
.card .card-body h5.card-title, .card .card-body .card-title.h5 {
    font-size: 1.125rem;
    line-height: 1.4444444444rem;
    font-weight: 700;
    color: #17324d;
    margin-bottom: 16px;
    transition: all .3s;
}
```
Quindi intendevo eliminare solo:
```
@media (min-width: 992px) {
  .card .card-body h5.card-title, .card .card-body .card-title.h5 {
      font-size: 1rem;
  }
}
```

**Comment by DomeT99** [comment]
Okay! Ora mi è più chiaro, ti ringrazio. Potrei aprire una PR nel pomeriggio o in tarda mattinata se posso procedere.

**Comment by astagi** [comment]
@DomeT99 giro la questione anche a @zetareticoli può aver senso se non c'è un motivo preciso per cui esiste quella regola..

**Comment by zetareticoli** [comment]
Ciao @AlessandroVecchi , grazie per la segnalazione.

Effettivamente quella _media query_ non sembra aver motivo di esistere, facciamo comunque un controllo degli stili utilizzati nel nuovo kit UI così da uniformare Bootstrap Italia.
