### ISSUE TITLE
package.json - entry main punta a file non esistente

### ISSUE THREAD

**Issue by lscorcia** [italia/bootstrap-italia#808]
## Versione di Bootstrap Italia

Bootstrap Italia v2.2.0.

## Comportamento atteso

Sto importando Bootstrap Italia v2.2.0 all'interno di una pipeline Webpack 5. Sto indicando al bundle di esportare l'oggetto `bootstrap` tramite il seguente snippet:

**webpack.config.js**
```
...
module.exports = {
    ...
    module: {
        ...
        rules: [
            ...
            {
                test: require.resolve("bootstrap-italia"),
                use: [{
                    loader: "expose-loader",
                    options: {
                        exposes: ["bootstrap"],
                    }
                }],
            }
        ]
    },
...
};
```
 
## Comportamento attuale

La build webpack fallisce alla riga `test: require.resolve("bootstrap-italia"),` riportando il seguente errore:

`EXEC : [webpack-cli] error : Cannot find module 'C:\myproject\Assets\node_modules\bootstrap-italia\dist\js\bootstrap-italia.min.js'. Please verify that the package.json has a valid "main" entry`

## Possibili soluzioni

In effetti il file menzionato nella entry main nel file package.json non esiste nel pacchetto:

https://github.com/italia/bootstrap-italia/blob/60792d17c53e1bc57a8bda87303e1c0e34d0c060/package.json#L24
![immagine](https://user-images.githubusercontent.com/16761934/211878156-6ab02120-080d-44a2-bd63-3c8a15c7131a.png)

La entry corretta sarebbe:

`"main": "dist/bootstrap-italia.esm.js",`

Attualmente il file contiene una entry chiamata `module` con il valore corretto, ma non mi risulta che sia standard ES (cfr. https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for). Veniva usata da Webpack 2, probabilmente Webpack 5 non la considera più.

Se serve posso fornire PR.

**Comment by astagi** [comment]
@lscorcia hai perfettamente ragione, apri pure la PR grazie infinite! 

Giusto per chiarezza dal link che mi hai mandato

```
The `main` field makes sure that Node users using require will be served the UMD version. 
The `module` field is not an official npm feature but a common convention among bundlers 
to designate how to import an ESM version of our library.
```

Quindi in `main` dovrebbe starci la versione UMD (appunto `dist/js/bootstrap-italia.bundle.min.js`) 
invece in `module` la versione ESM (in questo caso `dist/bootstrap-italia.esm.js`).

Ti torna?

**Comment by lscorcia** [comment]
Eh magari ci fossero due fonti di documentazione coerenti! 

Ho provato e purtroppo impostando `"main": "dist/js/bootstrap-italia.bundle.min.js"` la compilazione va a buon fine ma l'export di `bootstrap` non funziona (non ho ancora capito perché). Linkato in quello stesso post su StackOverflow si trova questo link: https://esbuild.github.io/api/#main-fields dove invece sembra che `main` debba contenere la versione CommonJS del modulo, di cui non mi sembra esista distribuzione nel package.

Impostando invece il valore al path del modulo ESM funziona regolarmente. Però potrebbe essere un problema di Webpack o della mia configurazione webpack...

**Comment by astagi** [comment]
@lscorcia ma nel file del tuo codice come lo importi? giusto per provare a replicare!

**Comment by astagi** [comment]
Si bootstrap fa così, esatto @lscorcia .. fammi sapere se risolvi, comunque se vuoi ben venga la PR quello del file main è un errore! Grazie 🙏

**Comment by lscorcia** [comment]
Inviata PR. Ho risolto anche il mio problema, stavo eseguendo l'export in maniera errata. Il modo corretto è il seguente:

```
import * as bootstrap from 'bootstrap-italia';
window.bootstrap = bootstrap;
```

Senza utilizzare `expose-loader` nel file `webpack.config.js`. In questo modo il metodo `loadFonts` è accessibile.
Grazie mille e a presto!

**Comment by astagi** [comment]
Ottimo @lscorcia ! Si, in effetti se utilizzi la sintassi

```js
import * as bootstrap from 'bootstrap-italia';
```

a tutti gli effetti WebPack utilizza il file UMD. 

Invece per utilizzare i moduli dovresti fare una cosa del tipo

```js
import { CarouselBI, Alert, Tooltip, Sticky, InputNumber, BackToTop } from 'bootstrap-italia'

```

Come nell'esempio [qua](https://github.com/astagi/demo-bsitalia-2/blob/develop/demo.entry.js)
