### ISSUE TITLE
Form - label sovrapposta a testo quando input ha già valore al load

### ISSUE THREAD

**Issue by lscorcia** [italia/bootstrap-italia#813]
## Versione di Bootstrap Italia

v2.2.0

## Comportamento atteso

I form field hanno label che si sposta dinamicamente, se valore vuoto è sovrapposta al form field, se valore presente si sposta più in alto. Al page load, se il campo ha già un valore (ad es. campi Nome/Cognome in una pagina Profilo utente), la label dovrebbe essere già in alto.

## Comportamento attuale

Al page load, se il form field ha già un valore, la label viene sovrapposta al testo. Dandogli il focus poi si sposta e resta in alto, ma il primo caricamento è errato.

![immagine](https://user-images.githubusercontent.com/16761934/212081648-cc4debe7-20d3-4afe-873e-1311f8aff167.png)

Per visionare il problema ho preparato un codepen: https://codepen.io/lscorcia/pen/QWBvYwz

**Comment by astagi** [comment]
Ciao @lscorcia si è una breaking change dell'attuale versione di Bootstrap Italia. Come specificato in documentazione se il campo è precompilato occorre aggiungere la classe `active` alle label

```html
<label class="active" for="formNome">Nome</label>
```

Codice completo:

```html
<html>
  <body>
<div class="mt-4">
  <div class="row">
    <div class="form-group col-md-6">
      <label class="active" for="formNome">Nome</label>
      <input type="text" class="form-control" id="formNome" value="Hello">
    </div>
    <div class="form-group col-md-6">
      <label class="active" for="formCognome">Cognome</label>
      <input type="text" class="form-control" id="formCognome" value="World">
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <label for="Comune">Comune</label>
      <input type="text" class="form-control" id="Comune">
    </div>
    <div class="form-group col-md">
      <label for="Provincia">Provincia</label>
      <input type="text" class="form-control" id="Provincia">
    </div>
    <div class="form-group col-md">
      <label for="CAP">CAP</label>
      <input type="text" class="form-control" id="CAP">
    </div>
  </div>
</div>
    </html>
  </body>
```

**Comment by lscorcia** [comment]
Ciao, ok provo a vedere se risolve.

Ho trovato la nota a cui fai riferimento qui: https://italia.github.io/bootstrap-italia/docs/form/input/ , forse è il caso di aggiungerla anche qui https://italia.github.io/bootstrap-italia/docs/come-iniziare/migrazione-dalla-versione-1/#form . Grazie!

**Comment by astagi** [comment]
Si hai ragione provvedo subito! Grazie @lscorcia

**Comment by astagi** [comment]
Fatto, grazie @lscorcia

**Comment by lscorcia** [comment]
Ho notato però che se l'utente svuota il campo, l'attributo active non viene rimosso dalla label (es. https://italia.github.io/bootstrap-italia/docs/form/introduzione/#stili-personalizzati prova a cancellare la parola 'Rossi' dal cognome). Applicando l'attributo la label è praticamente sempre fissa in alto. E' normale?

**Comment by astagi** [comment]
Ciao @lscorcia si hai perfettamente ragione, è come se gli script venissero proprio disabilitati! guardo un attimo e cerco di capire perchè ciò avviene, grazie della segnalazione intanto!

**Comment by astagi** [comment]
Soluzione trovata al volo @lscorcia questa dovrebbe funzionare https://github.com/italia/bootstrap-italia/pull/818

**Comment by AlessandroVecchi** [comment]
Ciao,

**Comment by AlessandroVecchi** [comment]
Ciao,

**Comment by AlessandroVecchi** [comment]
Ciao

**Comment by AlessandroVecchi** [comment]
Ciao, era stata verificata l'opzione con fieldset?
A me non sembra il massimo...
