### ISSUE TITLE
Impossibile utilizzare le dichiarazioni dei tipi con TypeScript e Angular

### ISSUE THREAD

**Issue by icolumbro-asf** [italia/bootstrap-italia#820]
## Versione di Bootstrap Italia

2.2.0

## Comportamento atteso

Alla dichiarazione di una variabile si dovrebbe poter specificare un tipo tra quelli disponibili per la libreria.

## Comportamento attuale

La libreria non mette a disposizione alcun tipo.

## Contesto

Integrando Bootstrap Italia in un progetto Angular 15 (con TypeScript) tramite npm, ci si aspetterebbe di aver a disposizione dei tipi relativi ai vari componenti messi a disposizione dalla libreria, es.:
import { Modal, Notification } from 'bootstrap-italia';

@Component({
  selector: 'my-component',
  templateUrl: './my-component.component.html',
})
export class MyComponent implements AfterViewInit {
  bsModal: Modal = null;
  bsNotification: Notification;

  ngAfterViewInit(): void {
    this.bsNotification = new Notification(document.getElementById('myNotification'), { timeout: 2000, });
  }
}

**Comment by DomeT99** [comment]
Ciao, la PR #804 ha aggiunto il supporto base a TS, ma non ci sono ancora dei tipi specifici mi sembra di aver capito.

**Comment by astagi** [comment]
@icolumbro-asf @DomeT99 chiudo come duplicato. 

In che senso non ci sono tipi specifici @DomeT99 ?

**Comment by icolumbro-asf** [comment]
Almeno per adesso mi andrebbero bene anche tutti gli argomenti dichiarati come any ma non riesco proprio ad importare i tipi dei componenti. Controllando i sorgenti in effetti io trovo il solo file decs.d.ts ma nulla più...

**Comment by astagi** [comment]
Chiarissimo @DomeT99 grazie, si @elgorditosalsero aveva già sottolineato questa cosa, prima di mergiarla @icolumbro-asf volevo fare i tipi delle varie configurazioni dei componenti, poi dalla release 2.3.0 di Bootstrap Italia sarà tutto pronto

**Comment by astagi** [comment]
Fantastico @icolumbro-asf grazie! Si mi sembra un'ottima struttura dalla quale ripartire, proprio con le option come stavamo pensando!! Poi se vuoi contribuire anche sul branch specifico ben venga, ci farebbe molto piacere!

**Comment by astagi** [comment]
Figurati non preoccuparti @icolumbro-asf mi sembra un ottimo punto di partenza!

**Comment by elgorditosalsero** [comment]
Haloa 😄 

Ho messo tutto ad any come base di partenza perché non ho avuto moltissimo tempo per studiarmi le customizzazioni dei vari componenti rispetto al base component di Bootstrap 😄 

Come detto ad @astagi, posso aggiornare tutto io, ma, ovviamente, ho bisogno di una mano per capire bene come tipizzare

**Comment by astagi** [comment]
Tranquillo @elgorditosalsero è un ottimo lavoro e un ottima base di partenza, seguo l'implementazione suggerita da @icolumbro-asf per la parte di configurazione in modo da sistemare le opzioni dei vari componenti poi direi che come iterazione iniziale sui tipi dovremmo esserci ampiamente.

**Comment by astagi** [comment]
@icolumbro-asf @DomeT99 @elgorditosalsero nell'ultimo rilascio (2.3.2) sono stati aggiornati diversi tipi. Se potete fare un giro e dare feedback ve ne sarei molto grato 🙏

**Comment by DomeT99** [comment]
@astagi appena ho un po' di tempo do un'occhiata e ti lascio un feedback :)

**Comment by icolumbro-asf** [comment]
@astagi è un buon inizio ma i tipi dovrebbero essere più restrittivi (usare `any` il meno possibile). Ho notato che c'è un problema col tipo `InputSearch` che, se utilizzato, il compilatore dà errore dicendo che non viene esportato alcun tipo con quel nome però, tra quelli che vengono suggeriti, compare `InputSearchAutocomplete`...
