### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'scrollTop')

### ISSUE THREAD

**Issue by claudiobat** [italia/bootstrap-italia#829]
Salve,
ho scaricato Bootstrap Italia 2.3.2 e Node.js 18.12.1.

Ho eseguito i comandi:
`npm install`
`npm run build`

Ho creato una pagina html importando i file:

- bootstrap-italia.min.css
- bootstrap-italia.bundle.min.js

e inserendo un semplice pulsante.

Il pulsante si vede, ma in console compare il seguente errore:
`
Destinazione navigazione: http://localhost/esempio-bootstrap/
bootstrap-italia.bundle.min.js:72 Uncaught TypeError: Cannot read properties of null (reading 'scrollTop')
    at bootstrap-italia.bundle.min.js:72:121
    at bootstrap-italia.bundle.min.js:4:99
    at bootstrap-italia.bundle.min.js:5:3
(anonimo) @ bootstrap-italia.bundle.min.js:72
(anonimo) @ bootstrap-italia.bundle.min.js:4
(anonimo) @ bootstrap-italia.bundle.min.js:5
`

Mi aspettavo che non ci fosse alcun errore.
Cosa sto sbagliando?

**Comment by claudiobat** [comment]
Chiedo scusa, ho risolto importando il file javascript nel body dell'html e non nello head.

**Comment by astagi** [comment]
Nessun problema @claudiobat grazie!
