### ISSUE TITLE
Esplicitare nella doc la breaking change select custom multipla

### ISSUE THREAD

**Issue by archetipo** [italia/bootstrap-italia#830]
## Versione di Bootstrap Italia

2.x.x

## Comportamento atteso

presenza della multi selezione con ricerca come nella versione >=1.6.4  [Select custom Multipla](https://italia.github.io/bootstrap-italia/1.x/docs/form/select/#select-custom-multipla)

## Comportamento attuale

Non presente nella versione attuale, direi che si tratta di un breaking change ma qui [Migrazione dalla versione 1](https://italia.github.io/bootstrap-italia/docs/come-iniziare/migrazione-dalla-versione-1/) non e' menzionato.

Forse andrebbe documentato.

## Possibili soluzioni

dipende dal piano di attività

## Contesto

E' previsto che questa funzionalità venga portata dalla >=1.6.4 alla 2.x.x?

**Comment by Fupete** [comment]
A breve non è prevista la creazione o l'integrazione di nuovi campi _custom_. 

Precedenti "select _custom_", come anche campi data e orario _custom_, sono stati rimossi nell'evoluzione alla versione 2, ma già deprecati nella documentazione da qualche versione 1 precedente, perché complicati, o impossibili, da rendere accessibili, a favore di standard di dispositivi e browser. Nel percorso è stato integrato il componente _autocomplete_, per fornire un campo input con possibilità di selezione e ricerca, validato per l'accessibilità e testato.

**Comment by Fupete** [comment]
Rispetto a documentarlo nella scheda di migrazione dalla 1 è una considerazione interessante. 
Essendo deprecati nella documentazione già della 1 fu valutato di non farlo. @astagi che ne pensi?

**Comment by archetipo** [comment]
Grazie, 
 
 ah  nella versione attuale su Github della [documentazione  ](https://github.com/italia/bootstrap-italia/blob/1.x/docs/form/select.md#select-custom-multipla) non era specificato,  ma forse era da intuire che qualsiasi select custom fosse deprecata, ad esempio ho visto che ora  e' specificato nel dettaglio nella [versione pubblica ](https://italia.github.io/bootstrap-italia/1.x/docs/form/select/#select-custom)

Grazie

**Comment by astagi** [comment]
Grazie @archetipo , si direi di specificarlo cc @Fupete . @archetipo se vuoi già buttare giù tu una bozza con una PR ben venga :)

**Comment by archetipo** [comment]
Ciao @astagi  ho fatto 2 PR una sulla versione 1.x che esplicita su ogni componente che sara' deprecato
e una sulla versione 2.x che riporta chiaro il braking.

Mi rimane solo piu' un dubbio a questo punto, come poter implementare una selezione multipla ad esempio un campo *tags*
in modo che sia considerato **accessibile** ?

Ho fatto e messo al riuso [questo](https://github.com/INRIM/service-app) che al nostro interno usiamo e i componente 
select multipla e' molto utilizzato soprattuto per taggare e classificare le informazioni. 
Mi sarebbe piaciuto pianificare l'aggiornamento e il porting alla versione 2.x.x  di questo progetto 
o magari aggiornare ad angular ma ho visto che i vari ui Kit non prevedono per ora in nessun caso un componente simile.

Grazie.

**Comment by astagi** [comment]
Grazie @archetipo includiamo tutto nei prossimi rilasci per ora stiamo fixando alcune cose sui colori! 

Sul discorso tags e select multipla siamo ancora in fase di studio e consultazione, sicuramente ne riparleremo :)

**Comment by astagi** [comment]
Una domanda @archetipo come mai la specifica della platform in docker-compose.yml?

**Comment by archetipo** [comment]
Ciao @astagi ok grazie rimango in poi in attesa di sapere come gestire tags e select multiple
La motivazione del campo platform e' scritta nella seconda riga della PR #832

Te la riporto nel con il chip Silicon (M1) che e' Arm  quando eseguo la build tramite buildx di docker e' necessario definire 
l'architettura con cui venga generato il container nel caso linux/amd64. 

Se non si specifica l'architettura del container come linux/amd64 anche se[ l'immagine iniziale e' compilata per arm ](https://hub.docker.com/layers/timbru31/ruby-node/3.0-16/images/sha256-b888ce4270fb1329c408a0a592860b9df118a72d3e39477364dc1e95c9c1ff7c?context=explore) il container non si avvia e non e' testabile, probabilmente perche' alcune librerie o dipendenze scaricate a runtime non sono compatibili con arm..

**Comment by astagi** [comment]
Perfetto grazie mille della spiegazione @archetipo l'avevo persa.. Io sono ancora su chip Intel :)

**Comment by astagi** [comment]
Mergiato! Grazie ancora @archetipo
