### ISSUE TITLE
Spaziatura it-header-slim-right-zone

### ISSUE THREAD

**Issue by lscorcia** [italia/bootstrap-italia#831]
## Versione di Bootstrap Italia

Versione 2.3.2

## Comportamento atteso

Credo ci sia una piccola regressione nei margini tra gli elementi all'interno del container `it-header-slim-right-zone` (dropdown lingua, pulsante Accedi).

E' possibile vedere il comportamento precedente nell'immagine linkata nel readme di bootstrap-italia-playground:
![immagine](https://user-images.githubusercontent.com/16761934/215893677-10224f62-052e-4be7-a4aa-9af2f8acb96b.png)

Notare lo spazio tra "ITA v" e "Accedi".

## Comportamento attuale

Questo l'attuale rendering da http://bootstrap-italia-playground.vercel.app/ :

![immagine](https://user-images.githubusercontent.com/16761934/215893807-e509d2fa-c71e-42cf-b342-e1c2690e2fda.png)

I due contenuti di `it-header-slim-right-zone` sono adiacenti senza margini né padding.

## Contesto

Credo che la regressione sia arrivata tra la release 2.2.0 e la 2.3.2 perché me ne sono appena accorto...

**Comment by DomeT99** [comment]
Ciao!
Credo sia sufficiente aggiungere all'elemento dropdown della lingua un `padding` (right e left) di circa `20px`. 
Che ne pensate?

**Comment by astagi** [comment]
Ciao @DomeT99 indago, potrebbe mancare proprio un padding o un margine, ma forse è semplicemente saltato durante la ristrutturazione delle variabili, indaghiamo

**Comment by astagi** [comment]
Fixato in https://github.com/italia/bootstrap-italia/commit/457148a38d71512b96203b4c5dc9118a10c89bc8 @DomeT99 @lscorcia
