### ISSUE TITLE
Aggiornamento Splide.js

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#836]
## Versione di Bootstrap Italia

2.3.4

## Comportamento atteso

Plugin Splide non aggiornato e risulta difficile consultare la documentazione ufficiale

## Comportamento attuale

Splide.js usato per il componente carousel risulta aggiornato alla v3.6.12, attualmente è disponibile la v4.1.3

## Possibili soluzioni

Aggiornamento alla versione 4.x
https://splidejs.com/guides/version4#migrating-from-v3-to-v4

**Comment by Fupete** [comment]
👍 

Nel frattempo la documentazione della v3 è qui https://splidejs.com/v3/archives/ 🔖

**Comment by AlessandroVecchi** [comment]
Ok, purché non ci siano troppe breaking nella stessa release 😅
