### ISSUE TITLE
Bootstrap Italia Bundle Min JS 2.3.4 + Angular 13 | DOMException #1360

### ISSUE THREAD

**Issue by alessiobilleci** [italia/bootstrap-italia#837]
Avendo gruppi di due radio button costruiti dinamicamente (hanno lo stesso name e id univoco) al click dei uno dei due viene mostrato il segunte errore in console:
Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '#id' is not a valid selector.
con riferimento a node_modules\bootstrap-italia\dist\js\bootstrap-italia.bundle.min.js

**Comment by astagi** [comment]
Buongiorno @alessiobilleci , puoi darci un po' di contesto?

**Comment by alessiobilleci** [comment]
> Buongiorno @alessiobilleci , puoi darci un po' di contesto?
Certamente 👍 
Nell'html ho una cosa del genere 

```
 <div class="form-check form-check-inline">
                            <input name="gruppo-{{type.id}}" type="radio" id="automatic-{{type.id}}" [value]="1"
                                [(ngModel)]="type.someBoolean" (change)="changeInput(type)">
                            <label
                                for="automatic-{{type.id}}">Opzione 1</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input name="gruppo-{{type.id}}" type="radio" id="manual-{{type.id}}" [value]="2"
                                [(ngModel)]="type.someBoolean" (change)="changeInput(type)">
                            <label
                                for="manual-{{type.id}}">Opzione 2</label>
                        </div>
```
Si tratta di due radio button che gestiscono la visualizzazione di un contenuto sottostante a seconda del radio button cliccato.
Mi aspetto che cambiando il radio button cambi la vista sotto (gestita con un If in base al value che come puoi vedere è collegato ad un ngModel.
A livello grafico funziona ma genera un errore in console per ogni elemento ciclato.

Se posso aggiungere altro sono a disposizione

**Comment by astagi** [comment]
@alessiobilleci stai utilizzando Angular mi sembra giusto? Hai provato il kit Angular attualmente in costruzione? forse l'implementazione dei radio button può darti qualche dritta https://github.com/italia/design-angular-kit

**Comment by astagi** [comment]
@alessiobilleci ti lascio anche questa discussione dove abbiamo già affrontato il tema Angular, per ora chiudo la issue: https://github.com/italia/bootstrap-italia/issues/729#issuecomment-1268251954
