### ISSUE TITLE
Scrollbar in NAV TABS orizzontali

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#851]
## Versione di Bootstrap Italia

2.3.4

## Comportamento atteso

Nella navigazione a TAB non dovrebbe comparire la scroll bar orizzontale se non quando il testo è più largo della dimensione del viewport

## Comportamento attuale

Nel componente TAB con risoluzioni inferiori a 1200px compare la scroll bar orizzontale
https://italia.github.io/bootstrap-italia/docs/componenti/tab/#tab-orizzontali

![immagine](https://user-images.githubusercontent.com/20642463/225928520-355edaa4-a3ce-4fcd-aba8-a3bc3cdaa988.png)

## Possibili soluzioni

```
.nav-tabs {
  position: relative;
  background-color: #fff;
  border-bottom-color: #c5c7c9;
  display: flex;
  overflow-x: scroll;
  overflow-y: hidden;
  -webkit-overflow-scrolling: touch;
  flex-wrap: nowrap;
}
```
sostituire **overflow-x: scroll;** con  **overflow-x: auto;**

**Comment by DomeT99** [comment]
@astagi quando posso, aiuto volentieri!

**Comment by AlessandroVecchi** [comment]
Grazie @astagi e @DomeT99 
Sono sempre timoroso nel toccare un codice creato da altri perché la modifica in un punto potrebbe rompere il layout in un altro e su un framework condiviso questo sarebbe un grosso problema. Quindi do dei suggerimenti che però devono essere super testati per essere sicuri che sia la soluzione migliore.

**Comment by DomeT99** [comment]
@AlessandroVecchi ci mancherebbe, sono timori più che leciti.
