### ISSUE TITLE
Modo correto per l'inclusione delle icone svg e loro denominazione

### ISSUE THREAD

**Issue by gorobey** [italia/bootstrap-italia#858]
## Versione di Bootstrap Italia

2.3.6

## Comportamento atteso

l'uso di un'icona rispetto ad un'altra potrebbe derivare da un campo dinamico (faccio riferimento al tema drupal per i comuni nel mio caso), dove ad esempio potrebbe essere richiamata l'icona del telefono oppure quella della posta elettronica proprio a seconda del campo che si intende visualizzare ad esempio:

```
<svg class="icon" viewBox="0 0 24 24" id="it-{{ tipo_punto|lower }}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <use href="/web/modules/custom/design-comuni-drupal-theme/comuni_theme/node_modules/bootstrap-italia/dist/svg/sprites.svg#it-{{ tipo_punto|lower }}"></use>
</svg>
```

## Comportamento attuale

Facendo riferimento a questa pagina:
https://italia.github.io/bootstrap-italia/docs/utilities/icone/
l'utilizzo sopra descritto non risulta possibile poiché la maggior parte delle icone nella sprites sono nomitate in inglese, ma visto che i siti in cui viene utilizzato bootstrap-italia sono principalmente in italiano e così presumibilmente anche il logo beckend... ma attualmente le icone vengono principalmente richiamate così:

```
<svg class="icon" viewBox="0 0 24 24" id="it-telephone" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path ... />
</svg>
```
dove non viene utilizzato lo sprites, ma viene incluso il codice dell'icona.

## Possibili soluzioni

Mi rendo conto che questo problema non è direttamente legato a bootstrap-italia, ma al modo in cui questo viene utilizzato, ma credo altresì sia questo il posto giusto dove proporre e concordare uno standard di utilizzo, ad esempio:

1. Definendo quale sia la via "corretta" per l'inclusione delle icone (richiamando le singole icone o utilizzando lo sprites? via HTML o CSS? è corretto seguire https://italia.github.io/bootstrap-italia/docs/utilities/icone/ ?)
2. Adottando un approccio differente nella denominazione:
- favorendo l'uso della parola italiana a quella inglese (es: telefono invece di telephone)
- utilizzando vocaboli inglesi solo se ormai entrati a far parte della della lingua corrente (es: mail o email)

**Comment by astagi** [comment]
Ciao @gorobey Bootstrap Italia sulla denominazione delle icone ha sempre seguito la lingua inglese, nel tuo caso potresti fare una mappatura, ad esempio

```
{
  "telefono" : "it-telephone",
  "nome" : "it-user"
}
```

spero di aver compreso bene la problematica

**Comment by gorobey** [comment]
Grazie @astagi , quindi mi confermi che comunque l'intenzione è quella di utilizzare unicamente lo sprite di Boostrap Italia e di conseguenza l'abbandono di font awesome?
Al momento avevo pensato di aggiungere il campo "icona" fornita dal modulo fontawesome, perché utilizzato in altre aree del sito (link assistenza), ma non è la solizione che preferirei:
Mi piacerebbe che le icone siano richiamate sempre allo stesso modo e da un unico set.

**Comment by arturu** [comment]
L'uso dei componenti (mi riferisco al concetto dei componenti che si fa in drupal, che da drupal 10.1 sarà ancora di più centrale per i frontend) potrebbe semplificare molto il codice, facilitare l'uso e la manutenzione. Se usi i componenti ti ritroverai a scrivere una cosa del genere per includere le icone
```{% include '@components/icona/icona.html.twig' with {
  name: mail,
  size: xs,
  color: primary
}%}```
Ci penserà il componente a scrivere i html codice corretto in qualsiasi punto lo richiami e poi aggiornando il componente aggiorni in tutte le parti in cui è richiamato. Un esempio
 https://git.drupalcode.org/project/bootstrap_italia/-/blob/2.x/components/components-2/icon/icon.html.twig

Il bello dei componenti è che si possono estendere a piacimento e si possono mappare nella ui di backend di drupal per costruire temi low-code, volendo puoi anche mappare i nomi in italiano, ma questo lo vedo uno spreco di tempo.

**Comment by gorobey** [comment]
Grazie @arturu per la tua risposta,
trovo la tua soluzione più interessante della mia ma non risolve il problema:
che si utilizzi la sprites di bootstrap-italia o il set di font awesome non c'è un modo "permanete" per richiamare un'icona, che sia questa utilizzata nel backend o nelle pagine, che si parli di drupal o wordpress i campi sono etichettati in lingua italiana, l'unico modo per richiamare in "automatico" un'icona è la trasposizione del nome, cosa possibile solo nel caso ci sia la ragionevole sicurezza che la label del campo e il nome dell'icona non cambino nel tempo.

Infine il modulo font-awesome porta con se anche un campo "icona" perché viene utilizzato se la sprites di bootstrap-italia contiene tutte le icone necessarie? sarebbe un metodo da abbandonare o si è deciso di mantenerlo "per pigrizia" (=leggi: in assenza della stessa funzionalità del campo con cui scegliere l'icona del modulo font-awesome)?

**Comment by arturu** [comment]
> Grazie @arturu per la tua risposta, trovo la tua soluzione più interessante della mia ma non risolve il problema: che si utilizzi la sprites di bootstrap-italia o il set di font awesome non c'è un modo "permanete" per richiamare un'icona, che sia questa utilizzata nel backend o nelle pagine, che si parli di drupal o wordpress i campi sono etichettati in lingua italiana, l'unico modo per richiamare in "automatico" un'icona è la trasposizione del nome, cosa possibile solo nel caso ci sia la ragionevole sicurezza che la label del campo e il nome dell'icona non cambino nel tempo.
> 

Un consiglio filosofico. Ti propongo un altro approccio, al posto di pensare che non cambi nulla prova a pensare nei termini i cui tutto cambi in continuazione e in maniera frequente, con questo approccio diventa naturale sviluppare software resiliente ai cambiamenti.

Per quanto riguarda il caso specifico. Con Drupal ci sono 1000 modi per sviluppare la stessa cosa, ho capito che hai l'esigenza di temizzare un campo a cui associare un'icona. Penso che la migliore strada sia quella di usare le `suggestions` associate ai template dei campi. Ad esempio, per il campo `field_telefono` potresti costruire un pezzo di template `field--name-field-telefono.html.twig` (in cui inserisci il codice per produrre l'output dell'icona) e drupal te lo renderizza ovunque viene utilizzato il campo telefono, così scrivi il codice una volta. In futuro, quando il nome dell'icona cambia, ad esempio da `it-telephone` a `it-telephone-2`, aggiorni il codice in un solo punto. In questa maniera non hai bisogno di sviluppare un algoritmo che associ in automatico il campo all'icona, che sarebbe un algoritmo molto sensibile ai cambiamenti e in cui sei costretto a mettere un mare di condizioni per soddisfare le esigenze dei diversi campi, eccezioni e artifici vari.

Per quanto riguarda wordpress non saprei, non lo conosco.

> Infine il modulo font-awesome porta con se anche un campo "icona" perché viene utilizzato se la sprites di bootstrap-italia contiene tutte le icone necessarie? sarebbe un metodo da abbandonare o si è deciso di mantenerlo "per pigrizia" (=leggi: in assenza della stessa funzionalità del campo con cui scegliere l'icona del modulo font-awesome)?

Penso che questo argomento dovrebbe rientrare in un'altra discussione.

**Comment by astagi** [comment]
Il discorso dei componenti sarà anche oggetto delle prossime lavorazioni di Bootstrap Italia che verrà completamente riscritto attraverso l'uso dei web component. Grazie @arturu e @gorobey per aver mantenuto la discussione, se tutto è chiaro chiuderei questa issue ,che ne dite?

**Comment by gorobey** [comment]
grazie a voi @arturu e @astagi per avermi dato delucidazioni sull'argomento, chiedo solo un'ultima cosa anche se OT a @astagi per quando è prevista la nuova release?

**Comment by astagi** [comment]
Figurati è un piacere @gorobey ! La nuova release con i fix è prevista per domani, entro fine mese rilasceremo anche il componente Video :)

**Comment by astagi** [comment]
@gorobey nuova versione rilasciata! Buon lavoro!
