### ISSUE TITLE
burger menu su versione desktop

### ISSUE THREAD

**Issue by davideginna** [italia/bootstrap-italia#859]
## Comportamento atteso
Avere la possibilitá del burger menu che si crea nel header per risoluzioni piccole dello schermo anche su desktop

## Comportamento attuale
Attualmente devo restringere la pagina per avere il burger menu nel header

## Possibili soluzioni
aggiunta di una classe o un parametro che attiva o disattiva il burge menu con annessa sidebar

**Comment by AlessandroVecchi** [comment]
Ciao, il burger menu si attiva automaticamente per risoluzioni orizzontali sotto il 992px (quindi fondamentalmente per tablet con orientamento verticale)

**Comment by astagi** [comment]
Si esatto, come specificato da @AlessandroVecchi il comportamento di base è quello. Nel tuo caso @davideginna vorresti forzare questo comportamento anche su desktop? Tecnicamente penso tu possa farlo già sovrascrivendo l'attuale comportamento di Bootstrap su una data risoluzione, ma questo significherebbe uscire dalle regole del design system. Per ora chiudo la issue.

**Comment by groundrace** [comment]
nel design system quindi è obbligatorio avere il menu visibile per width > 992px ?
Non è una regola un po' troppo limitante?
il modo in cui è implementato sulla `_navigation.scss`

```
...
//Tablet horizontal / small desktop
@media (min-width: #{map-get($grid-breakpoints, lg)}) {
  .row.row-column-border > [class^='col-'] .navbar {
    padding: 0;
  }

  .navbar {
    background: $navigation-bg-color-desktop;
    padding: 0;

    // navbar mobile
    .navbar-collapsable {
      position: relative;
      top: auto;
      right: auto;
      left: auto;
      bottom: auto;
      z-index: auto;
      background: none;
      display: block !important; //-sovrascrive l'inline style di jquery
      transition: none;
...
``` 
l'implementazione attuale che prevede una `[!important](display: block !important;)` ci pare troppo bloccante per un potenziale riuso che intenda non visualizzare il menu. Quello di rendere obbligatorio il menù aperto su dektio dovrebbe essere un suggerimento più che un obbligo
