### ISSUE TITLE
loadFonts non può essere importata in Typescript

### ISSUE THREAD

**Issue by mv-er** [italia/bootstrap-italia#870]
## Versione di Bootstrap Italia

2.3.7

## Comportamento atteso

`import { loadFonts } from 'bootstrap-italia'`
Importa correttamente la funzione `loadFonts` in ambiente Typescript, come suggerito nella [documentazione](https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/#via-javascript)

## Comportamento attuale

`import { loadFonts } from 'bootstrap-italia'`
Appare il seguente messaggio d'errore: Module '"bootstrap-italia"' has no exported member 'loadFonts'.

## Possibili soluzioni

Aggiungere l'export di `loadFonts` nella definizione dei tipi

## Contesto

Libreria installata tramite npm:
`npm install bootstrap-italia`

**Comment by astagi** [comment]
Grazie della segnalazione @mv-er ! se vuoi aprire una PR a riguardo sei il benvenuto!
