### ISSUE TITLE
Problema con l'introduzione dei tipi per loadFonts

### ISSUE THREAD

**Issue by StefanoMartella** [italia/bootstrap-italia#882]
## Versione di Bootstrap Italia
 
2.4.0
 
## Comportamento atteso
 
Nessun problema in fase di compilazione.
 
## Comportamento attuale
 
Durante la compilazione della mia applicazione Angular restituisce il seguente errore:
> A parameter initializer is only allowed in a function or constructor implementation

relativamente al file [fonts-loader.d.ts](https://github.com/italia/bootstrap-italia/blob/a9cd91fd6575414d9b6a59a2e2934ca9fc867657/types/plugins/fonts-loader.d.ts)
 
## Possibili soluzioni
 
Credo sia sufficiente rimuovere l'inizializzazione del parametro `path` all'interno di `loadFonts`, se ritenete che la soluzione sia valida procedo ad effettuare una pull request.

**Comment by astagi** [comment]
Chiarissimo! Grazie @StefanoMartella manda pure una PR!
