### ISSUE TITLE
Colori footer non correlati alla variabile $primary

### ISSUE THREAD

**Issue by abmcr** [italia/bootstrap-italia#893]
le linee 419 be 420 del file utilities/color_var.scss

$footer-top-background: hsl(210, 100%, 30%); // color-blue-30
$footer-bottom-background: hsl(210, 100%, 20%); // color-blue-20

non permettono di ereditare il $primary-h

**Comment by zetareticoli** [comment]
@astagi direi che è la soluzione più veloce. posso prenderla in gestione io

**Comment by astagi** [comment]
Grazie @zetareticoli
