### ISSUE TITLE
Errore di compilazione Typescript - error TS7010: 'loadFonts', which lacks return-type annotation, implicitly has an 'any' return type.

### ISSUE THREAD

**Issue by traycold** [italia/bootstrap-italia#897]
## Versione di Bootstrap Italia

2.4.2

## Comportamento atteso

L'applicazione che usa bootstrapItalia e in particolare la funzione loadFonts() compila correttamente con Typescript.

## Comportamento attuale

Errore di compilazione:
`Error: node_modules/bootstrap-italia/types/plugins/fonts-loader.d.ts:5:17 - error TS7010: 'loadFonts', which lacks return-type annotation, implicitly has an 'any' return type.`

## Possibili soluzioni

aggiungere il returnType in `types/plugins/fonts-loader.d.ts`:

`export function loadFonts(path: string):any`

## Contesto

n.a.

**Comment by astagi** [comment]
@traycold il fix dovrebbe risolvere il problema, confermi?
