### ISSUE TITLE
Buttons outlined success, warning, danger, info... non funzionano

### ISSUE THREAD

**Issue by s-castagnaro-abaco** [italia/bootstrap-italia#899]
## Versione di Bootstrap Italia

Versione 2.4.2

## Comportamento atteso

Mettendo la classe btn-outline-success mi aspettavo di vedere il bordo verde.
```html
<button class="btn btn-outline-success" />
```

## Comportamento attuale

Aggiungendo le classi btn-outline-* il bordo non si vede tranne per le classi primary e secondary. Es.:
```html
<button class="btn btn-outline-success">No</button> <!-- ❌ -->
<button class="btn btn-outline-primary">Ok</button> <!-- ✅ -->
```

**Comment by zetareticoli** [comment]
@s-castagnaro-abaco @astagi le classi di tipo `btn-outline-` dedicate ai messaggi di status (info, warning, success ed error)  non sono presenti nella libreria. 

@astagi @Fupete possiamo prevedere di aggiungerle utilizzando direttamente i design tokens?
