### ISSUE TITLE
Errore di rendering negli steppers

### ISSUE THREAD

**Issue by adilorenzodema** [italia/bootstrap-italia#907]
## Versione di Bootstrap Italia
Angular: "13.3.6"
bootstrap-italia": "2.4.2"

## Comportamento atteso

Voglio utilizzare gli stepper di boostrap italia come da documentazione:
![image](https://github.com/italia/bootstrap-italia/assets/77487424/1ecfa2bb-1eca-414b-95c7-33e69f97e121)

## Comportamento attuale

![image](https://github.com/italia/bootstrap-italia/assets/77487424/a00ac329-6e1a-4509-8aa2-cac18005228a)

ma nella mia app lo stepper viene renderizzato verticalmente
![image](https://github.com/italia/bootstrap-italia/assets/77487424/1b9b8fd0-ca49-4a0b-99be-0d047f2e311c)

Qui è come importo gli stili di Angular bootstrap Italia
![image](https://github.com/italia/bootstrap-italia/assets/77487424/536370f6-2fcc-4f80-ba6f-9f40fe2a38e6)

Potete aiutarmi a capire il problema?

**Comment by astagi** [comment]
Ciao @adilorenzodema ma questo problema lo riscontri anche nella doc di Bootstrap Italia o solo nella tua applicazione?

**Comment by adilorenzodema** [comment]
Io seguo questa doc:
https://italia.github.io/bootstrap-italia/docs/componenti/steppers/

e vedo che qui gli steppers sono disposti orizzontalmente

**Comment by astagi** [comment]
Forse c'è una regola css del container nella tua app che altera questo comportamento?
