### ISSUE TITLE
Problema nella compilazione con bootstrap 5.3

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia#910]
## Versione di Bootstrap Italia
Penso che si verifichi su tutte le versioni 2.x, io lo rilevo sulla 2.4.x

## Comportamento atteso
Mi aspetto di compilare senza errori

## Comportamento attuale

Compilando la libreria vengono restituiti diversi errori tutti simili, riporto solo uno per brevità

```bash
WARNING in ./node_modules/bootstrap-italia/dist/plugins/cookiebar.js 155:21-43
export 'getElementFromSelector' (imported as 'getElementFromSelector') was not found in 'bootstrap/js/src/util/index' (possible exports: defineJQueryPlugin, execute, executeAfterTransition, findShadowRoot, getElement, getNextActiveElement, getTransitionDurationFromElement, getUID, getjQuery, isDisabled, isElement, isRTL, isVisible, noop, onDOMContentLoaded, parseSelector, reflow, toType, triggerTransitionEnd)
 @ ./node_modules/bootstrap-italia/dist/bootstrap-italia.esm.js 5:0-62 5:0-62
 @ ./src/js/index.js 22:0-45 40:19-28
```
Non trova nell'export `getElementFromSelector`

## Possibili soluzioni
Nel mio progetto ho risolto con:

```bash
npm install bootstrap@5.2 --save-exact
```
in quanto essendoci in https://github.com/italia/bootstrap-italia/blob/12a2ccae87e751b4a318dee93376ab6908c092be/package.json#L100 un eventuale update o install farà installare la versione 5.3 di bootstrap (che è uscita ieri)

## Contesto
Il contesto è per chi compila versioni custom della libreria

**Comment by astagi** [comment]
L'ultimo commit https://github.com/italia/bootstrap-italia/commit/f828078e6d722a2c625d4eee4a7faa99f787a912 dovrebbe risolvere il problema.

**Comment by astagi** [comment]
Rilasciata nuova versione, grazie ancora della segnalazione e del suggerimento
