### ISSUE TITLE
escapeSelector

### ISSUE THREAD

**Issue by SimonePadovan** [italia/bootstrap-italia#913]
## Versione di Bootstrap Italia

2.5.0

## Comportamento atteso

gli id dei nostri tags html sono composti da nome form: nome componente. Ad esempio per il tag toggle il campo di input ha questo id: **formId:toggleEsempio1a**. Sembra che le istruzioni javascript gestire da bootstrap italia non tengano conto di questa possibilitá ed indirizzino gli elementi senza effettuare un escaping. 
Succede quindi che nel caso del toggle (ma anche con altri componenti) compaia i seguente errore: Uncaught DOMException: Document.querySelector: '#formId:toggleEsempio1a' is not a valid selector.

## Comportamento attuale
Viene sollevata una eccezione javascript dovuta al fatto che l'istruzione querySelector non tiene conto della possibilitá che l'id del tag referenziato contenga il carattere ":"

## Possibili soluzioni
richiamare jQuery.escapeSelector() per trattare l'id del tag da selezionare
https://api.jquery.com/jQuery.escapeSelector/

**Comment by SimonePadovan** [comment]
@astagi 
Ciao Andrea, grazie per la risposta. Cerco di spiegare meglio il problema:
Prendiamo ad esempio il componente toggle utilizzatro come segue:
`		<h:form id="form">
			<div>
			  <div class="row">
				<div class="form-check col-6">
				  <div class="toggles">
					<label for="**form:toggleEsempio1a**">
					  Label dell'interruttore 1
					  <input type="checkbox" id="**form:toggleEsempio1a**"/>
					  <span class="lever"></span>
					</label>
				  </div>
				</div>
			  </div>
			</div>
		</h:form>
`
L'id del campo di input e del tag for della label é composto da id della {form : id item} -> form:toggleEsempio1a. Questa é una impostazione del framework (JSF) che utilizziamo.
Se a runtime provi a selezionare o deselezionare il toggle riceverai per 4 volte il seguente errore nella console:

`Uncaught DOMException: Document.querySelector: '#form:toggleEsempio1a' is not a valid selector [bootstrap-italia.min.js.xhtml:78](http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT)
    getInputFromLabel http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:78
    <anonima> http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:80
    r http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:66`

Questo sembra dovuto al fatto che il relativo javascript di bootstrap-italia utilizzi l'id senza effettuarne prima un escaping per gestire eventuali caratteri riservati come i :.
La prima istruzione javascript che da l'errore infatti é questa:

`getInputFromLabel=e=>document.querySelector("#"+e.getAttribute("for"));_`

Non si tratta di istruzioni jquery, ma javascript. 
Occorrerebbe effettuare l'escaping degli attributi id prima di utilizzarli.

Spero di essermi spiegato e attendo feedback.

grazie mille
Simone

**Comment by SimonePadovan** [comment]
Buongiorno, non ho piú ricevuto feedback riguardo questo problema.
Per noi é fondamentale risolverlo il prinma possibile per riuscire a procedere con l'adozione degli stili previsti.

grazie

**Comment by astagi** [comment]
Buongiorno @SimonePadovan prendo in carico per un rilascio per la prossima settimana.

**Comment by SimonePadovan** [comment]
Grazie mille

**Comment by astagi** [comment]
@SimonePadovan questo codice dà l'errore? non riesco a riprodurlo

```html
        <label for="form:toggleEsempio1a">Campo testo</label>
          <input type="text" class="form-control" id="form:toggleEsempio1a" required />
        </div>
```

**Comment by SimonePadovan** [comment]
Esatto, se povi a cliccare sul toggle otterrai un errore nella console

**Comment by SimonePadovan** [comment]
il campo di input non é un text ma un checkbox (toggle)

`<h:form id="form"> <div> <div class="row"> <div class="form-check col-6"> <div class="toggles"> <label for="form:toggleEsempio1a"> Label dell'interruttore 1 <input type="checkbox" id="form:toggleEsempio1a"/> <span class="lever"></span> </label> </div> </div> </div> </div> </h:form> `

**Comment by astagi** [comment]
Capito, però dovrebbe verificarsi anche con label e testo no @SimonePadovan ? intanto provo con la checkbox

**Comment by astagi** [comment]
@SimonePadovan il fix è pronto ☝🏻 non so se avete modo di verificarlo altrimenti rilascio una nuova versione e vediamo. Sono riuscito a riprodurlo e sistemarlo comunque.

**Comment by SimonePadovan** [comment]
@astagi il problema non riguarda solo la label, ma anche gran parte degli altri componenti.
Come ad esempio:

-Sidebar (nella console ricevo questo errore: Uncaught DOMException: Document.querySelector: '#j_idt42:0_submenu' is not a valid selector)

-Accordion 
-Tabs
-Autocomplete
-Rating
-Checkbox
-Select radio

grazie

**Comment by astagi** [comment]
@SimonePadovan questo problema lo noti se usi la validazione? Senza dovrebbe andare tutto liscio.. mi confermi?

**Comment by SimonePadovan** [comment]
Non uso la validazione.

Per il campo radio e checkbox il problema penso sia sempre nella gestione della label (come per il toggle) gestita via javascript specifico.
Per accordion e gli altri entra in gioco anche l'attriuto data-bs-target che dovrebbe essere escapato.

grazie

**Comment by astagi** [comment]
@SimonePadovan purtroppo dopo un po' di controlli ho visto che l'escaping non viene fatto lato Bootstrap dal quale derivano molti componenti. Il consiglio che posso darvi è quello di escapare direttamente il `data-bs-target`, ad esempio (caso Accordion)

```html
    <div class="accordion-item">
      <h2 class="accordion-header " id="head:heading1c">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#coll\:collapse1c" aria-expanded="true" aria-controls="collapse1c">
          Elemento Richiudibile #1
        </button>
      </h2>
      <div id="coll:collapse1c" class="accordion-collapse collapse show" role="region" aria-labelledby="head:heading1c">
        <div class="accordion-body">
          Vestibulum hendrerit ultrices nibh, sed pharetra lacus ultrices eget. Morbi et ipsum et sapien dapibus facilisis. Integer eget semper nibh. Proin enim nulla, egestas ac rutrum eget, ullamcorper nec turpis.
        </div>
      </div>
    </div>
```


con `data-bs-target="#coll\:collapse1c" `

**Comment by SimonePadovan** [comment]
@astagi peccato, una cosa in piú da gestire...
Non ho capito la patch per l'escaping delle labels invece l'hai fatta per tutti i componenti che la utilizzano ?

**Comment by astagi** [comment]
Si è per tutti @SimonePadovan ma non sono sicuro di includerla a questo punto. Si creerebbe confusione in tal caso, la label gestisce l'escaping ma l'escaping non è gestito dai `data-bs-target` . Lascerei gestire l'escaping all'utente a questo punto, cosa che già bootstrap di base richiede.

**Comment by SimonePadovan** [comment]
e comunque non funzionerebbe inserire l'escaping del tag for della label
