### ISSUE TITLE
Assenza dell'icona Moodle

### ISSUE THREAD

**Issue by fabiojust** [italia/bootstrap-italia#915]
## Versione di Bootstrap Italia

2.5.1

## Comportamento atteso

Nella suite delle icone manca quella di Moodle, piattaforma elearning open-source molto usata in ambito scolastico, anche nelle scuole italiane. Consiglio l'aggiunta, grazie

**Comment by astagi** [comment]
Grazie @fabiojust

**Comment by astagi** [comment]
Il branch linkato includerà nuove icone nella libreria tra cui Moodle
