### ISSUE TITLE
Radio/check si spostano

### ISSUE THREAD

**Issue by SimonePadovan** [italia/bootstrap-italia#917]
2.5.1

Nella form di esempio presente su bootstrap italia (https://italia.github.io/bootstrap-italia/docs/esempi/form/) si verifica un comportamento errato nei radio buttons e checkbox.
Se viene selezionato un radio group o un check box questo si muove in alto.
Lo stesso comportamento succede nelle form sviluppate da me con gli stili della versione 2.5.1.

![immagine](https://github.com/italia/bootstrap-italia/assets/1256958/35aaa7df-37e6-490d-bffd-8f7f258386a5)

**Comment by SimonePadovan** [comment]
bene grazie a te !

**Comment by astagi** [comment]
@SimonePadovan includo questa issue nella prossima iterazione, da capire perchè hanno questo strano comportamento e inserirlo anche in documentazione.

**Comment by SimonePadovan** [comment]
Buongiorno, non ho piú ricevuto ulteriori feedback alle issues aperte

**Comment by astagi** [comment]
@spadovan stiamo lavorando sui fix. Verranno rilasciati nella 2.7.1
