### ISSUE TITLE
Colore alert e notifiche "info" non è uniforme

### ISSUE THREAD

**Issue by gianvitofanelli** [italia/bootstrap-italia#920]
## Versione di Bootstrap Italia

2.5.1

## Comportamento atteso

Il colore delle notifiche e degli alert "info" dovrebbe essere uniforme: blu o grigio.

## Comportamento attuale

Gli alert sono grigi, le notifiche blu.

## Possibili soluzioni

Uniformare il colore. Sul UI Kit è blu, ma essendo informativa potrebbe anche essere corretto tenerla con un grigio più neutro.

**Comment by Fupete** [comment]
cc @zetareticoli

**Comment by zetareticoli** [comment]
Ho rinominato la precedente variante "Info" in "Primary" e aggiunto la nuova con colore grigio, come su BS Italia.
[Vai a Figma](https://www.figma.com/file/2gaQw683ZazAPEILQtFLZF/%5BDesign-system-%E2%80%A8del-Paese%5D---UI-Kit-Italia?type=design&node-id=1445%3A57036&mode=design&t=ytOjZ9RfeekyuYPA-1
)

Ora aggiorno anche il template e la documentazione.
