### ISSUE TITLE
Nuovo componente per sezione dati

### ISSUE THREAD

**Issue by SimonePadovan** [italia/bootstrap-italia#923]
2.5.1

Sarebbe molto comodo/utile avere anche un componente per gestire la sezione dei dati compilabili come previsto ad esempio nella form di compilazione di esempiop per la scuola dell'infanzia (https://italia.github.io/design-comuni-pagine-statiche/servizi/graduatoria-dati-personali.html#applicant-info).
Qui sono previste diverse sezioni (Richiedente, Beneficiario, ...) e sarebbe molto utile disporre di un componente che provveda al rendering della parte in grigio col titolo e sottotiolo e la parte bianca (card ?) con i dati compilabili .

**Comment by spadovan** [comment]
buongiorno attendo risoluzione grazie

**Comment by astagi** [comment]
@spadovan se ti serve adesso come componente puoi prendere ispirazione dal tema per costruirlo nella tua applicazione, lo teniamo sicuramente per le prossime iterazioni
