### ISSUE TITLE
[BUG] Errore: Modulo non trovato

### ISSUE THREAD

**Issue by fla88vus** [italia/bootstrap-italia#924]
## Versione di Bootstrap Italia
La versione di Bootstrap Italia è la 2.6.0

## Comportamento atteso
Corretta visualizzazione componente <Alert> importato come modulo in un'applicazione react typescript

## Comportamento attuale

In fase di compilazione viene restituito questo errore nel terminale: 
Module not found: Error: Can't resolve 'bootstrap-italia/dist/assets/resizer-3x2.svg' in 'C:\Users\***\tree-view-prova\node_modules\design-react-kit\dist\esm'

## Possibili soluzioni
Abbiamo aggiunto manualmente il file svg resizer-3x2.svg nella cartella assets, recuperandolo da un altro progetto in cui avevamo installato solo la dipendenza design-react-kit

## Contesto
1. Abbiamo creato un'applicazione react partendo dal template typescript
2. Abbiamo installato la dipendenza di design-react-kit 
3. Abbiamo installato la dipendenza di bootstrap-italia e relativi fonts
4. Abbiamo implementato nel file App.tsx un componente Alert da visualizzare per testare i css di Bootstrap
5. In fase di compilazione, il terminale ci ha restituito l'errore sopra riportato

Sistema operativo: Windows
IDE: VS Code
Browser: Chrome

**Comment by astagi** [comment]
@fla88vus attenzione l'attuale design react kit non è allineato con bootstrap italia 2.x. Stiamo lavorando ad una nuova versione compatibile probabilmente l'errore è data da questa discrepanza
