### ISSUE TITLE
Radio button: comportamento strano alla selezione nel form

### ISSUE THREAD

**Issue by SimonePadovan** [italia/bootstrap-italia#925]
2.5.1

Nella form di esempio (https://italia.github.io/bootstrap-italia/docs/esempi/form/), se clicco su radio2 non proprio sulla label ma un pochino sotto, il radio sembra selezionato ma il pallino non viene settato.

![immagine](https://github.com/italia/bootstrap-italia/assets/1256958/5d7400b3-a4b9-436b-bf2a-841e3bdd7b85)

**Comment by spadovan** [comment]
sono in attesa di una risoluzione, grazie

**Comment by astagi** [comment]
@spadovan stiamo lavorando sui fix. Verranno rilasciati nella 2.7.1
