### ISSUE TITLE
Navscroll con chiamata AJAX

### ISSUE THREAD

**Issue by SimonePadovan** [italia/bootstrap-italia#927]
2.6.0

se associo una chiamata ajax o un submit ad uno degli elementi del menu navscroll, compare questo errore nella console javascript:

Uncaught TypeError: 'querySelector' called on an object that does not implement interface Element.
    findOne http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:54
    _scrollToHash http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    n http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    _bindEvents http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    _bindEvents http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    _bindEvents http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    NavScroll http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    getOrCreateInstance http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:52
    <anonymous> http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    <anonymous> http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    _execute http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:90
    onDocumentScroll http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:90
    onDocumentScroll http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:90
    onDocumentScroll http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:90
    onDocumentScroll http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:90
    <anonymous> http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:96
    <anonymous> http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:4
    <anonymous> http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT:5
[bootstrap-italia.bundle.min.js.xhtml:54:195](http://localhost:8080/bootstrap-italia-test/javax.faces.resource/js/bootstrap-italia.bundle.min.js.xhtml?ln=ui-italia&v=1.0.0-SNAPSHOT)

**Comment by astagi** [comment]
@SimonePadovan hai uno snippet di codice funzionante in modo da debuggare il tuo problema? grazie

**Comment by SimonePadovan** [comment]
Ciao Andrea, mi dispiace ma il mio snipped utilizzerebbe JSF quindi non so quanto tip possa essere utile

**Comment by spadovan** [comment]
sono in attesa di una risoluzione, grazie
