### ISSUE TITLE
Navscroll su mobile con scrollTop

### ISSUE THREAD

**Issue by SimonePadovan** [italia/bootstrap-italia#928]
2.6.0

Quando si usa Navscroll su mobile insieme al componente "Torna su", il bottone per tornare su scompare dietro alla riga di navigazione creata in fondo alla pagina.

![immagine](https://github.com/italia/bootstrap-italia/assets/1256958/cc3f63bd-d567-4733-88db-a6f5a073263b)

**Comment by spadovan** [comment]
sono in attesa di una risoluzione, grazie
