### ISSUE TITLE
Navscroll su desktop con scrollTop

### ISSUE THREAD

**Issue by SimonePadovan** [italia/bootstrap-italia#929]
2.6.0

Nella versione desktop utilittando Navscroll con scrollTop il bottone scrolltop scompare sotto il menu

![immagine](https://github.com/italia/bootstrap-italia/assets/1256958/46e2692e-8407-44b5-b4ef-eb03a607b4de)

**Comment by SimonePadovan** [comment]
Stessa cosa dicasi per il megamenu nell'header

![immagine](https://github.com/italia/bootstrap-italia/assets/1256958/fe823823-8e82-4134-9ca0-e0a9e26ef652)

**Comment by spadovan** [comment]
sono in attesa di una risoluzione, grazie
