### ISSUE TITLE
TimePicker

### ISSUE THREAD

**Issue by danimog** [italia/bootstrap-italia#934]
## Versione di Bootstrap Italia

2.6.0

## Comportamento atteso

Nel componente time picker esiste una configurazione dei minuti suddivisa in quarti d'ora o mezz'ore?

## Comportamento attuale

Attualmente il componente elenca tutti i minuti

## Possibili soluzioni

Nel progetto Oruga (https://oruga.io/components/timepicker.html) si trova la props incrementMinutes

**Comment by astagi** [comment]
Ciao @danimog forse l'attributo [step](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#step) può fare al caso tuo?

**Comment by danimog** [comment]
@astagi sì, grazie! anche se vedo ancora limitazioni (su alcuni browser tipo Firefox) e nella selezione dei minuti continua però a mostrare tutti i minuti (anche se indico step="900" - ossia 900 secondi = 15 minuti)..
