### ISSUE TITLE
Bordo nel componente Callout

### ISSUE THREAD

**Issue by mariantanase** [italia/bootstrap-italia#937]
## Versione di Bootstrap Italia

2.6.1

## Comportamento atteso

Quando il titolo del componente callout e molto lungo, il bordo sovrascrive il title.
Il codice utilizzato è:

```
<div class="callout note">
<div class="callout-inner">
<div class="callout-title"><span class="text">SCELTA/REVOCA MEDICO DI MEDICINA GENERALE<br />PEDIATRA DI LIBERA SCELTA (ANAGRAFE ASSISTITI),<br />TESSERA SANITARIA</span></div>
Contenuto...
</div>
</div>
```

## Comportamento attuale

![Screenshot 2023-07-17 at 14-35-38 Distretto Sanitario n  34 – Carini – ASP Palermo](https://github.com/italia/bootstrap-italia/assets/3976174/75eeead8-615e-46e5-ae59-440180433408)

**Comment by astagi** [comment]
Probabile che dopo una certa lunghezza sballa il componente, verifico. Grazie @mariantanase

**Comment by mariantanase** [comment]
Ho fatto altri test, magari può aiutare nel debug.

Sembra che se il titolo e lungo, **il testo che viene spostato sull'ultima riga** viene presso in considerazione come larghezza.


Prima:
`<div class="callout-title"><span class="text">INTEGRAZIONE SOCIOSANITARIA E RIABILITAZIONE - CURE DOMICILIARI</span></div>`
![callout-prima](https://github.com/italia/bootstrap-italia/assets/3976174/2affb65e-7a7d-4ada-b1ac-4f0560e13256)

Dopo:
`<div class="callout-title"><span class="text">INTEGRAZIONE SOCIOSANITARIA<br />E RIABILITAZIONE - CURE DOMICILIARI</span></div>`

![callout-dopo](https://github.com/italia/bootstrap-italia/assets/3976174/c5aa340f-6005-465e-8e86-26272e540b38)

**Comment by astagi** [comment]
Grazie @mariantanase , purtroppo il componente ha un limite su questo si, anche a livello grafico la parte del titolo non può essere molto lunga purtroppo. Se occorrono delle informazioni aggiuntive andrebbero messe nel body più che nel titolo.

**Comment by mariantanase** [comment]
Ok grazie
