### ISSUE TITLE
Errore nel funzionamento delle tabs

### ISSUE THREAD

**Issue by zetareticoli** [italia/bootstrap-italia#942]
## Versione di Bootstrap Italia

v2.6.1

## Comportamento atteso

Cliccando su un tab, la classe `.active` dovrebbe attivarsi su questo elemento e rimuoversi da quello precedente attivo.

## Comportamento attuale

In molte varianti di tabs invece, la classe non viene modificata e per gli elementi attivi vengono utilizzati stili sbagliati.

Esempio di malfunzionamento:
- https://italia.github.io/bootstrap-italia/docs/componenti/tab/#tab-testuale
- https://italia.github.io/bootstrap-italia/docs/componenti/tab/#tab-testuale-1
- https://italia.github.io/bootstrap-italia/docs/componenti/tab/#tab-con-icona

Esempio di funzionamento corretto:
- https://italia.github.io/bootstrap-italia/docs/componenti/tab/#tab-testuale-2
- https://italia.github.io/bootstrap-italia/docs/componenti/tab/#tab-con-icona-grande-2

## Possibili soluzioni

Controllare il funzionamento e implementazione del JS della libreria Bootstrap genitore. 
Verificare gli stili CSS applicati.

**Comment by Virtute90** [comment]
Ho controllato la documentazione ufficiale di bootstrap per questa issue e secondo me il funzionamento è corretto che sia così com'è ora.

Ecco le mie considerazioni:

Nella [documentazione ufficiale di bootstrap](https://getbootstrap.com/docs/5.2/components/navs-tabs/#base-nav) è riportato che la classe .active non porta nessun stile:

![image](https://github.com/italia/bootstrap-italia/assets/32056724/545931d1-15ea-47dc-82a5-2019aecf4c27)

Infatti non c'è nessuna implementazione nella libreria genitore, per la parte di navigazione, che gestisce la classe; invece c'è nella parte delle tab con i pannelli associati.

In ogni caso la classe `.active `non dovrebbe essere attiva in base alla pagina in cui si è? Se si, secondo me, è da gestire esternamente.

**Comment by astagi** [comment]
@zetareticoli @Virtute90 ho controllato la issue, in realtà questa cosa accade solo dove non viene utilizzato il pannello, ovvero in una tab che non ha il contenuto associato alla voce. Devo verificare come mai. Negli esempi di tab completa e di utilizzo normale (ovvero clicco e mi cambia il contenuto) questo non accade.
