### ISSUE TITLE
impossibile avviare il container dietro al proxy

### ISSUE THREAD

**Issue by tassoman** [italia/bootstrap-italia#946]
## Versione di Bootstrap Italia

main

## Comportamento atteso

Ho provato ad avviare l'ambiente di sviluppo ma non riesce a scaricare le dipendenze di debian, mentre installa chromium (?)

## Comportamento attuale

```bash
 => ERROR [ 3/12] RUN apt-get update && apt-get install -y chromium                                                                                      8.6s
------
 > [ 3/12] RUN apt-get update && apt-get install -y chromium:
#6 0.943 Ign:1 http://deb.debian.org/debian bookworm InRelease
#6 0.961 Get:2 https://deb.nodesource.com/node_18.x bookworm InRelease [4586 B]
#6 1.066 Ign:3 http://deb.debian.org/debian bookworm-updates InRelease
#6 1.189 Ign:4 http://deb.debian.org/debian-security bookworm-security InRelease
#6 1.223 Get:5 https://deb.nodesource.com/node_18.x bookworm/main amd64 Packages [776 B]
#6 2.047 Ign:1 http://deb.debian.org/debian bookworm InRelease
#6 2.149 Ign:3 http://deb.debian.org/debian bookworm-updates InRelease
#6 2.284 Ign:4 http://deb.debian.org/debian-security bookworm-security InRelease
#6 4.126 Ign:1 http://deb.debian.org/debian bookworm InRelease
#6 4.228 Ign:3 http://deb.debian.org/debian bookworm-updates InRelease
#6 4.365 Ign:4 http://deb.debian.org/debian-security bookworm-security InRelease
#6 8.201 Err:1 http://deb.debian.org/debian bookworm InRelease
#6 8.201   Connection failed [IP: 146.75.54.132 80]
#6 8.303 Err:3 http://deb.debian.org/debian bookworm-updates InRelease
#6 8.303   Connection failed [IP: 146.75.54.132 80]
#6 8.444 Err:4 http://deb.debian.org/debian-security bookworm-security InRelease
#6 8.444   Connection failed [IP: 146.75.54.132 80]
#6 8.454 Fetched 5362 B in 8s (690 B/s)
#6 8.454 Reading package lists...
#6 8.479 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Connection failed [IP: 146.75.54.132 80]
#6 8.479 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Connection failed [IP: 146.75.54.132 80]
#6 8.479 W: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  Connection failed [IP: 146.75.54.132 80]
#6 8.479 W: Some index files failed to download. They have been ignored, or old ones used instead.
#6 8.493 Reading package lists...
#6 8.519 Building dependency tree...
#6 8.523 Reading state information...
#6 8.525 E: Unable to locate package chromium
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/bash -o pipefail -c apt-get update && apt-get install -y chromium]: exit code: 100
```

## Possibili soluzioni

Occorre indicare al container, di usare le variabili d'ambiente ereditate dal docker host

## Contesto

E' proprio necessario tutta questa infrastruttura per avviare il compilatore di interfaccia? Ruby compreso?  Non c'è modo di usare un compilatore a piacere? Esempio Vite?

**Comment by astagi** [comment]
Ciao @tassoman l'architettura di partenza con Docker serve giusto per tirar su l'ambiente senza doversi installare tutto. Al momento non abbiamo le forze necessarie per riuscire a spostare tutto (lib + documentazione) su Node e andare verso un unico ambiente. Non so perchè non riesce a localizzare il pacchetto chromium (forse errore di connessione?), prova a dare un rebuild totale dell'immagine cancellando la cache Docker.

**Comment by astagi** [comment]
@tassoman qualche news qua?

**Comment by tassoman** [comment]
Riesco ad avviare la generazione dei bundle con node però manca il layout html a cui attaccarli, poiché l'ambiente di sviluppo è la documentazione stessa.

Forse dovevo inziare dal "playground". Così però, ipotizzo che non otterrei i bundle modificabili ma una build già fatta...  
Il react kit, mi pare sia stato abbandonato...

**Comment by tassoman** [comment]
Ho capito, grazie. Mettere il browser nel container come dipendenza secondo me è eccessivo, sarebbe più opportuno presupporre che lo sviluppatore il browser ce l'abbia, già configurato. E che non sia necessariamente chrome/chromium.

**Comment by astagi** [comment]
@tassoman si vero, a dirla tutta non ricordo la dipendenza di chromium per cosa sia necessaria, appena ho un momento indago. Ad ogni modo ci sposteremo verso l'utilizzo di altri builder di documentazione rispetto a Jekyll.

**Comment by tassoman** [comment]
D'accordo, grazie. Nel frattempo, provo anche io, se riesco a combinare qualcosa provo a sottoporlo tramite PR.  

Parlando di page builder, l'ecosistema è abbastanza ampio, spesso dipendente dal linguaggio principalmente utilizzato. In questo momento sarebbero interessanti Vitepress e MkDocs. Ma in futuro, chissà?

**Comment by astagi** [comment]
Grazie a te @tassoman , si Vitepress e MkDocs sono molto interessanti, il grosso del lavoro sarà riportare tutta l'automazione fatta con Ruby e la parte template di Jekyll da modificare. Sicuramente però comincia a sentirsi la necessità. Fammi sapere, se per te va bene possiamo anche chiudere la issue.

**Comment by tassoman** [comment]
D'accordo, nel caso occorre parlarne in un altra issue, mi sa che qui siamo finiti fuori tema 🤔
