### ISSUE TITLE
Vulnerabilità progressbar.js

### ISSUE THREAD

**Issue by antoniobenci87** [italia/bootstrap-italia#947]
La versione di bootstrap italia utilizzata è la 2.6.1, è affetta da una vulnerabilità che riguarda progressbar.js

avete news a riguardo? 
è possibile che tutte le versioni di bootstrap italia 2.x  sono affette da questa vulnerabilità?

**Comment by astagi** [comment]
Grazie @antoniobenci87 ho scritto su twitter anche al maintainer purtroppo nessuna risposta. Sembra sparito dai radar 😞

**Comment by antonio-giovannetti** [comment]
Ciao, avete notizie riguardo questa issue? Oppure workaround per utilizzare senza rischi la versione 2.6.x?

**Comment by arturu** [comment]
Nel progetto drupal ho usato un primo workaround in questo commit https://git.drupalcode.org/project/bootstrap_italia/-/commit/5d4b0d740852616ee115511ce635d2623fed0088 che poi ho perfezionato con questo https://git.drupalcode.org/project/bootstrap_italia/-/commit/7ba749caeffc60a4e0893d07a8a272f32053492b . Praticamente ho rimosso il componente donuts

**Comment by astagi** [comment]
Ho scritto anche all'azienda dove lavora, non ho risposta da due settimane.
