### ISSUE TITLE
Label radio toggle button non funzionante

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/bootstrap-italia#950]
## Versione di Bootstrap Italia

2.6.0

## Comportamento atteso

https://getbootstrap.com/docs/5.2/forms/checks-radios/#radio-toggle-buttons
Lo stato active deve essere solo sul pulsante selezionato

## Comportamento attuale

La label dei pulsanti, una volta premuti, rimangono sempre con la classe active.
Questo è dovuto al meccanisco che fissa la label in alto quando un input contiene qualcosa o è selezionato.
https://italia.github.io/bootstrap-italia/docs/form/introduzione/#organizzazione-dei-campi
![Immagine 2023-08-29 111753](https://github.com/italia/bootstrap-italia/assets/20642463/161bd73d-a598-4b81-8ad9-fece3f2ace87)

## Possibili soluzioni

è possibile che funzioni esattamente come nella documentazione di Bootstrap?

**Comment by Virtute90** [comment]
Non ho capito la domanda, fai riferimento ad un radio button nel primo caso ma nel secondo ad un input di tipo testo.

**Comment by PiemP** [comment]
Questa problematica credo sia collegata alla #954 . Io non ho questo problema in quanto uso il codice che ho rilasciato nella PR #955 e vado ad escludere dagli elementi con le "label attive" gli input di tipo radio e di tipo checkbox. 

Risolta la #954 si risolve anche questa.

**Comment by astagi** [comment]
Grazie @PiemP ! Sarebbe quasi utile creare un esempio all'interno della documentazion, ci penso. Intano assegno questa issue alla tua PR.

**Comment by astagi** [comment]
Grazie @AlessandroVecchi quindi tu hai utilizzato le classi bootstrap native? cioè hai fatto una cosa di questo genere?

```html
<input type="radio" class="btn-check" name="options" id="option4" autocomplete="off">
<label class="btn btn-secondary" for="option4">Radio</label>
```

**Comment by AlessandroVecchi** [comment]
> Grazie @AlessandroVecchi quindi tu hai utilizzato le classi bootstrap native? cioè hai fatto una cosa di questo genere?
> 
> ```
> <input type="radio" class="btn-check" name="options" id="option4" autocomplete="off">
> <label class="btn btn-secondary" for="option4">Radio</label>
> ```
esatto

**Comment by astagi** [comment]
@AlessandroVecchi con la PR si risolve il problema (cc @PiemP ) 
<img width="454" alt="image" src="https://github.com/italia/bootstrap-italia/assets/537363/83b6afa1-cd3f-42b7-af9a-39dd761d26e3">

**Comment by AlessandroVecchi** [comment]
Ciao,
Non ho capito bene se sia dovuto a questa PR ma adesso riscontro un comportamento sbagliato che non rispecchia quello di bootstrap: https://getbootstrap.com/docs/5.2/forms/checks-radios/#radio-toggle-buttons

In particolare non vengono mantenute le classi contestuali.
nel mio caso

`<label class="btn btn-outline-success" ...`

![Screenshot 2024-01-12 153625](https://github.com/italia/bootstrap-italia/assets/20642463/c10a4674-e06b-402a-a928-40009225f67e)

**12:30** dovrebbe essere totalmente verde con testo bianco invece perde tutta la formattazione.
