### ISSUE TITLE
Label nei form non sale in caso di POST HTTP - versione 2.5.1

### ISSUE THREAD

**Issue by PiemP** [italia/bootstrap-italia#954]
## Versione di Bootstrap Italia

2.5.1

## Comportamento atteso

Le label dei campi valorizzati di un form dovrebbero rimanere sopra il campo quando si rientra sulla stessa pagina dopo una richiesta POST che termina con una validazione andata male. 

![image](https://github.com/italia/bootstrap-italia/assets/2736009/7fba94cf-1913-4ca2-a6cc-f7aef31418b4)

## Comportamento attuale

![image](https://github.com/italia/bootstrap-italia/assets/2736009/38a2b765-a800-4bb9-9006-fd98babdf800)

## Possibili soluzioni

modificare lo script che gestisce quel comportamento in modo che possa gestire il fatto che il campo sia valorizzato al nuovo caricamento della pagina o un alternativa per disabilitare questo addon: questo perché, anche se si aggiunge la classe `active` alla label, quando si entra ed esce dal campo non valorizzato la label riprenderà a muoversi dentro e fuori dal campo.

**Comment by PiemP** [comment]
La problematica non riguarda solo qusta cosa ma ci sono alcuni input tipo i `type="number"` che non si comportano correttamente. La `textarea` risulta un pò strana come interazione. 

La soluzione "facile" è aggiungere un attributo (tipo `it-bs-static`) alle label che si vuole che non si muovano di modo che non venga fatto il binding degli eventi dentro la classe `InputLabel`, così per i campi che non vuoi questo comportamento lo puoi disabilitare. 

Resta il fatto che va documentata questa aggiunta.

**Comment by astagi** [comment]
Grazie @PiemP ! ma la PR è pronta per la review quindi? la vedo in draft

**Comment by PiemP** [comment]
Ciao @astagi, ho preparato la PR ma non sono sicuro sia una soluzione "bella" a livello di codice. Quello che credo è che forse, questa funzionalità. dovrebbe essere rivista anche in chiave di una maggiore accessibilità (avere una label che si muove e diventa più piccola potrebbe essere problematica per persone che hanno una percezione differente dal normale). É per quello che ho lasciato il PR in draft: vorrei stimolare un pensiero a riguardo al termine del quale, se mi dite che va bene così, metto il PR in review e fate quello che volete.

Grazie.

**Comment by PiemP** [comment]
> Grazie @PiemP ! ma la PR è pronta per la review quindi? la vedo in draft

PS. chiaramente se mi dite che il PR può andare bene preparo anche la documentazione relativa alla gestione delle label "attive" nel caso in cui si decida di usare l'attributo `it-bs-static`.

**Comment by AlessandroVecchi** [comment]
Il problema è in generale su tutti i campi di input.
Anche se si imposta la classe "active" su un campo, quando si toglie il focus la classe "active" sparisce e la label torna all'interno del campo. L'unico modo per evitarlo è inserire un placeholder ma è chiaro che non è una soluzione sempre praticabile.

Non c'è un modo per disattivare queso comportamento delle label. L'animanazione è carina ma mi sta creando un mare di problemi nell'allineamento dei campi!

**Comment by AlessandroVecchi** [comment]
Concordo, ho un sacco di form (realizzate su base bootstrap 4) da portare al nuovo layout ma le modifiche da fare sono così tante per adattarle che praticamente devo riscrivere il codice da capo e fare mille test.

Magari si potrebbe pensare ad una versione che sfrutta il layout base di boostrap 5, senza override, ed una classe da applicare alla form che invece abilita la versione custom del modello.

**Comment by PiemP** [comment]
Credo che per risolvere questo discorso dovremmo appoggiarci alla funzione delle [Floating label](https://getbootstrap.com/docs/5.2/forms/floating-labels/) di Bootstrap. 

Questo comporta il fatto di modificare/rimuovere il codice relativo alle **Label attive** di modo che le label by default siano funzionali, modificare il codice CSS delle **Floating label** per rispecchiare la grafica di Bootstrap Italia e aggiornare la documentazione.

**Comment by PiemP** [comment]
@astagi Tieni conto che se adottiamo la soluzione che ho proposto io nel PR, qualche meccanismo che potrebbe essere utile per chi produce SPA (Single Page Application) potrebbe mancare (io non ho testato la cosa). 

Lo schema che avevate messo in pratica inizialmente "attivava" la label quando l'utente faceva qualcosa nella pagina. 
Con la mia modifica, le label, vengono attivate una volta che la pagina finisce il caricamento del DOM di modo che dopo un POST o un GET le label assumano la posizione "corretta". 

Nelle SPA il caricamento del DOM avviene anche durante la navigazione della pagina e questo potrebbe far sì che alcuni elementi non vengano mai "attivati". E` stata testata questa eventualità?

Inoltre, con la soluzione del mio PR, i "Radio toggle buttons" che @AlessandroVecchi cita nella issue #950 non verrebbe risolta.

Io ho fatto il PR sulla circostanza che posso testare. Non ho sufficiente esperienza in SPA per testare il corretto funzionamento.

Mi piacerebbe molto andare a fondo della questione ma sono sicuro che ci vorrebbe molto tempo e già il PR sui campi numerici mi ha tolto molto tempo libero.
