### ISSUE TITLE
Aggiornamento e aggiunta icone

### ISSUE THREAD

**Issue by SimoWZ** [italia/bootstrap-italia#960]
## Versione di Bootstrap Italia

2.6.2

## Comportamento atteso

Aggiornamento icona Twitter in X
Aggiunta icone Apple e Android per collegamento link app mobile nella barra social

## Comportamento attuale

Non presenti

**Comment by astagi** [comment]
@SimoWZ i designer sono all'opera, grazie della segnalazione :)

**Comment by astagi** [comment]
@SimoWZ rilasciata versione `2.7.1` con le icone 🚀
