### ISSUE TITLE
Assenza di documentazione per i footer

### ISSUE THREAD

**Issue by simomosi** [italia/bootstrap-italia#963]
## Versione di Bootstrap Italia

2.6.2

## Comportamento attuale

Non è presente la documentazione per la creazione di un footer.  
Nei sorgenti ho trovato le classi per crearne uno, immagino sia stata una dimenticanza.

Attualmente le pagine da cui prendere una struttura per il footer sono le seguenti:
- [esempi/template-vuoto](https://italia.github.io/bootstrap-italia/docs/esempi/template-vuoto/)
- [bootstrap-italia-playground/index.html](https://github.com/italia/bootstrap-italia-playground/tree/main)
- [esempi/comuni/footer.html](https://github.com/italia/bootstrap-italia/blob/main/_includes/esempi/comuni/footer.html)

## Comportamento atteso

Inserire una sezione con la struttura dei footer nella sezione "Menu di navigazione"

**Comment by astagi** [comment]
Grazie @simomosi si il footer ad oggi non ha una sezione dedicata, aggiungerlo può essere di aiuto più che guardare gli esempi. Si tratta di una sezione abbastanza libera ma alcune cose sono a tutti gli effetti da inserire.

**Comment by astagi** [comment]
Grazie @simomosi si il footer ad oggi non ha una sezione dedicata, aggiungerlo può essere di aiuto più che guardare gli esempi. Si tratta di una sezione abbastanza libera ma alcune cose sono a tutti gli effetti da inserire.
