### ISSUE TITLE
Tooltip Input text

### ISSUE THREAD

**Issue by Gianni-Luca** [italia/bootstrap-italia#970]
Buongiorno, vi scrivo per sapere se è stato previsto il campo di input text con relativo tooltip esplicativo. Attualmente su BI Italia è presente il caso d’uso di input con icona a sinistra o tooltip visualizzabile come link nel testo o pulsante unico.

**Comment by Virtute90** [comment]
Ciao, devi semplicemente aggiungere il tooltip nel campo input, ho fatto un esempio al volo:

https://codepen.io/Virtute90/pen/RwEJaoP

**Comment by Gianni-Luca** [comment]
Ciao, l'azione di tooltip deve essere visibile nel campo tramite icona (?). Cosi non è proprio accessibile, l'utente non riesce a capire se c'è un tooltip e dove è posizionato.

**Comment by Virtute90** [comment]
> Ciao, l'azione di tooltip deve essere visibile nel campo tramite icona (?). Cosi non è proprio accessibile, l'utente non riesce a capire se c'è un tooltip e dove è posizionato.

Ho aggiornato l'esempio nella risposta precedente, l'icona non la carica ma nel tuo ambiente dovrebbe funzionare.

Ti consiglio di prendere in considerazione l'esempio nella documentazione: https://italia.github.io/bootstrap-italia/docs/form/input/#utilizzo-di-placeholder-e-label

![image](https://github.com/italia/bootstrap-italia/assets/32056724/6bcefc3c-480b-49cd-bd39-600f260eea76)

A mio parere è la soluzione più "pulita"

**Comment by astagi** [comment]
Grazie @Virtute90
