### ISSUE TITLE
Focus campi input

### ISSUE THREAD

**Issue by Gianni-Luca** [italia/bootstrap-italia#971]
Buongiorno, esiste su bootstrap italia la classe per il campo input con focus attivo? Vi chiedo questo perchè sto sviluppando un form in cui alcuni campi possono essere modificati, ma con gli stili attuali sembrano tutti uguali, sia quelli in sola lettura che quelli modificabili.

**Comment by Virtute90** [comment]
Il focus lo imposti via javascript:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

**Comment by Gianni-Luca** [comment]
Si chiaro ma manca una classe unica su BI per uniformarla in tutti gli applicativi. Ogni sviluppatore lo applicato in modo differente. Inoltre su BI non c'è differenza fra un campo input active e un campo input read only.

**Comment by astagi** [comment]
@Gianni-Luca che modifica proporresti?
