### ISSUE TITLE
Amministrazione trasparente - Uncaught Error: Object of class WP_Error could not be converted to string

### ISSUE THREAD

**Issue by emanueless** [italia/bootstrap-italia#991]
## Versione di Bootstrap Italia

2.5.1

## Comportamento attuale
 La pagina dell' Amministrazione trasparente non si apre perché nella creazione dei link delle categorie e sottocategorie riceve anche dei dati di tipo WP_Error invece di classiche stringhe.

I file affetti da questo problema sono i seguenti: 
/page-templates/amministrazione-trasparente.php
Fatal error
: Uncaught Error: Object of class WP_Error could not be converted to string in /var/www/vhosts/SCUOLA.edu.it/httpdocs/wp-content/themes/design-scuole-wordpress-theme-main/page-templates/amministrazione-trasparente.php:62

/template-parts/search/filters-amministrazione.php
Fatal error: Uncaught Error: Object of class WP_Error could not be converted to string in /var/www/vhosts/SCUOLA.edu.it/httpdocs/wp-content/themes/design-scuole-wordpress-theme-main/template-parts/search/filters-amministrazione.php:43

## Possibili soluzioni
Per risolvere il problema ho proceduto alle seguenti modifiche:

/page-templates/amministrazione-trasparente.php LINEA 62 sostituita con:
`// FIX Uncaught Error: Object of class WP_Error could not be converted to string
                                        $testString = get_term_link( get_term_by('name', $value, 'amministrazione-trasparente'), 'amministrazione-trasparente' );
                                        if (gettype($testString)=="string") {
                                            $atreturn .= '<a href="' .$testString.'" title="' . $value . '">' . $value . '</a>';
                                            $atreturn .= '</li>';
                                        }`
 

/template-parts/search/filters-amministrazione.php LINEA 43 sostituita con:
`// FIX Uncaught Error: Object of class WP_Error could not be converted to string
                    $testString = get_term_link( get_term_by('name', $value, 'amministrazione-trasparente'), 'amministrazione-trasparente' );

                    if (gettype($testString)=="string") {
                       $atreturn_body .= ' <label class="mb-0" for="check-'.$term->slug.'"><a href="' . $testString . '">'.$term->name.'</a></label>';
                        $atreturn_body .= '</div>';
                        $atreturn_body .= '</li>';
                    }`

**Comment by astagi** [comment]
@emanueless questa issue tracker è relativa al progetto Bootstrap Italia.
