### ISSUE TITLE
Abbiamo bisogno di un componente Megamenu accessibile e testato 

### ISSUE THREAD

**Issue by Fupete** [italia/bootstrap-italia#995]
## Comportamento atteso

Avere un componente [Megamenu](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/megamenu/) accessibile e testato come l'implementazione realizzata su https://designers.italia.it ([code](https://github.com/italia/designers.italia.it/tree/main/src/components/megamenu)) ([articolo](https://www.webaccessibile.org/approfondimenti/un-mega-menu-accessibile/))

## Comportamento attuale

Durante l'implementazione di designers.italia.it sono stati corretti bug di a11y. 
Solo a titolo di esempio: 
- il pulsante di apertura deve avere semantica `<button>`e non `<a>`;
- i link "Vedi tutti" per ogni colonna/sezione tutti uguali non sono corretti, abbisognano di testo diverso o almeno aria-label ad hoc;
- i link abbisognano di essere distinti come link non solo dal colore, specialmente quando presenti anche testo descrittivo o testo di altra natura;
- ...

## Possibili soluzioni

"Copiare" quanto già stato fatto su https://designers.italia.it. 

cc @astagi @cfabry

**Comment by cfabry** [comment]
Si, è importante inserire il componente "megamenu" così come implementato su Designer Italia. [Quelli presenti attualmente ](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/megamenu/) andrebbero uniformati e adattati o valutare se eliminarli del tutto.

**Comment by Fupete** [comment]
Ancora un passo avanti, update e cose da fare: https://github.com/italia/bootstrap-italia/pull/1025#issuecomment-1842690633

**Comment by Fupete** [comment]
@astagi La PR https://github.com/italia/bootstrap-italia/pull/1036#issuecomment-1853898407 è pronta. Aspetta solo tua review e merge per il rilascio della v2.8. Let me know.
