### ISSUE TITLE
Componente chips: controllare dimensioni e spaziature

### ISSUE THREAD

**Issue by Fupete** [italia/bootstrap-italia#997]
## Comportamento atteso

Coerenza del componente chips con UI Kit Italia

## Comportamento attuale

In Bootstrap Italia esistono le varianti alte 24px (default) e 32px (lg). 
In UI Kit Italia esistono le varianti alte 24px (small), 40px (medium) e 48px (large). 

![Chips in Bootstrap Italia](https://github.com/italia/bootstrap-italia/assets/6736103/430fdca8-906b-427d-a1ec-29104a4df030)
![Chips in UI Kit Italia](https://github.com/italia/bootstrap-italia/assets/6736103/02cc0822-af2c-4f71-ae92-07faa5307384)

Nei gruppi di chip inoltre in Bootstrap Italia è da verificare la spaziatura verticale. 

![Gruppi di chips in Bootstrap Italia](https://github.com/italia/bootstrap-italia/assets/6736103/4923c788-2769-4f2c-a590-2eeded8d30a1)

## Contesto

Coerenza tra risorse del design system del Paese e usabilità componente.

cc @zetareticoli @astagi

**Comment by AlessandroVecchi** [comment]
Mia opinione, 40px e 48px mi sembrano molto grandi.
Inoltre per una scalatura più corretta sarebbe meglio 24px (small), **36px** (medium) e 48px (large).

**Comment by astagi** [comment]
@Fupete @zetareticoli lascio la parola a voi designer per il dubbio di @AlessandroVecchi

**Comment by Fupete** [comment]
@astagi @zetareticoli io direi intanto di risolvere il bug della spaziatura verticale nei gruppi di icone. Che ha parecchio impatto anche sulle card di Designers Italia per esempio 🤷  

![immagine](https://github.com/italia/bootstrap-italia/assets/6736103/be4c5792-9cf0-41d3-8a51-837b8eeeff8a)
